/*
 * Copyright 2026 the original author or authors.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
@file:OptIn(
    org.jetbrains.kotlin.ir.symbols.UnsafeDuringIrConstructionAPI::class,
    org.jetbrains.kotlin.DeprecatedForRemovalCompilerApi::class,
)
package org.openrewrite.kotlin.recipe.internal

import org.jetbrains.kotlin.backend.common.extensions.IrPluginContext
import org.jetbrains.kotlin.backend.common.lower.DeclarationIrBuilder
import org.jetbrains.kotlin.ir.builders.irBlockBody
import org.jetbrains.kotlin.ir.builders.irCall
import org.jetbrains.kotlin.ir.builders.irGet
import org.jetbrains.kotlin.ir.builders.irReturn
import org.jetbrains.kotlin.ir.declarations.IrModuleFragment
import org.jetbrains.kotlin.ir.declarations.IrSimpleFunction
import org.jetbrains.kotlin.ir.expressions.IrExpression
import org.jetbrains.kotlin.ir.types.classFqName
import org.jetbrains.kotlin.ir.util.kotlinFqName
import org.jetbrains.kotlin.ir.visitors.IrVisitorVoid
import org.jetbrains.kotlin.ir.visitors.acceptChildrenVoid
import org.jetbrains.kotlin.name.CallableId
import org.jetbrains.kotlin.name.FqName
import org.jetbrains.kotlin.name.Name

/**
 * IR-phase body generator for top-level extension functions synthesized by
 * [RecipeFirMappedTypeFallbackExtension]. The FIR-side generator emits each
 * extension with `withGeneratedDefaultBody()`, which produces a stub that
 * throws "Stub for declaration generated by Plugin[MappedTypeFallbackKey]"
 * at runtime. This generator walks every IR file, finds those stubs, and
 * replaces each body with a direct call to the underlying Java instance
 * method on the receiver — bytecode-identical to what the JDK 15+ author
 * would have written if Kotlin's mapped-type customizer surfaced the method
 * directly.
 *
 * Implementation note: at the JVM level `kotlin.String` and `java.lang.String`
 * are the same class, so the IR `invokeVirtual` site is type-safe — the
 * extension receiver value IS a `java.lang.String` instance.
 */
internal object MappedTypeFallbackBodyGenerator {

    /**
     * Marker used both here and in [RecipeFirMappedTypeFallbackExtension]
     * to identify the generated extensions. The FIR-generator origin name
     * shows up on each [IrSimpleFunction] as `<key.toString()>` — checking
     * by string keeps us out of GeneratedDeclarationKey identity-equality
     * complications across the FIR→IR boundary.
     */
    private const val ORIGIN_NAME = "MappedTypeFallbackKey"

    fun generate(moduleFragment: IrModuleFragment, pluginContext: IrPluginContext) {
        val collected = mutableListOf<IrSimpleFunction>()
        moduleFragment.acceptChildrenVoid(object : IrVisitorVoid() {
            override fun visitElement(element: org.jetbrains.kotlin.ir.IrElement) {
                element.acceptChildrenVoid(this)
            }

            override fun visitSimpleFunction(declaration: IrSimpleFunction) {
                if (isMappedTypeFallback(declaration)) {
                    collected += declaration
                }
                super.visitSimpleFunction(declaration)
            }
        })

        for (fn in collected) {
            generateBodyFor(fn, pluginContext)
        }
    }

    private fun isMappedTypeFallback(fn: IrSimpleFunction): Boolean {
        // The FIR-side origin uses our GeneratedDeclarationKey's class name.
        // The IR origin is a string-keyed identifier; we compare both formats
        // to be tolerant of K2 internal renames.
        val name = fn.origin.toString()
        return name.contains(ORIGIN_NAME)
    }

    private fun generateBodyFor(fn: IrSimpleFunction, pluginContext: IrPluginContext) {
        // Find the receiver parameter — extension receiver in IR parameter
        // list (since 2.1.20 parameters are unified, use the legacy
        // extensionReceiverParameter accessor for clarity).
        val extReceiver = fn.extensionReceiverParameter ?: return
        val receiverClassFqn = extReceiver.type.classFqName ?: return

        // Resolve the Java instance method on the corresponding java.lang.*
        // / java.util.* class via reflection on the JVM class. Since
        // kotlin.String -> java.lang.String at JVM level the lookup uses the
        // Kotlin class FQN directly when it resolves to a class on the
        // compile classpath, otherwise falls back to the
        // `JavaToKotlinClassMap.mapKotlinToJava` route.
        val javaClassFqn = resolveJavaCounterpart(receiverClassFqn) ?: return

        // Find the corresponding member function symbol via the IR plugin
        // context. We construct a CallableId for the Java class and look up
        // by name, then match on arity (we don't try to disambiguate
        // overloads — the JVM bytecode will resolve via descriptor).
        val javaClassId = org.jetbrains.kotlin.name.ClassId.topLevel(FqName(javaClassFqn))
        val classSymbol = pluginContext.referenceClass(javaClassId) ?: return
        val candidates = classSymbol.owner.declarations
            .filterIsInstance<IrSimpleFunction>()
            .filter { it.name.asString() == fn.name.asString() }
            .filter { it.dispatchReceiverParameter != null }
            .filter { it.valueParameters.size == fn.valueParameters.size }

        // Disambiguate overloads by erased descriptor matching against our
        // synthetic extension. If multiple candidates remain we pick the
        // first — the bytecode-level overload resolution at the call site
        // will use exact descriptors.
        val javaFn = candidates.firstOrNull() ?: return

        val body = DeclarationIrBuilder(
            generatorContext = pluginContext,
            symbol = fn.symbol,
            startOffset = fn.startOffset,
            endOffset = fn.endOffset,
        ).irBlockBody {
            val callExpr = irCall(javaFn.symbol).apply {
                dispatchReceiver = irGet(extReceiver)
                for ((idx, vp) in fn.valueParameters.withIndex()) {
                    putValueArgument(idx, irGet(vp))
                }
            } as IrExpression
            if (fn.returnType.isUnit()) {
                +callExpr
            } else {
                +irReturn(callExpr)
            }
        }
        fn.body = body
    }

    private fun org.jetbrains.kotlin.ir.types.IrType.isUnit(): Boolean =
        classFqName?.asString() == "kotlin.Unit"

    /**
     * Resolve the Java class FQN that backs a Kotlin mapped-type class FQN.
     * Mirrors `JavaToKotlinClassMap.mapKotlinToJava` but works on FqName
     * directly so we don't need the reflective backdoor from the FIR side.
     */
    private fun resolveJavaCounterpart(kotlinFqn: FqName): String? {
        // Hard-coded the most common mappings inline to avoid reflection
        // overhead and to keep the IR pass independent of FIR-time discovery.
        return when (kotlinFqn.asString()) {
            "kotlin.String" -> "java.lang.String"
            "kotlin.CharSequence" -> "java.lang.CharSequence"
            "kotlin.Any" -> "java.lang.Object"
            "kotlin.Comparable" -> "java.lang.Comparable"
            "kotlin.Number" -> "java.lang.Number"
            "kotlin.Throwable" -> "java.lang.Throwable"
            "kotlin.Boolean" -> "java.lang.Boolean"
            "kotlin.Byte" -> "java.lang.Byte"
            "kotlin.Char" -> "java.lang.Character"
            "kotlin.Short" -> "java.lang.Short"
            "kotlin.Int" -> "java.lang.Integer"
            "kotlin.Long" -> "java.lang.Long"
            "kotlin.Float" -> "java.lang.Float"
            "kotlin.Double" -> "java.lang.Double"
            "kotlin.collections.Iterable", "kotlin.collections.MutableIterable" -> "java.lang.Iterable"
            "kotlin.collections.Collection", "kotlin.collections.MutableCollection" -> "java.util.Collection"
            "kotlin.collections.List", "kotlin.collections.MutableList" -> "java.util.List"
            "kotlin.collections.Set", "kotlin.collections.MutableSet" -> "java.util.Set"
            "kotlin.collections.Map", "kotlin.collections.MutableMap" -> "java.util.Map"
            "kotlin.collections.Map.Entry", "kotlin.collections.MutableMap.MutableEntry" -> "java.util.Map\$Entry"
            "kotlin.collections.Iterator", "kotlin.collections.MutableIterator" -> "java.util.Iterator"
            "kotlin.collections.ListIterator", "kotlin.collections.MutableListIterator" -> "java.util.ListIterator"
            else -> null
        }
    }
}
