package org.openrewrite.maven;

import org.junit.jupiter.api.Test;
import org.openrewrite.DocumentExample;
import org.openrewrite.test.RewriteTest;

import static org.assertj.core.api.Assertions.assertThat;
import static org.openrewrite.maven.Assertions.pomXml;

class ChangeDependencyVersionValueTest implements RewriteTest {

    @DocumentExample
    @Test
    void changeVersionValue() {
        rewriteRun(
          spec -> spec.recipe(new ChangeDependencyVersionValue(
            "jakarta.activation",
            "jakarta.activation-api",
            "2.1.0",
            ChangeDependencyVersionValue.VersionLocation.MANAGED_DEPENDENCY.name()
          )),
          pomXml(
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <dependencyManagement>
                      <dependencies>
                          <dependency>
                              <groupId>jakarta.activation</groupId>
                              <artifactId>jakarta.activation-api</artifactId>
                              <version>1.2.0</version>
                          </dependency>
                      </dependencies>
                  </dependencyManagement>
              </project>
              """,
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <dependencyManagement>
                      <dependencies>
                          <dependency>
                              <groupId>jakarta.activation</groupId>
                              <artifactId>jakarta.activation-api</artifactId>
                              <version>2.1.0</version>
                          </dependency>
                      </dependencies>
                  </dependencyManagement>
              </project>
              """
          )
        );
    }

    @Test
    void changeVersionValueWithDynamicVersion() {
        rewriteRun(
          spec -> spec.recipe(new ChangeDependencyVersionValue(
            "jakarta.activation",
            "jakarta.activation-api",
            "2.1.x",
            ChangeDependencyVersionValue.VersionLocation.MANAGED_DEPENDENCY.name()
          )),
          pomXml(
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <dependencyManagement>
                      <dependencies>
                          <dependency>
                              <groupId>jakarta.activation</groupId>
                              <artifactId>jakarta.activation-api</artifactId>
                              <version>1.2.0</version>
                          </dependency>
                      </dependencies>
                  </dependencyManagement>
              </project>
              """,
            spec -> spec.after(pom -> {
                assertThat(pom).containsPattern("<version>2.1.(\\d+)</version>");
                return pom;
            })
          )
        );
    }

    @Test
    void latestPatchVersionValue() {
        rewriteRun(
          spec -> spec.recipe(new ChangeDependencyVersionValue(
            "jakarta.activation",
            "jakarta.activation-api",
            "latest.patch",
            null,
            false,
            ChangeDependencyVersionValue.VersionLocation.MANAGED_DEPENDENCY.name()
          )),
          pomXml(
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <dependencyManagement>
                      <dependencies>
                          <dependency>
                              <groupId>jakarta.activation</groupId>
                              <artifactId>jakarta.activation-api</artifactId>
                              <version>1.2.0</version>
                          </dependency>
                      </dependencies>
                  </dependencyManagement>
              </project>
              """,
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <dependencyManagement>
                      <dependencies>
                          <dependency>
                              <groupId>jakarta.activation</groupId>
                              <artifactId>jakarta.activation-api</artifactId>
                              <version>1.2.2</version>
                          </dependency>
                      </dependencies>
                  </dependencyManagement>
              </project>
              """
          )
        );
    }

    @Test
    void changePropertyVersionValue() {
        rewriteRun(
          spec -> spec.recipe(new ChangeDependencyVersionValue(
            "jakarta.activation",
            "jakarta.activation-api",
            "2.1.0",
            ChangeDependencyVersionValue.VersionLocation.MANAGED_DEPENDENCY.name()
          )),
          pomXml(
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <properties>
                          <javax.activation.version>1.2.0</javax.activation.version>
                  </properties>
                  <dependencyManagement>
                      <dependencies>
                          <dependency>
                              <groupId>jakarta.activation</groupId>
                              <artifactId>jakarta.activation-api</artifactId>
                              <version>${javax.activation.version}</version>
                          </dependency>
                      </dependencies>
                  </dependencyManagement>
              </project>
              """,
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <properties>
                          <javax.activation.version>2.1.0</javax.activation.version>
                  </properties>
                  <dependencyManagement>
                      <dependencies>
                          <dependency>
                              <groupId>jakarta.activation</groupId>
                              <artifactId>jakarta.activation-api</artifactId>
                              <version>${javax.activation.version}</version>
                          </dependency>
                      </dependencies>
                  </dependencyManagement>
              </project>
              """
          )
        );
    }

    @Test
    void changeProfileManagedDependencyVersionValue() {
        rewriteRun(
          spec -> spec.recipe(new ChangeDependencyVersionValue(
            "jakarta.activation",
            "jakarta.activation-api",
            "2.1.0",
            ChangeDependencyVersionValue.VersionLocation.MANAGED_DEPENDENCY.name()
          )),
          pomXml(
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <profiles>
                    <profile>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>jakarta.activation</groupId>
                                  <artifactId>jakarta.activation-api</artifactId>
                                  <version>1.2.0</version>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                    </profile>
                  </profiles>
              </project>
              """,
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <profiles>
                    <profile>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>jakarta.activation</groupId>
                                  <artifactId>jakarta.activation-api</artifactId>
                                  <version>2.1.0</version>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                    </profile>
                  </profiles>
              </project>
              """
          )
        );
    }

    @Test
    void changePropertyVersionProfileManagedDependency() {
        rewriteRun(
          spec -> spec.recipe(new ChangeDependencyVersionValue(
            "jakarta.activation",
            "jakarta.activation-api",
            "2.1.0",
            ChangeDependencyVersionValue.VersionLocation.MANAGED_DEPENDENCY.name()
          )),
          pomXml(
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <properties>
                          <javax.activation.version>1.2.0</javax.activation.version>
                  </properties>
                  <profiles>
                    <profile>
                      <id>test</id>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>jakarta.activation</groupId>
                                  <artifactId>jakarta.activation-api</artifactId>
                                  <version>${javax.activation.version}</version>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                    </profile>
                  </profiles>
              </project>
              """,
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <properties>
                          <javax.activation.version>2.1.0</javax.activation.version>
                  </properties>
                  <profiles>
                    <profile>
                      <id>test</id>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>jakarta.activation</groupId>
                                  <artifactId>jakarta.activation-api</artifactId>
                                  <version>${javax.activation.version}</version>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                    </profile>
                  </profiles>
              </project>
              """
          )
        );
    }

    @Test
    void changeEveryVersionOfEveryDependencyWithChangePropertyVersionName() {
        rewriteRun(
          spec -> spec.recipe(new ChangeDependencyVersionValue(
            "jakarta.activation",
            "jakarta.activation-api",
            "2.1.0",
            null,
            true,
            null,
            null
          )),
          pomXml(
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <properties>
                          <javax.activation.version>1.2.0</javax.activation.version>
                  </properties>
                  <profiles>
                    <profile>
                      <id>test</id>
                      <dependencies>
                          <dependency>
                              <groupId>jakarta.activation</groupId>
                              <artifactId>jakarta.activation-api</artifactId>
                              <version>1.2.0</version>
                          </dependency>
                      </dependencies>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>jakarta.activation</groupId>
                                  <artifactId>jakarta.activation-api</artifactId>
                                  <version>${javax.activation.version}</version>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                      <build>
                        <plugins>
                            <plugin>
                                <dependencies>
                                    <dependency>
                                        <groupId>jakarta.activation</groupId>
                                        <artifactId>jakarta.activation-api</artifactId>
                                        <version>1.2.0</version>
                                    </dependency>
                                </dependencies>
                            </plugin>
                        </plugins>
                      </build>
                    </profile>
                  </profiles>
              </project>
              """,
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <properties>
                          <jakarta.activation-api.version>2.1.0</jakarta.activation-api.version>
                  </properties>
                  <profiles>
                    <profile>
                      <id>test</id>
                      <dependencies>
                          <dependency>
                              <groupId>jakarta.activation</groupId>
                              <artifactId>jakarta.activation-api</artifactId>
                              <version>2.1.0</version>
                          </dependency>
                      </dependencies>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>jakarta.activation</groupId>
                                  <artifactId>jakarta.activation-api</artifactId>
                                  <version>${jakarta.activation-api.version}</version>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                      <build>
                        <plugins>
                            <plugin>
                                <dependencies>
                                    <dependency>
                                        <groupId>jakarta.activation</groupId>
                                        <artifactId>jakarta.activation-api</artifactId>
                                        <version>2.1.0</version>
                                    </dependency>
                                </dependencies>
                            </plugin>
                        </plugins>
                      </build>
                    </profile>
                  </profiles>
              </project>
              """
          )
        );
    }

    @Test
    void changeOnlyTheVersionOfProfileManagedDependencyWithChangePropertyVersionName() {
        rewriteRun(
          spec -> spec.recipe(new ChangeDependencyVersionValue(
            "jakarta.activation",
            "jakarta.activation-api",
            "2.1.0",
            null,
            true,
            null,
            "MANAGED_DEPENDENCY"
          )),
          pomXml(
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <properties>
                          <javax.activation.version>1.2.0</javax.activation.version>
                  </properties>
                  <profiles>
                    <profile>
                      <id>test</id>
                      <dependencies>
                          <dependency>
                              <groupId>jakarta.activation</groupId>
                              <artifactId>jakarta.activation-api</artifactId>
                              <version>1.2.0</version>
                          </dependency>
                      </dependencies>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>jakarta.activation</groupId>
                                  <artifactId>jakarta.activation-api</artifactId>
                                  <version>${javax.activation.version}</version>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                      <build>
                        <plugins>
                            <plugin>
                                <dependencies>
                                    <dependency>
                                        <groupId>jakarta.activation</groupId>
                                        <artifactId>jakarta.activation-api</artifactId>
                                        <version>1.2.0</version>
                                    </dependency>
                                </dependencies>
                            </plugin>
                        </plugins>
                      </build>
                    </profile>
                  </profiles>
              </project>
              """,
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <properties>
                          <jakarta.activation-api.version>2.1.0</jakarta.activation-api.version>
                  </properties>
                  <profiles>
                    <profile>
                      <id>test</id>
                      <dependencies>
                          <dependency>
                              <groupId>jakarta.activation</groupId>
                              <artifactId>jakarta.activation-api</artifactId>
                              <version>1.2.0</version>
                          </dependency>
                      </dependencies>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>jakarta.activation</groupId>
                                  <artifactId>jakarta.activation-api</artifactId>
                                  <version>${jakarta.activation-api.version}</version>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                      <build>
                        <plugins>
                            <plugin>
                                <dependencies>
                                    <dependency>
                                        <groupId>jakarta.activation</groupId>
                                        <artifactId>jakarta.activation-api</artifactId>
                                        <version>1.2.0</version>
                                    </dependency>
                                </dependencies>
                            </plugin>
                        </plugins>
                      </build>
                    </profile>
                  </profiles>
              </project>
              """
          )
        );
    }

    @Test
    void changeOnlyTheVersionOfDependencyWithChangePropertyVersionName() {
        rewriteRun(
          spec -> spec.recipe(new ChangeDependencyVersionValue(
            "jakarta.activation",
            "jakarta.activation-api",
            "2.1.0",
            null,
            true,
            null,
            "DEPENDENCY"
          )),
          pomXml(
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <properties>
                          <javax.activation.version>1.2.0</javax.activation.version>
                  </properties>
                  <profiles>
                    <profile>
                      <id>test</id>
                      <dependencies>
                          <dependency>
                              <groupId>jakarta.activation</groupId>
                              <artifactId>jakarta.activation-api</artifactId>
                              <version>${javax.activation.version}</version>
                          </dependency>
                      </dependencies>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>jakarta.activation</groupId>
                                  <artifactId>jakarta.activation-api</artifactId>
                                  <version>1.2.0</version>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                      <build>
                        <plugins>
                            <plugin>
                                <dependencies>
                                    <dependency>
                                        <groupId>jakarta.activation</groupId>
                                        <artifactId>jakarta.activation-api</artifactId>
                                        <version>1.2.0</version>
                                    </dependency>
                                </dependencies>
                            </plugin>
                        </plugins>
                      </build>
                    </profile>
                  </profiles>
              </project>
              """,
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <properties>
                          <jakarta.activation-api.version>2.1.0</jakarta.activation-api.version>
                  </properties>
                  <profiles>
                    <profile>
                      <id>test</id>
                      <dependencies>
                          <dependency>
                              <groupId>jakarta.activation</groupId>
                              <artifactId>jakarta.activation-api</artifactId>
                              <version>${jakarta.activation-api.version}</version>
                          </dependency>
                      </dependencies>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>jakarta.activation</groupId>
                                  <artifactId>jakarta.activation-api</artifactId>
                                  <version>1.2.0</version>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                      <build>
                        <plugins>
                            <plugin>
                                <dependencies>
                                    <dependency>
                                        <groupId>jakarta.activation</groupId>
                                        <artifactId>jakarta.activation-api</artifactId>
                                        <version>1.2.0</version>
                                    </dependency>
                                </dependencies>
                            </plugin>
                        </plugins>
                      </build>
                    </profile>
                  </profiles>
              </project>
              """
          )
        );
    }

    @Test
    void changeOnlyTheVersionOfPluginDependencyWithChangePropertyVersionName() {
        rewriteRun(
          spec -> spec.recipe(new ChangeDependencyVersionValue(
            "jakarta.activation",
            "jakarta.activation-api",
            "2.1.0",
            null,
            true,
            null,
            "PLUGIN_DEPENDENCY"
          )),
          pomXml(
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <properties>
                          <javax.activation.version>1.2.0</javax.activation.version>
                  </properties>
                  <profiles>
                    <profile>
                      <id>test</id>
                      <dependencies>
                          <dependency>
                              <groupId>jakarta.activation</groupId>
                              <artifactId>jakarta.activation-api</artifactId>
                              <version>1.2.0</version>
                          </dependency>
                      </dependencies>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>jakarta.activation</groupId>
                                  <artifactId>jakarta.activation-api</artifactId>
                                  <version>1.2.0</version>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                      <build>
                        <plugins>
                            <plugin>
                                <dependencies>
                                    <dependency>
                                        <groupId>jakarta.activation</groupId>
                                        <artifactId>jakarta.activation-api</artifactId>
                                        <version>${javax.activation.version}</version>
                                    </dependency>
                                </dependencies>
                            </plugin>
                        </plugins>
                      </build>
                    </profile>
                  </profiles>
              </project>
              """,
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <properties>
                          <jakarta.activation-api.version>2.1.0</jakarta.activation-api.version>
                  </properties>
                  <profiles>
                    <profile>
                      <id>test</id>
                      <dependencies>
                          <dependency>
                              <groupId>jakarta.activation</groupId>
                              <artifactId>jakarta.activation-api</artifactId>
                              <version>1.2.0</version>
                          </dependency>
                      </dependencies>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>jakarta.activation</groupId>
                                  <artifactId>jakarta.activation-api</artifactId>
                                  <version>1.2.0</version>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                      <build>
                        <plugins>
                            <plugin>
                                <dependencies>
                                    <dependency>
                                        <groupId>jakarta.activation</groupId>
                                        <artifactId>jakarta.activation-api</artifactId>
                                        <version>${jakarta.activation-api.version}</version>
                                    </dependency>
                                </dependencies>
                            </plugin>
                        </plugins>
                      </build>
                    </profile>
                  </profiles>
              </project>
              """
          )
        );
    }

    @Test
    void changeOnlyTheVersionOfProfileManagedDependencyWithNewPropertyVersionName() {
        rewriteRun(
          spec -> spec.recipe(new ChangeDependencyVersionValue(
            "jakarta.activation",
            "jakarta.activation-api",
            "2.1.0",
            null,
            false,
            "test",
            "MANAGED_DEPENDENCY"
          )),
          pomXml(
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <properties>
                          <javax.activation.version>1.2.0</javax.activation.version>
                  </properties>
                  <profiles>
                    <profile>
                      <id>test</id>
                      <dependencies>
                          <dependency>
                              <groupId>jakarta.activation</groupId>
                              <artifactId>jakarta.activation-api</artifactId>
                              <version>1.2.0</version>
                          </dependency>
                      </dependencies>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>jakarta.activation</groupId>
                                  <artifactId>jakarta.activation-api</artifactId>
                                  <version>${javax.activation.version}</version>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                      <build>
                        <plugins>
                            <plugin>
                                <dependencies>
                                    <dependency>
                                        <groupId>jakarta.activation</groupId>
                                        <artifactId>jakarta.activation-api</artifactId>
                                        <version>1.2.0</version>
                                    </dependency>
                                </dependencies>
                            </plugin>
                        </plugins>
                      </build>
                    </profile>
                  </profiles>
              </project>
              """,
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <properties>
                          <test>2.1.0</test>
                  </properties>
                  <profiles>
                    <profile>
                      <id>test</id>
                      <dependencies>
                          <dependency>
                              <groupId>jakarta.activation</groupId>
                              <artifactId>jakarta.activation-api</artifactId>
                              <version>1.2.0</version>
                          </dependency>
                      </dependencies>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>jakarta.activation</groupId>
                                  <artifactId>jakarta.activation-api</artifactId>
                                  <version>${test}</version>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                      <build>
                        <plugins>
                            <plugin>
                                <dependencies>
                                    <dependency>
                                        <groupId>jakarta.activation</groupId>
                                        <artifactId>jakarta.activation-api</artifactId>
                                        <version>1.2.0</version>
                                    </dependency>
                                </dependencies>
                            </plugin>
                        </plugins>
                      </build>
                    </profile>
                  </profiles>
              </project>
              """
          )
        );
    }

    @Test
    void alreadyLatestVersionButWithPropertyChange() {
        rewriteRun(
          spec -> spec.recipe(new ChangeDependencyVersionValue(
            "jakarta.activation",
            "jakarta.activation-api",
            "2.1.0",
            null,
            true,
            "test",
            null
          )),
          pomXml(
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <properties>
                          <jakarta.activation-api.version>2.1.0</jakarta.activation-api.version>
                  </properties>
                  <profiles>
                    <profile>
                      <id>test</id>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>jakarta.activation</groupId>
                                  <artifactId>jakarta.activation-api</artifactId>
                                  <version>${jakarta.activation-api.version}</version>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                    </profile>
                  </profiles>
              </project>
              """,
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <properties>
                          <test>2.1.0</test>
                  </properties>
                  <profiles>
                    <profile>
                      <id>test</id>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>jakarta.activation</groupId>
                                  <artifactId>jakarta.activation-api</artifactId>
                                  <version>${test}</version>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                    </profile>
                  </profiles>
              </project>
              """
          )
        );
    }
}