/*
 * Copyright 2025 the original author or authors.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openrewrite.maven;

import org.junit.jupiter.api.Test;
import org.openrewrite.DocumentExample;
import org.openrewrite.test.RecipeSpec;
import org.openrewrite.test.RewriteTest;

import static org.openrewrite.maven.Assertions.pomXml;

class RemoveDuplicatePluginDeclarationsTest implements RewriteTest {

    @Override
    public void defaults(RecipeSpec spec) {
        spec.recipe(new RemoveDuplicatePluginDeclarations());
    }

    @DocumentExample
    @Test
    void removeDuplicatePlugin() {
        rewriteRun(
          pomXml(
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <groupId>org.apache.maven.plugins</groupId>
                              <artifactId>maven-compiler-plugin</artifactId>
                              <version>3.8.1</version>
                          </plugin>
                          <plugin>
                              <groupId>org.apache.maven.plugins</groupId>
                              <artifactId>maven-surefire-plugin</artifactId>
                              <version>2.22.2</version>
                          </plugin>
                          <plugin>
                              <groupId>org.apache.maven.plugins</groupId>
                              <artifactId>maven-compiler-plugin</artifactId>
                              <version>3.11.0</version>
                          </plugin>
                      </plugins>
                  </build>
              </project>
              """,
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <groupId>org.apache.maven.plugins</groupId>
                              <artifactId>maven-compiler-plugin</artifactId>
                              <version>3.11.0</version>
                          </plugin>
                          <plugin>
                              <groupId>org.apache.maven.plugins</groupId>
                              <artifactId>maven-surefire-plugin</artifactId>
                              <version>2.22.2</version>
                          </plugin>
                      </plugins>
                  </build>
              </project>
              """
          )
        );
    }

    @Test
    void removeDuplicatePluginWithImplicitGroupId() {
        rewriteRun(
          pomXml(
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <artifactId>maven-compiler-plugin</artifactId>
                              <version>3.8.1</version>
                          </plugin>
                          <plugin>
                              <groupId>org.apache.maven.plugins</groupId>
                              <artifactId>maven-compiler-plugin</artifactId>
                              <version>3.11.0</version>
                          </plugin>
                      </plugins>
                  </build>
              </project>
              """,
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <artifactId>maven-compiler-plugin</artifactId>
                              <version>3.11.0</version>
                          </plugin>
                      </plugins>
                  </build>
              </project>
              """
          )
        );
    }

    @Test
    void removeDuplicateInPluginManagement() {
        rewriteRun(
          pomXml(
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <pluginManagement>
                          <plugins>
                              <plugin>
                                  <groupId>org.apache.maven.plugins</groupId>
                                  <artifactId>maven-compiler-plugin</artifactId>
                                  <version>3.8.1</version>
                              </plugin>
                              <plugin>
                                  <groupId>org.apache.maven.plugins</groupId>
                                  <artifactId>maven-compiler-plugin</artifactId>
                                  <version>3.11.0</version>
                              </plugin>
                          </plugins>
                      </pluginManagement>
                  </build>
              </project>
              """,
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <pluginManagement>
                          <plugins>
                              <plugin>
                                  <groupId>org.apache.maven.plugins</groupId>
                                  <artifactId>maven-compiler-plugin</artifactId>
                                  <version>3.11.0</version>
                              </plugin>
                          </plugins>
                      </pluginManagement>
                  </build>
              </project>
              """
          )
        );
    }

    @Test
    void removeMultipleDuplicates() {
        rewriteRun(
          pomXml(
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <groupId>org.apache.maven.plugins</groupId>
                              <artifactId>maven-compiler-plugin</artifactId>
                              <version>3.8.1</version>
                          </plugin>
                          <plugin>
                              <groupId>org.apache.maven.plugins</groupId>
                              <artifactId>maven-compiler-plugin</artifactId>
                              <version>3.9.0</version>
                          </plugin>
                          <plugin>
                              <groupId>org.apache.maven.plugins</groupId>
                              <artifactId>maven-compiler-plugin</artifactId>
                              <version>3.11.0</version>
                          </plugin>
                      </plugins>
                  </build>
              </project>
              """,
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <groupId>org.apache.maven.plugins</groupId>
                              <artifactId>maven-compiler-plugin</artifactId>
                              <version>3.11.0</version>
                          </plugin>
                      </plugins>
                  </build>
              </project>
              """
          )
        );
    }

    @Test
    void noChangeWhenNoDuplicates() {
        rewriteRun(
          pomXml(
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <groupId>org.apache.maven.plugins</groupId>
                              <artifactId>maven-compiler-plugin</artifactId>
                              <version>3.8.1</version>
                          </plugin>
                          <plugin>
                              <groupId>org.apache.maven.plugins</groupId>
                              <artifactId>maven-surefire-plugin</artifactId>
                              <version>2.22.2</version>
                          </plugin>
                      </plugins>
                  </build>
              </project>
              """
          )
        );
    }

    @Test
    void keepDifferentGroupIdsSameArtifactId() {
        rewriteRun(
          pomXml(
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <groupId>org.apache.maven.plugins</groupId>
                              <artifactId>maven-compiler-plugin</artifactId>
                              <version>3.8.1</version>
                          </plugin>
                          <plugin>
                              <groupId>com.example</groupId>
                              <artifactId>maven-compiler-plugin</artifactId>
                              <version>1.0.0</version>
                          </plugin>
                      </plugins>
                  </build>
              </project>
              """
          )
        );
    }

    @Test
    void removeDuplicateInProfile() {
        rewriteRun(
          pomXml(
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <profiles>
                      <profile>
                          <id>release</id>
                          <build>
                              <plugins>
                                  <plugin>
                                      <artifactId>maven-gpg-plugin</artifactId>
                                      <version>3.2.4</version>
                                  </plugin>
                                  <plugin>
                                      <artifactId>maven-gpg-plugin</artifactId>
                                      <version>3.2.7</version>
                                  </plugin>
                              </plugins>
                          </build>
                      </profile>
                  </profiles>
              </project>
              """,
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <profiles>
                      <profile>
                          <id>release</id>
                          <build>
                              <plugins>
                                  <plugin>
                                      <artifactId>maven-gpg-plugin</artifactId>
                                      <version>3.2.7</version>
                                  </plugin>
                              </plugins>
                          </build>
                      </profile>
                  </profiles>
              </project>
              """
          )
        );
    }

    @Test
    void removeDuplicateInProfilePluginManagement() {
        rewriteRun(
          pomXml(
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <profiles>
                      <profile>
                          <id>release</id>
                          <build>
                              <pluginManagement>
                                  <plugins>
                                      <plugin>
                                          <artifactId>maven-gpg-plugin</artifactId>
                                          <version>3.2.4</version>
                                      </plugin>
                                      <plugin>
                                          <artifactId>maven-gpg-plugin</artifactId>
                                          <version>3.2.7</version>
                                      </plugin>
                                  </plugins>
                              </pluginManagement>
                          </build>
                      </profile>
                  </profiles>
              </project>
              """,
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <profiles>
                      <profile>
                          <id>release</id>
                          <build>
                              <pluginManagement>
                                  <plugins>
                                      <plugin>
                                          <artifactId>maven-gpg-plugin</artifactId>
                                          <version>3.2.7</version>
                                      </plugin>
                                  </plugins>
                              </pluginManagement>
                          </build>
                      </profile>
                  </profiles>
              </project>
              """
          )
        );
    }

    @Test
    void removeDuplicateInReporting() {
        rewriteRun(
          pomXml(
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <reporting>
                      <plugins>
                          <plugin>
                              <artifactId>maven-javadoc-plugin</artifactId>
                              <version>3.6.3</version>
                          </plugin>
                          <plugin>
                              <artifactId>maven-javadoc-plugin</artifactId>
                              <version>3.11.2</version>
                          </plugin>
                      </plugins>
                  </reporting>
              </project>
              """,
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <reporting>
                      <plugins>
                          <plugin>
                              <artifactId>maven-javadoc-plugin</artifactId>
                              <version>3.6.3</version>
                          </plugin>
                      </plugins>
                  </reporting>
              </project>
              """
          )
        );
    }

    @Test
    void keepRepeatedPluginsInsideConfiguration() {
        rewriteRun(
          pomXml(
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <artifactId>maven-antrun-plugin</artifactId>
                              <version>3.1.0</version>
                              <configuration>
                                  <plugins>
                                      <plugin>
                                          <artifactId>maven-compiler-plugin</artifactId>
                                      </plugin>
                                      <plugin>
                                          <artifactId>maven-compiler-plugin</artifactId>
                                      </plugin>
                                  </plugins>
                              </configuration>
                          </plugin>
                      </plugins>
                  </build>
              </project>
              """
          )
        );
    }

    @Test
    void mergeExecutionsAndDependenciesOfDuplicateBuildPlugins() {
        rewriteRun(
          pomXml(
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <artifactId>maven-compiler-plugin</artifactId>
                              <version>3.11.0</version>
                              <dependencies>
                                  <dependency>
                                      <groupId>group</groupId>
                                      <artifactId>first</artifactId>
                                      <version>1</version>
                                  </dependency>
                              </dependencies>
                              <executions>
                                  <execution>
                                      <id>first</id>
                                      <goals>
                                          <goal>compile</goal>
                                      </goals>
                                  </execution>
                              </executions>
                          </plugin>
                          <plugin>
                              <artifactId>maven-surefire-plugin</artifactId>
                              <version>3.5.2</version>
                          </plugin>
                          <plugin>
                              <artifactId>maven-compiler-plugin</artifactId>
                              <dependencies>
                                  <dependency>
                                      <groupId>group</groupId>
                                      <artifactId>second</artifactId>
                                      <version>1</version>
                                  </dependency>
                              </dependencies>
                              <executions>
                                  <execution>
                                      <id>second</id>
                                      <goals>
                                          <goal>compile</goal>
                                      </goals>
                                  </execution>
                              </executions>
                          </plugin>
                      </plugins>
                  </build>
              </project>
              """,
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <artifactId>maven-compiler-plugin</artifactId>
                              <version>3.11.0</version>
                              <dependencies>
                                  <dependency>
                                      <groupId>group</groupId>
                                      <artifactId>second</artifactId>
                                      <version>1</version>
                                  </dependency>
                                  <dependency>
                                      <groupId>group</groupId>
                                      <artifactId>first</artifactId>
                                      <version>1</version>
                                  </dependency>
                              </dependencies>
                              <executions>
                                  <execution>
                                      <id>first</id>
                                      <goals>
                                          <goal>compile</goal>
                                      </goals>
                                  </execution>
                                  <execution>
                                      <id>second</id>
                                      <goals>
                                          <goal>compile</goal>
                                      </goals>
                                  </execution>
                              </executions>
                          </plugin>
                          <plugin>
                              <artifactId>maven-surefire-plugin</artifactId>
                              <version>3.5.2</version>
                          </plugin>
                      </plugins>
                  </build>
              </project>
              """
          )
        );
    }

    @Test
    void mergeExecutionsWithTheSameId() {
        rewriteRun(
          pomXml(
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <artifactId>maven-antrun-plugin</artifactId>
                              <version>3.1.0</version>
                              <executions>
                                  <execution>
                                      <id>generate</id>
                                      <phase>generate-sources</phase>
                                      <goals>
                                          <goal>run</goal>
                                      </goals>
                                      <configuration>
                                          <target>
                                              <echo message="first"/>
                                          </target>
                                          <skip>false</skip>
                                      </configuration>
                                  </execution>
                              </executions>
                          </plugin>
                          <plugin>
                              <artifactId>maven-antrun-plugin</artifactId>
                              <executions>
                                  <execution>
                                      <id>generate</id>
                                      <phase>process-sources</phase>
                                      <configuration>
                                          <target>
                                              <echo message="second"/>
                                          </target>
                                      </configuration>
                                  </execution>
                              </executions>
                          </plugin>
                      </plugins>
                  </build>
              </project>
              """,
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <artifactId>maven-antrun-plugin</artifactId>
                              <version>3.1.0</version>
                              <executions>
                                  <execution>
                                      <id>generate</id>
                                      <phase>process-sources</phase>
                                      <goals>
                                          <goal>run</goal>
                                      </goals>
                                      <configuration>
                                          <target>
                                              <echo message="second"/>
                                          </target>
                                          <skip>false</skip>
                                      </configuration>
                                  </execution>
                              </executions>
                          </plugin>
                      </plugins>
                  </build>
              </project>
              """
          )
        );
    }

    @Test
    void mergeConfigurationLikeMaven() {
        rewriteRun(
          pomXml(
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <artifactId>maven-compiler-plugin</artifactId>
                              <version>3.13.0</version>
                              <configuration>
                                  <release>17</release>
                                  <showWarnings>true</showWarnings>
                                  <compilerArgs>
                                      <arg>-Xlint:all</arg>
                                  </compilerArgs>
                              </configuration>
                          </plugin>
                          <plugin>
                              <artifactId>maven-compiler-plugin</artifactId>
                              <configuration>
                                  <release>21</release>
                                  <compilerArgs combine.children="append">
                                      <arg>-parameters</arg>
                                  </compilerArgs>
                              </configuration>
                          </plugin>
                      </plugins>
                  </build>
              </project>
              """,
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <artifactId>maven-compiler-plugin</artifactId>
                              <version>3.13.0</version>
                              <configuration>
                                  <release>21</release>
                                  <showWarnings>true</showWarnings>
                                  <compilerArgs combine.children="append">
                                      <arg>-Xlint:all</arg>
                                      <arg>-parameters</arg>
                                  </compilerArgs>
                              </configuration>
                          </plugin>
                      </plugins>
                  </build>
              </project>
              """
          )
        );
    }

    @Test
    void laterConfigurationOverridesWithCombineSelf() {
        rewriteRun(
          pomXml(
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <artifactId>maven-surefire-plugin</artifactId>
                              <version>3.5.2</version>
                              <configuration>
                                  <excludes>
                                      <exclude>**/*IT.java</exclude>
                                  </excludes>
                              </configuration>
                          </plugin>
                          <plugin>
                              <artifactId>maven-surefire-plugin</artifactId>
                              <configuration combine.self="override">
                                  <skipTests>true</skipTests>
                              </configuration>
                          </plugin>
                      </plugins>
                  </build>
              </project>
              """,
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <artifactId>maven-surefire-plugin</artifactId>
                              <version>3.5.2</version>
                              <configuration combine.self="override">
                                  <skipTests>true</skipTests>
                              </configuration>
                          </plugin>
                      </plugins>
                  </build>
              </project>
              """
          )
        );
    }

    @Test
    void lastPluginManagementDeclarationWinsWithoutMerging() {
        rewriteRun(
          pomXml(
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <pluginManagement>
                          <plugins>
                              <plugin>
                                  <artifactId>maven-surefire-plugin</artifactId>
                                  <version>3.2.5</version>
                                  <configuration>
                                      <trimStackTrace>false</trimStackTrace>
                                  </configuration>
                              </plugin>
                              <plugin>
                                  <artifactId>maven-jar-plugin</artifactId>
                                  <version>3.4.2</version>
                              </plugin>
                              <plugin>
                                  <artifactId>maven-surefire-plugin</artifactId>
                                  <version>3.5.2</version>
                              </plugin>
                          </plugins>
                      </pluginManagement>
                  </build>
              </project>
              """,
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <pluginManagement>
                          <plugins>
                              <plugin>
                                  <artifactId>maven-surefire-plugin</artifactId>
                                  <version>3.5.2</version>
                              </plugin>
                              <plugin>
                                  <artifactId>maven-jar-plugin</artifactId>
                                  <version>3.4.2</version>
                              </plugin>
                          </plugins>
                      </pluginManagement>
                  </build>
              </project>
              """
          )
        );
    }

    @Test
    void coordinatesAreComparedTrimmed() {
        rewriteRun(
          pomXml(
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <artifactId>maven-jar-plugin</artifactId>
                              <version>3.4.2</version>
                          </plugin>
                          <plugin>
                              <groupId> org.apache.maven.plugins </groupId>
                              <artifactId>
                                  maven-jar-plugin
                              </artifactId>
                          </plugin>
                      </plugins>
                  </build>
              </project>
              """,
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <artifactId>
                                  maven-jar-plugin
                              </artifactId>
                              <version>3.4.2</version>
                          </plugin>
                      </plugins>
                  </build>
              </project>
              """
          )
        );
    }

    @Test
    void keepElementOrderAndCommentsOfMergedDeclarations() {
        rewriteRun(
          pomXml(
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <artifactId>maven-jar-plugin</artifactId>
                              <version>3.4.2</version>
                          </plugin>

                          <!-- integration tests -->
                          <plugin>
                              <artifactId>maven-failsafe-plugin</artifactId>
                              <version>3.5.2</version>
                              <configuration>
                                  <skipITs>false</skipITs>
                              </configuration>
                              <executions>
                                  <!-- run the tests -->
                                  <execution>
                                      <goals>
                                          <goal>integration-test</goal>
                                      </goals>
                                  </execution>
                              </executions>
                          </plugin>

                          <!-- verify after integration tests -->
                          <plugin>
                              <artifactId>maven-failsafe-plugin</artifactId>
                              <executions>

                                  <!-- check the results -->
                                  <execution>
                                      <goals>
                                          <goal>verify</goal>
                                      </goals>
                                  </execution>
                              </executions>
                          </plugin>
                      </plugins>
                  </build>
              </project>
              """,
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <artifactId>maven-jar-plugin</artifactId>
                              <version>3.4.2</version>
                          </plugin>

                          <!-- integration tests -->
                          <!-- verify after integration tests -->
                          <plugin>
                              <artifactId>maven-failsafe-plugin</artifactId>
                              <version>3.5.2</version>
                              <configuration>
                                  <skipITs>false</skipITs>
                              </configuration>
                              <executions>
                                  <!-- run the tests -->
                                  <!-- check the results -->
                                  <execution>
                                      <goals>
                                          <goal>verify</goal>
                                          <goal>integration-test</goal>
                                      </goals>
                                  </execution>
                              </executions>
                          </plugin>
                      </plugins>
                  </build>
              </project>
              """
          )
        );
    }

    @Test
    void reindentEarlierDeclarationToMatchTheLaterOne() {
        rewriteRun(
          pomXml(
            """
              <project>
              \t<groupId>com.example</groupId>
              \t<artifactId>my-app</artifactId>
              \t<version>1.0.0</version>
              \t<build>
              \t\t<plugins>
                          <plugin>
                              <artifactId>maven-deploy-plugin</artifactId>
                              <version>2.8.1</version>
                              <configuration>
                                  <skip>true</skip>
                              </configuration>
                          </plugin>
              \t\t\t<plugin>
              \t\t\t\t<artifactId>maven-deploy-plugin</artifactId>
              \t\t\t\t<executions>
              \t\t\t\t\t<execution>
              \t\t\t\t\t\t<id>default-deploy</id>
              \t\t\t\t\t\t<phase>none</phase>
              \t\t\t\t\t</execution>
              \t\t\t\t</executions>
              \t\t\t</plugin>
              \t\t</plugins>
              \t</build>
              </project>
              """,
            """
              <project>
              \t<groupId>com.example</groupId>
              \t<artifactId>my-app</artifactId>
              \t<version>1.0.0</version>
              \t<build>
              \t\t<plugins>
              \t\t\t<plugin>
              \t\t\t\t<artifactId>maven-deploy-plugin</artifactId>
              \t\t\t\t<version>2.8.1</version>
              \t\t\t\t<configuration>
              \t\t\t\t\t<skip>true</skip>
              \t\t\t\t</configuration>
              \t\t\t\t<executions>
              \t\t\t\t\t<execution>
              \t\t\t\t\t\t<id>default-deploy</id>
              \t\t\t\t\t\t<phase>none</phase>
              \t\t\t\t\t</execution>
              \t\t\t\t</executions>
              \t\t\t</plugin>
              \t\t</plugins>
              \t</build>
              </project>
              """
          )
        );
    }

    @Test
    void lastProfilePluginWinsWhenTheMainBuildDoesNotDeclareIt() {
        rewriteRun(
          pomXml(
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <profiles>
                      <profile>
                          <id>dist</id>
                          <build>
                              <plugins>
                                  <plugin>
                                      <artifactId>maven-assembly-plugin</artifactId>
                                      <version>2.4</version>
                                      <configuration>
                                          <descriptors>
                                              <descriptor>assembly/bin.xml</descriptor>
                                          </descriptors>
                                      </configuration>
                                  </plugin>
                                  <plugin>
                                      <artifactId>maven-assembly-plugin</artifactId>
                                      <configuration>
                                          <descriptorRefs>
                                              <descriptorRef>jar-with-dependencies</descriptorRef>
                                          </descriptorRefs>
                                      </configuration>
                                  </plugin>
                              </plugins>
                          </build>
                      </profile>
                  </profiles>
              </project>
              """,
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <profiles>
                      <profile>
                          <id>dist</id>
                          <build>
                              <plugins>
                                  <plugin>
                                      <artifactId>maven-assembly-plugin</artifactId>
                                      <configuration>
                                          <descriptorRefs>
                                              <descriptorRef>jar-with-dependencies</descriptorRef>
                                          </descriptorRefs>
                                      </configuration>
                                  </plugin>
                              </plugins>
                          </build>
                      </profile>
                  </profiles>
              </project>
              """
          )
        );
    }

    @Test
    void mergeProfilePluginsWhenTheMainBuildDeclaresThePlugin() {
        rewriteRun(
          pomXml(
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <artifactId>maven-surefire-plugin</artifactId>
                              <version>3.5.2</version>
                          </plugin>
                      </plugins>
                  </build>
                  <profiles>
                      <profile>
                          <id>ci</id>
                          <build>
                              <plugins>
                                  <plugin>
                                      <artifactId>maven-surefire-plugin</artifactId>
                                      <configuration>
                                          <forkCount>2</forkCount>
                                      </configuration>
                                  </plugin>
                                  <plugin>
                                      <artifactId>maven-surefire-plugin</artifactId>
                                      <configuration>
                                          <rerunFailingTestsCount>1</rerunFailingTestsCount>
                                      </configuration>
                                  </plugin>
                              </plugins>
                          </build>
                      </profile>
                  </profiles>
              </project>
              """,
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <artifactId>maven-surefire-plugin</artifactId>
                              <version>3.5.2</version>
                          </plugin>
                      </plugins>
                  </build>
                  <profiles>
                      <profile>
                          <id>ci</id>
                          <build>
                              <plugins>
                                  <plugin>
                                      <artifactId>maven-surefire-plugin</artifactId>
                                      <configuration>
                                          <rerunFailingTestsCount>1</rerunFailingTestsCount>
                                          <forkCount>2</forkCount>
                                      </configuration>
                                  </plugin>
                              </plugins>
                          </build>
                      </profile>
                  </profiles>
              </project>
              """
          )
        );
    }

    @Test
    void mergePluginManagementWhenTheParentManagesThePlugin() {
        rewriteRun(
          pomXml(
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>parent</artifactId>
                  <version>1.0.0</version>
                  <packaging>pom</packaging>
                  <modules>
                      <module>child</module>
                  </modules>
                  <build>
                      <pluginManagement>
                          <plugins>
                              <plugin>
                                  <artifactId>maven-surefire-plugin</artifactId>
                                  <version>3.5.2</version>
                              </plugin>
                          </plugins>
                      </pluginManagement>
                  </build>
              </project>
              """
          ),
          pomXml(
            """
              <project>
                  <parent>
                      <groupId>com.example</groupId>
                      <artifactId>parent</artifactId>
                      <version>1.0.0</version>
                  </parent>
                  <artifactId>child</artifactId>
                  <build>
                      <pluginManagement>
                          <plugins>
                              <plugin>
                                  <artifactId>maven-surefire-plugin</artifactId>
                                  <configuration>
                                      <skip>true</skip>
                                  </configuration>
                              </plugin>
                              <plugin>
                                  <artifactId>maven-surefire-plugin</artifactId>
                                  <version>3.5.3</version>
                              </plugin>
                          </plugins>
                      </pluginManagement>
                  </build>
              </project>
              """,
            """
              <project>
                  <parent>
                      <groupId>com.example</groupId>
                      <artifactId>parent</artifactId>
                      <version>1.0.0</version>
                  </parent>
                  <artifactId>child</artifactId>
                  <build>
                      <pluginManagement>
                          <plugins>
                              <plugin>
                                  <artifactId>maven-surefire-plugin</artifactId>
                                  <version>3.5.3</version>
                                  <configuration>
                                      <skip>true</skip>
                                  </configuration>
                              </plugin>
                          </plugins>
                      </pluginManagement>
                  </build>
              </project>
              """,
            spec -> spec.path("child/pom.xml")
          )
        );
    }

    @Test
    void mergePluginManagementOfPluginsTheSuperPomManages() {
        rewriteRun(
          pomXml(
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <pluginManagement>
                          <plugins>
                              <plugin>
                                  <artifactId>maven-dependency-plugin</artifactId>
                                  <version>3.8.1</version>
                              </plugin>
                              <plugin>
                                  <artifactId>maven-dependency-plugin</artifactId>
                                  <configuration>
                                      <silent>true</silent>
                                  </configuration>
                              </plugin>
                          </plugins>
                      </pluginManagement>
                  </build>
              </project>
              """,
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <pluginManagement>
                          <plugins>
                              <plugin>
                                  <artifactId>maven-dependency-plugin</artifactId>
                                  <version>3.8.1</version>
                                  <configuration>
                                      <silent>true</silent>
                                  </configuration>
                              </plugin>
                          </plugins>
                      </pluginManagement>
                  </build>
              </project>
              """
          )
        );
    }

    @Test
    void keepCommentsInsideMergedConfiguration() {
        rewriteRun(
          pomXml(
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <groupId>org.apache.maven.plugins</groupId>
                              <artifactId>maven-surefire-plugin</artifactId>
                              <configuration>
                                  <redirectTestOutputToFile>true</redirectTestOutputToFile>
                                  <includes>
                                      <!-- Make sure both the Test/Tests.java files are included -->
                                      <include>**/*Test*.java</include>
                                  </includes>
                              </configuration>
                          </plugin>
                          <plugin>
                              <artifactId>maven-surefire-plugin</artifactId>
                              <version>2.12</version>
                              <configuration>
                                  <includes>
                                      <include>**/*Test*.java</include>
                                  </includes>
                              </configuration>
                          </plugin>
                      </plugins>
                  </build>
              </project>
              """,
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <groupId>org.apache.maven.plugins</groupId>
                              <artifactId>maven-surefire-plugin</artifactId>
                              <version>2.12</version>
                              <configuration>
                                  <redirectTestOutputToFile>true</redirectTestOutputToFile>
                                  <includes>
                                      <!-- Make sure both the Test/Tests.java files are included -->
                                      <include>**/*Test*.java</include>
                                  </includes>
                              </configuration>
                          </plugin>
                      </plugins>
                  </build>
              </project>
              """
          )
        );
    }

    @Test
    void writeMergedPluginInTheIndentationOfItsSiblings() {
        rewriteRun(
          pomXml(
            """
              <project>
              \t<groupId>com.example</groupId>
              \t<artifactId>my-app</artifactId>
              \t<version>1.0.0</version>
              \t<build>
              \t\t<plugins>
              \t\t\t<plugin>
              \t\t\t\t<artifactId>maven-javadoc-plugin</artifactId>
              \t\t\t\t<configuration>
              \t\t\t\t\t<doclint>none</doclint>
              \t\t\t\t</configuration>
              \t\t\t</plugin>
              \t\t\t<plugin>
              \t\t\t\t<artifactId>maven-jar-plugin</artifactId>
              \t\t\t</plugin>
                          <plugin>
                              <artifactId>maven-javadoc-plugin</artifactId>
                              <version>3.2.0</version>
                          </plugin>
              \t\t</plugins>
              \t</build>
              </project>
              """,
            """
              <project>
              \t<groupId>com.example</groupId>
              \t<artifactId>my-app</artifactId>
              \t<version>1.0.0</version>
              \t<build>
              \t\t<plugins>
              \t\t\t<plugin>
              \t\t\t\t<artifactId>maven-javadoc-plugin</artifactId>
              \t\t\t\t<version>3.2.0</version>
              \t\t\t\t<configuration>
              \t\t\t\t\t<doclint>none</doclint>
              \t\t\t\t</configuration>
              \t\t\t</plugin>
              \t\t\t<plugin>
              \t\t\t\t<artifactId>maven-jar-plugin</artifactId>
              \t\t\t</plugin>
              \t\t</plugins>
              \t</build>
              </project>
              """
          )
        );
    }

    @Test
    void straightenInconsistentIndentationOfMovedContent() {
        rewriteRun(
          pomXml(
            """
              <project>
              \t<groupId>com.example</groupId>
              \t<artifactId>my-app</artifactId>
              \t<version>1.0.0</version>
              \t<build>
              \t\t<plugins>
              \t\t\t<plugin>
              \t\t\t\t<artifactId>maven-javadoc-plugin</artifactId>
              \t\t\t\t<configuration>
              \t\t\t\t\t<aggregate>true</aggregate>
              \t\t\t\t</configuration>
              \t\t\t</plugin>
              \t\t\t<plugin>
              \t\t\t\t<artifactId>maven-jar-plugin</artifactId>
              \t\t\t</plugin>
                            <plugin>
                                <artifactId>maven-javadoc-plugin</artifactId>
                                <version>3.2.0</version>
                                <configuration>
                                        <doclint>none</doclint>
                                </configuration>
                              </plugin>
              \t\t</plugins>
              \t</build>
              </project>
              """,
            """
              <project>
              \t<groupId>com.example</groupId>
              \t<artifactId>my-app</artifactId>
              \t<version>1.0.0</version>
              \t<build>
              \t\t<plugins>
              \t\t\t<plugin>
              \t\t\t\t<artifactId>maven-javadoc-plugin</artifactId>
              \t\t\t\t<version>3.2.0</version>
              \t\t\t\t<configuration>
              \t\t\t\t\t<doclint>none</doclint>
              \t\t\t\t\t<aggregate>true</aggregate>
              \t\t\t\t</configuration>
              \t\t\t</plugin>
              \t\t\t<plugin>
              \t\t\t\t<artifactId>maven-jar-plugin</artifactId>
              \t\t\t</plugin>
              \t\t</plugins>
              \t</build>
              </project>
              """
          )
        );
    }

    @Test
    void dropExecutionsMavenDidNotInheritIntoTheMerge() {
        rewriteRun(
          pomXml(
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <artifactId>maven-antrun-plugin</artifactId>
                              <version>3.1.0</version>
                              <inherited>false</inherited>
                              <executions>
                                  <execution>
                                      <id>from-first</id>
                                      <goals>
                                          <goal>run</goal>
                                      </goals>
                                  </execution>
                              </executions>
                          </plugin>
                          <plugin>
                              <artifactId>maven-antrun-plugin</artifactId>
                              <executions>
                                  <execution>
                                      <id>from-second</id>
                                      <goals>
                                          <goal>run</goal>
                                      </goals>
                                  </execution>
                              </executions>
                          </plugin>
                          <plugin>
                              <artifactId>maven-jar-plugin</artifactId>
                              <executions>
                                  <execution>
                                      <id>not-inherited</id>
                                      <inherited>false</inherited>
                                      <goals>
                                          <goal>jar</goal>
                                      </goals>
                                  </execution>
                                  <execution>
                                      <id>inherited</id>
                                      <goals>
                                          <goal>test-jar</goal>
                                      </goals>
                                  </execution>
                              </executions>
                          </plugin>
                          <plugin>
                              <artifactId>maven-jar-plugin</artifactId>
                              <version>3.4.2</version>
                          </plugin>
                      </plugins>
                  </build>
              </project>
              """,
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <artifactId>maven-antrun-plugin</artifactId>
                              <version>3.1.0</version>
                              <inherited>false</inherited>
                              <executions>
                                  <execution>
                                      <id>from-second</id>
                                      <goals>
                                          <goal>run</goal>
                                      </goals>
                                  </execution>
                              </executions>
                          </plugin>
                          <plugin>
                              <artifactId>maven-jar-plugin</artifactId>
                              <version>3.4.2</version>
                              <executions>
                                  <execution>
                                      <id>inherited</id>
                                      <goals>
                                          <goal>test-jar</goal>
                                      </goals>
                                  </execution>
                              </executions>
                          </plugin>
                      </plugins>
                  </build>
              </project>
              """
          )
        );
    }

    @Test
    void keepNonInheritedExecutionsOfProfileDuplicatesMergedIntoTheMainBuild() {
        rewriteRun(
          pomXml(
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <artifactId>maven-antrun-plugin</artifactId>
                              <version>3.1.0</version>
                          </plugin>
                      </plugins>
                  </build>
                  <profiles>
                      <profile>
                          <id>ci</id>
                          <build>
                              <plugins>
                                  <plugin>
                                      <artifactId>maven-antrun-plugin</artifactId>
                                      <executions>
                                          <execution>
                                              <id>root-only</id>
                                              <inherited>false</inherited>
                                              <goals>
                                                  <goal>run</goal>
                                              </goals>
                                          </execution>
                                      </executions>
                                  </plugin>
                                  <plugin>
                                      <artifactId>maven-antrun-plugin</artifactId>
                                      <executions>
                                          <execution>
                                              <id>everywhere</id>
                                              <goals>
                                                  <goal>run</goal>
                                              </goals>
                                          </execution>
                                      </executions>
                                  </plugin>
                              </plugins>
                          </build>
                      </profile>
                  </profiles>
              </project>
              """,
            """
              <project>
                  <groupId>com.example</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1.0.0</version>
                  <build>
                      <plugins>
                          <plugin>
                              <artifactId>maven-antrun-plugin</artifactId>
                              <version>3.1.0</version>
                          </plugin>
                      </plugins>
                  </build>
                  <profiles>
                      <profile>
                          <id>ci</id>
                          <build>
                              <plugins>
                                  <plugin>
                                      <artifactId>maven-antrun-plugin</artifactId>
                                      <executions>
                                          <execution>
                                              <id>root-only</id>
                                              <inherited>false</inherited>
                                              <goals>
                                                  <goal>run</goal>
                                              </goals>
                                          </execution>
                                          <execution>
                                              <id>everywhere</id>
                                              <goals>
                                                  <goal>run</goal>
                                              </goals>
                                          </execution>
                                      </executions>
                                  </plugin>
                              </plugins>
                          </build>
                      </profile>
                  </profiles>
              </project>
              """
          )
        );
    }
}
