/*
 * Copyright 2025 the original author or authors.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openrewrite.maven;

import org.junit.jupiter.api.Test;
import org.openrewrite.DocumentExample;
import org.openrewrite.test.RewriteTest;

import static org.openrewrite.maven.Assertions.pomXml;

class RemovePluginGoalTest implements RewriteTest {

    @DocumentExample
    @Test
    void removeGoalLeavingOtherGoals() {
        rewriteRun(
          spec -> spec.recipe(new RemovePluginGoal("org.apache.maven.plugins", "maven-surefire-plugin", "verify")),
          pomXml(
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                      <executions>
                        <execution>
                          <id>default</id>
                          <goals>
                            <goal>verify</goal>
                            <goal>test</goal>
                          </goals>
                        </execution>
                      </executions>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """,
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                      <executions>
                        <execution>
                          <id>default</id>
                          <goals>
                            <goal>test</goal>
                          </goals>
                        </execution>
                      </executions>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """
          )
        );
    }

    @Test
    void removeGoalRemovesEmptyExecution() {
        rewriteRun(
          spec -> spec.recipe(new RemovePluginGoal("org.apache.maven.plugins", "maven-surefire-plugin", "verify")),
          pomXml(
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                      <executions>
                        <execution>
                          <id>verify-only</id>
                          <goals>
                            <goal>verify</goal>
                          </goals>
                        </execution>
                        <execution>
                          <id>test-only</id>
                          <goals>
                            <goal>test</goal>
                          </goals>
                        </execution>
                      </executions>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """,
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                      <executions>
                        <execution>
                          <id>test-only</id>
                          <goals>
                            <goal>test</goal>
                          </goals>
                        </execution>
                      </executions>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """
          )
        );
    }

    @Test
    void removeLastGoalRemovesExecutionsElement() {
        rewriteRun(
          spec -> spec.recipe(new RemovePluginGoal("org.apache.maven.plugins", "maven-surefire-plugin", "verify")),
          pomXml(
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                      <executions>
                        <execution>
                          <id>verify-only</id>
                          <goals>
                            <goal>verify</goal>
                          </goals>
                        </execution>
                      </executions>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """,
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """
          )
        );
    }

    @Test
    // Rare in practice, but exercises the snapshot-iteration invariant:
    // the loop must handle mutations across multiple executions without stale references.
    void removeGoalFromMultipleExecutions() {
        rewriteRun(
          spec -> spec.recipe(new RemovePluginGoal("org.apache.maven.plugins", "maven-surefire-plugin", "verify")),
          pomXml(
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                      <executions>
                        <execution>
                          <id>verify-and-test</id>
                          <goals>
                            <goal>verify</goal>
                            <goal>test</goal>
                          </goals>
                        </execution>
                        <execution>
                          <id>verify-only</id>
                          <goals>
                            <goal>verify</goal>
                          </goals>
                        </execution>
                      </executions>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """,
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                      <executions>
                        <execution>
                          <id>verify-and-test</id>
                          <goals>
                            <goal>test</goal>
                          </goals>
                        </execution>
                      </executions>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """
          )
        );
    }

    @Test
    void noChangeWhenGoalNotPresent() {
        rewriteRun(
          spec -> spec.recipe(new RemovePluginGoal("org.apache.maven.plugins", "maven-surefire-plugin", "verify")),
          pomXml(
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                      <executions>
                        <execution>
                          <id>default</id>
                          <goals>
                            <goal>test</goal>
                          </goals>
                        </execution>
                      </executions>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """
          )
        );
    }

    @Test
    void noChangeWhenPluginNotPresent() {
        rewriteRun(
          spec -> spec.recipe(new RemovePluginGoal("org.apache.maven.plugins", "maven-surefire-plugin", "verify")),
          pomXml(
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-compiler-plugin</artifactId>
                      <executions>
                        <execution>
                          <goals>
                            <goal>compile</goal>
                          </goals>
                        </execution>
                      </executions>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """
          )
        );
    }

    @Test
    void noChangeWhenExecutionHasNoGoals() {
        rewriteRun(
          spec -> spec.recipe(new RemovePluginGoal("org.apache.maven.plugins", "maven-surefire-plugin", "verify")),
          pomXml(
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                      <executions>
                        <execution>
                          <id>default</id>
                          <phase>test</phase>
                        </execution>
                      </executions>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """
          )
        );
    }

    @Test
    void globMatchOnGoal() {
        rewriteRun(
          spec -> spec.recipe(new RemovePluginGoal("org.apache.maven.plugins", "maven-surefire-plugin", "veri*")),
          pomXml(
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                      <executions>
                        <execution>
                          <id>verify-only</id>
                          <goals>
                            <goal>verify</goal>
                          </goals>
                        </execution>
                      </executions>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """,
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """
          )
        );
    }

    @Test
    void globMatchOnPluginCoordinates() {
        rewriteRun(
          spec -> spec.recipe(new RemovePluginGoal("org.apache.maven.*", "*-surefire-plugin", "verify")),
          pomXml(
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                      <executions>
                        <execution>
                          <id>verify-only</id>
                          <goals>
                            <goal>verify</goal>
                          </goals>
                        </execution>
                      </executions>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """,
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """
          )
        );
    }

    @Test
    void removeDirectPluginGoal() {
        rewriteRun(
          spec -> spec.recipe(new RemovePluginGoal("org.apache.maven.plugins", "maven-surefire-plugin", "verify")),
          pomXml(
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                      <goals>
                        <goal>verify</goal>
                        <goal>test</goal>
                      </goals>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """,
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                      <goals>
                        <goal>test</goal>
                      </goals>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """
          )
        );
    }

    @Test
    void removeDirectPluginGoalRemovesEmptyGoals() {
        rewriteRun(
          spec -> spec.recipe(new RemovePluginGoal("org.apache.maven.plugins", "maven-surefire-plugin", "verify")),
          pomXml(
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                      <goals>
                        <goal>verify</goal>
                      </goals>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """,
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """
          )
        );
    }

    @Test
    void removeGoalFromPluginManagement() {
        rewriteRun(
          spec -> spec.recipe(new RemovePluginGoal("org.apache.maven.plugins", "maven-surefire-plugin", "verify")),
          pomXml(
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <pluginManagement>
                    <plugins>
                      <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <executions>
                          <execution>
                            <id>default</id>
                            <goals>
                              <goal>verify</goal>
                              <goal>test</goal>
                            </goals>
                          </execution>
                        </executions>
                      </plugin>
                    </plugins>
                  </pluginManagement>
                </build>
              </project>
              """,
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <pluginManagement>
                    <plugins>
                      <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <executions>
                          <execution>
                            <id>default</id>
                            <goals>
                              <goal>test</goal>
                            </goals>
                          </execution>
                        </executions>
                      </plugin>
                    </plugins>
                  </pluginManagement>
                </build>
              </project>
              """
          )
        );
    }

    @Test
    void removeGoalFromProfile() {
        rewriteRun(
          spec -> spec.recipe(new RemovePluginGoal("org.apache.maven.plugins", "maven-surefire-plugin", "verify")),
          pomXml(
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <profiles>
                  <profile>
                    <id>ci</id>
                    <build>
                      <plugins>
                        <plugin>
                          <groupId>org.apache.maven.plugins</groupId>
                          <artifactId>maven-surefire-plugin</artifactId>
                          <executions>
                            <execution>
                              <id>default</id>
                              <goals>
                                <goal>verify</goal>
                                <goal>test</goal>
                              </goals>
                            </execution>
                          </executions>
                        </plugin>
                      </plugins>
                    </build>
                  </profile>
                </profiles>
              </project>
              """,
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <profiles>
                  <profile>
                    <id>ci</id>
                    <build>
                      <plugins>
                        <plugin>
                          <groupId>org.apache.maven.plugins</groupId>
                          <artifactId>maven-surefire-plugin</artifactId>
                          <executions>
                            <execution>
                              <id>default</id>
                              <goals>
                                <goal>test</goal>
                              </goals>
                            </execution>
                          </executions>
                        </plugin>
                      </plugins>
                    </build>
                  </profile>
                </profiles>
              </project>
              """
          )
        );
    }

    @Test
    // NOTE: StringUtils.matchesGlob is case-insensitive, so "verify" matches "Verify".
    void goalMatchIsCaseInsensitive() {
        rewriteRun(
          spec -> spec.recipe(new RemovePluginGoal("org.apache.maven.plugins", "maven-surefire-plugin", "verify")),
          pomXml(
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                      <executions>
                        <execution>
                          <id>default</id>
                          <goals>
                            <goal>Verify</goal>
                          </goals>
                        </execution>
                      </executions>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """,
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """
          )
        );
    }

    @Test
    // Removing one goal must preserve comments attached to sibling goals and surrounding formatting.
    void preservesCommentsOnSiblingGoals() {
        rewriteRun(
          spec -> spec.recipe(new RemovePluginGoal("org.apache.maven.plugins", "maven-surefire-plugin", "verify")),
          pomXml(
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                      <executions>
                        <execution>
                          <id>default</id>
                          <goals>
                            <goal>verify</goal>
                            <!-- keep running tests -->
                            <goal>test</goal>
                          </goals>
                        </execution>
                      </executions>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """,
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                      <executions>
                        <execution>
                          <id>default</id>
                          <goals>
                            <!-- keep running tests -->
                            <goal>test</goal>
                          </goals>
                        </execution>
                      </executions>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """
          )
        );
    }

    @Test
    void doesNotTouchGoalInsideConfiguration() {
        rewriteRun(
          spec -> spec.recipe(new RemovePluginGoal("org.apache.maven.plugins", "maven-surefire-plugin", "verify")),
          pomXml(
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                      <configuration>
                        <goal>verify</goal>
                      </configuration>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """
          )
        );
    }

    @Test
    // Only the plugin matching the given coordinates should be affected; a different plugin with
    // the same goal name must be left untouched.
    void onlyAffectsMatchingPlugin() {
        rewriteRun(
          spec -> spec.recipe(new RemovePluginGoal("org.apache.maven.plugins", "maven-surefire-plugin", "verify")),
          pomXml(
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                      <executions>
                        <execution>
                          <id>a</id>
                          <goals>
                            <goal>verify</goal>
                          </goals>
                        </execution>
                      </executions>
                    </plugin>
                    <plugin>
                      <groupId>org.other</groupId>
                      <artifactId>other-plugin</artifactId>
                      <executions>
                        <execution>
                          <id>b</id>
                          <goals>
                            <goal>verify</goal>
                          </goals>
                        </execution>
                      </executions>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """,
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                    </plugin>
                    <plugin>
                      <groupId>org.other</groupId>
                      <artifactId>other-plugin</artifactId>
                      <executions>
                        <execution>
                          <id>b</id>
                          <goals>
                            <goal>verify</goal>
                          </goals>
                        </execution>
                      </executions>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """
          )
        );
    }

    @Test
    // Maven defaults an omitted plugin groupId to org.apache.maven.plugins for plugins
    // in <build> or <reporting> (per the Maven "Configuring Plug-ins" guide), so the recipe
    // must still match and remove the goal even when <groupId> is absent from the POM.
    void matchesWhenGroupIdOmitted() {
        rewriteRun(
          spec -> spec.recipe(new RemovePluginGoal("org.apache.maven.plugins", "maven-surefire-plugin", "verify")),
          pomXml(
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <artifactId>maven-surefire-plugin</artifactId>
                      <executions>
                        <execution>
                          <id>default</id>
                          <goals>
                            <goal>verify</goal>
                          </goals>
                        </execution>
                      </executions>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """,
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <artifactId>maven-surefire-plugin</artifactId>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """
          )
        );
    }

    @Test
    // A plugin matching the coordinates but declaring no goals at all must be left unchanged.
    void noChangeWhenPluginHasNoGoalsOrExecutions() {
        rewriteRun(
          spec -> spec.recipe(new RemovePluginGoal("org.apache.maven.plugins", "maven-surefire-plugin", "verify")),
          pomXml(
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                      <configuration>
                        <skipTests>true</skipTests>
                      </configuration>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """
          )
        );
    }

    @Test
    // The same plugin can be declared in both build/plugins and a profile; goals must be removed
    // from both locations in a single pass.
    void removesFromBothBuildAndProfile() {
        rewriteRun(
          spec -> spec.recipe(new RemovePluginGoal("org.apache.maven.plugins", "maven-surefire-plugin", "verify")),
          pomXml(
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                      <executions>
                        <execution>
                          <id>build</id>
                          <goals>
                            <goal>verify</goal>
                          </goals>
                        </execution>
                      </executions>
                    </plugin>
                  </plugins>
                </build>
                <profiles>
                  <profile>
                    <id>ci</id>
                    <build>
                      <plugins>
                        <plugin>
                          <groupId>org.apache.maven.plugins</groupId>
                          <artifactId>maven-surefire-plugin</artifactId>
                          <executions>
                            <execution>
                              <id>profile</id>
                              <goals>
                                <goal>verify</goal>
                              </goals>
                            </execution>
                          </executions>
                        </plugin>
                      </plugins>
                    </build>
                  </profile>
                </profiles>
              </project>
              """,
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                    </plugin>
                  </plugins>
                </build>
                <profiles>
                  <profile>
                    <id>ci</id>
                    <build>
                      <plugins>
                        <plugin>
                          <groupId>org.apache.maven.plugins</groupId>
                          <artifactId>maven-surefire-plugin</artifactId>
                        </plugin>
                      </plugins>
                    </build>
                  </profile>
                </profiles>
              </project>
              """
          )
        );
    }

    @Test
    // An execution's <phase> can hold the same value as the target goal (e.g. "verify").
    // Only <goal> tags inside <goals> may be removed; <phase> and <configuration> siblings
    // must be left untouched when other goals remain in the execution.
    void doesNotTouchPhaseOrConfigurationWhenGoalsRemain() {
        rewriteRun(
          spec -> spec.recipe(new RemovePluginGoal("org.apache.maven.plugins", "maven-surefire-plugin", "verify")),
          pomXml(
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                      <executions>
                        <execution>
                          <id>default</id>
                          <phase>verify</phase>
                          <goals>
                            <goal>verify</goal>
                            <goal>test</goal>
                          </goals>
                          <configuration>
                            <skipTests>false</skipTests>
                          </configuration>
                        </execution>
                      </executions>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """,
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                      <executions>
                        <execution>
                          <id>default</id>
                          <phase>verify</phase>
                          <goals>
                            <goal>test</goal>
                          </goals>
                          <configuration>
                            <skipTests>false</skipTests>
                          </configuration>
                        </execution>
                      </executions>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """
          )
        );
    }

    @Test
    // Removing the last goal removes the whole execution, taking its <phase> and
    // <configuration> siblings with it.
    void removesExecutionWithPhaseAndConfigurationWhenLastGoalRemoved() {
        rewriteRun(
          spec -> spec.recipe(new RemovePluginGoal("org.apache.maven.plugins", "maven-surefire-plugin", "verify")),
          pomXml(
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                      <executions>
                        <execution>
                          <id>default</id>
                          <phase>verify</phase>
                          <goals>
                            <goal>verify</goal>
                          </goals>
                          <configuration>
                            <skipTests>false</skipTests>
                          </configuration>
                        </execution>
                      </executions>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """,
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
                <groupId>org.sample</groupId>
                <artifactId>sample</artifactId>
                <version>1.0.0</version>
                <build>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                    </plugin>
                  </plugins>
                </build>
              </project>
              """
          )
        );
    }
}
