/*
 * Copyright 2021 the original author or authors.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openrewrite.maven;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import org.openrewrite.Issue;
import org.openrewrite.test.RewriteTest;

import static org.openrewrite.java.Assertions.mavenProject;
import static org.openrewrite.maven.Assertions.pomXml;

class UpgradeDependencyVersionTest implements RewriteTest {

    @Test
    void doNotOverrideImplicitProperty() {
        rewriteRun(
          spec -> spec.recipe(new UpgradeDependencyVersion(
            "io.dropwizard.metrics",
            "metrics-annotation",
            "4.2.9", null, true)),
          pomXml(
            """
                <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>com.example</groupId>
                    <artifactId>explicit-deps-app</artifactId>
                    <version>0.0.1-SNAPSHOT</version>
                    <name>explicit-deps-app</name>
                    <description>explicit-deps-app</description>
                    <properties>
                        <java.version>17</java.version>
                        <maven.compiler.source>17</maven.compiler.source>
                        <maven.compiler.target>17</maven.compiler.target>
                    </properties>
                    <repositories>
                        <repository>
                            <id>spring-milestone</id>
                            <url>https://repo.spring.io/milestone</url>
                            <snapshots>
                                <enabled>false</enabled>
                            </snapshots>
                        </repository>
                    </repositories>
                    <dependencyManagement>
                        <dependencies>
                            <dependency>
                                <groupId>org.springframework.boot</groupId>
                                <artifactId>spring-boot-dependencies</artifactId>
                                <version>2.4.0</version>
                                <type>pom</type>
                                <scope>import</scope>
                            </dependency>
                        </dependencies>
                    </dependencyManagement>
                    <dependencies>
                        <dependency>
                            <groupId>io.dropwizard.metrics</groupId>
                            <artifactId>metrics-annotation</artifactId>
                        </dependency>
                    </dependencies>
                </project>
            """,
            """
                <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>com.example</groupId>
                    <artifactId>explicit-deps-app</artifactId>
                    <version>0.0.1-SNAPSHOT</version>
                    <name>explicit-deps-app</name>
                    <description>explicit-deps-app</description>
                    <properties>
                        <java.version>17</java.version>
                        <maven.compiler.source>17</maven.compiler.source>
                        <maven.compiler.target>17</maven.compiler.target>
                    </properties>
                    <repositories>
                        <repository>
                            <id>spring-milestone</id>
                            <url>https://repo.spring.io/milestone</url>
                            <snapshots>
                                <enabled>false</enabled>
                            </snapshots>
                        </repository>
                    </repositories>
                    <dependencyManagement>
                        <dependencies>
                            <dependency>
                                <groupId>org.springframework.boot</groupId>
                                <artifactId>spring-boot-dependencies</artifactId>
                                <version>2.4.0</version>
                                <type>pom</type>
                                <scope>import</scope>
                            </dependency>
                        </dependencies>
                    </dependencyManagement>
                    <dependencies>
                        <dependency>
                            <groupId>io.dropwizard.metrics</groupId>
                            <artifactId>metrics-annotation</artifactId>
                            <version>4.2.9</version>
                        </dependency>
                    </dependencies>
                </project>
            """
          )
        );
    }
    @Test
    void updateManagedDependencyVersion() {
        rewriteRun(
          spec -> spec.recipe(new UpgradeDependencyVersion(
            "org.junit.jupiter",
            "junit-jupiter-api",
            "5.7.2", null, null)),
          pomXml(
            """
                  <project>
                      <groupId>com.mycompany.app</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>org.junit.jupiter</groupId>
                                  <artifactId>junit-jupiter-api</artifactId>
                                  <version>5.6.2</version>
                                  <scope>test</scope>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                  </project>
              """,
            """
                  <project>
                      <groupId>com.mycompany.app</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>org.junit.jupiter</groupId>
                                  <artifactId>junit-jupiter-api</artifactId>
                                  <version>5.7.2</version>
                                  <scope>test</scope>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                  </project>
              """
          )
        );
    }

    @ParameterizedTest
    @CsvSource(value = {"com.google.guava:guava", "*:*"}, delimiter = ':')
    void upgradeVersion(String groupId, String artifactId) {
        rewriteRun(
          spec -> spec.recipe(new UpgradeDependencyVersion(
            groupId,
            artifactId,
            "latest.patch",
            null,
            null
          )),
          pomXml(
            """
                  <project>
                    <groupId>com.mycompany.app</groupId>
                    <artifactId>my-app</artifactId>
                    <version>1</version>
                    <dependencies>
                      <dependency>
                        <groupId>com.google.guava</groupId>
                        <artifactId>guava</artifactId>
                        <version>13.0</version>
                      </dependency>
                    </dependencies>
                  </project>
              """,
            """
                  <project>
                    <groupId>com.mycompany.app</groupId>
                    <artifactId>my-app</artifactId>
                    <version>1</version>
                    <dependencies>
                      <dependency>
                        <groupId>com.google.guava</groupId>
                        <artifactId>guava</artifactId>
                        <version>13.0.1</version>
                      </dependency>
                    </dependencies>
                  </project>
              """
          )
        );
    }

    @Test
    void overrideManagedDependency() {
        rewriteRun(
          spec -> spec.recipe(new UpgradeDependencyVersion(
            "com.google.guava",
            "guava",
            "14.0",
            "",
            true
          )),
          pomXml(
            """
                  <project>
                      <groupId>com.mycompany</groupId>
                      <artifactId>my-parent</artifactId>
                      <version>1</version>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>com.google.guava</groupId>
                                  <artifactId>guava</artifactId>
                                  <version>13.0.1</version>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                  </project>
              """,
            """
                  <project>
                      <groupId>com.mycompany</groupId>
                      <artifactId>my-parent</artifactId>
                      <version>1</version>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>com.google.guava</groupId>
                                  <artifactId>guava</artifactId>
                                  <version>14.0</version>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                  </project>
              """
          ),
          mavenProject("my-child",
            pomXml(
              """
                <project>
                    <parent>
                        <groupId>com.mycompany</groupId>
                        <artifactId>my-parent</artifactId>
                        <version>1</version>
                    </parent>
                    <groupId>com.mycompany</groupId>
                    <artifactId>my-child</artifactId>
                    <version>1</version>
                    <dependencies>
                        <dependency>
                            <groupId>com.google.guava</groupId>
                            <artifactId>guava</artifactId>
                        </dependency>
                    </dependencies>
                </project>
                """,
              """
                    <project>
                        <parent>
                            <groupId>com.mycompany</groupId>
                            <artifactId>my-parent</artifactId>
                            <version>1</version>
                        </parent>
                        <groupId>com.mycompany</groupId>
                        <artifactId>my-child</artifactId>
                        <version>1</version>
                        <dependencies>
                            <dependency>
                                <groupId>com.google.guava</groupId>
                                <artifactId>guava</artifactId>
                                <version>14.0</version>
                            </dependency>
                        </dependencies>
                    </project>
                """
            )
          )
        );
    }

    @Test
    @Issue("https://github.com/openrewrite/rewrite/issues/739")
    void upgradeVersionWithGroupIdAndArtifactIdDefinedAsProperty() {
        rewriteRun(
          spec -> spec.recipe(new UpgradeDependencyVersion(
            "io.quarkus",
            "quarkus-universe-bom",
            "1.13.7.Final",
            null,
            null
          )),
          pomXml(
            """
                  <project>
                      <groupId>org.openrewrite.example</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <properties>
                          <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
                          <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
                          <quarkus.platform.version>1.11.7.Final</quarkus.platform.version>
                      </properties>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>${quarkus.platform.group-id}</groupId>
                                  <artifactId>${quarkus.platform.artifact-id}</artifactId>
                                  <version>${quarkus.platform.version}</version>
                                  <type>pom</type>
                                  <scope>import</scope>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                  </project>
              """,
            """
                  <project>
                      <groupId>org.openrewrite.example</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <properties>
                          <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
                          <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
                          <quarkus.platform.version>1.13.7.Final</quarkus.platform.version>
                      </properties>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>${quarkus.platform.group-id}</groupId>
                                  <artifactId>${quarkus.platform.artifact-id}</artifactId>
                                  <version>${quarkus.platform.version}</version>
                                  <type>pom</type>
                                  <scope>import</scope>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                  </project>
              """
          )
        );
    }

    @Test
    void upgradeVersionSuccessively() {
        rewriteRun(
          spec -> spec.recipe(new UpgradeDependencyVersion(
            "com.google.guava",
            "*",
            "28.x",
            "-jre",
            null
          ).doNext(
            new UpgradeDependencyVersion(
              "com.google.guava",
              "*",
              "29.x",
              "-jre",
              null
            )
          )),
          pomXml(
            """
                  <project>
                    <groupId>com.mycompany.app</groupId>
                    <artifactId>my-app</artifactId>
                    <version>1</version>
                    <dependencies>
                      <dependency>
                        <groupId>com.google.guava</groupId>
                        <artifactId>guava</artifactId>
                        <version>27.0-jre</version>
                      </dependency>
                    </dependencies>
                  </project>
              """,
            """
                  <project>
                    <groupId>com.mycompany.app</groupId>
                    <artifactId>my-app</artifactId>
                    <version>1</version>
                    <dependencies>
                      <dependency>
                        <groupId>com.google.guava</groupId>
                        <artifactId>guava</artifactId>
                        <version>29.0-jre</version>
                      </dependency>
                    </dependencies>
                  </project>
              """
          )
        );
    }

    @Test
    @Issue("https://github.com/openrewrite/rewrite/issues/565")
    void propertiesInDependencyGroupIdAndArtifactId() {
        rewriteRun(
          spec -> spec.recipe(new UpgradeDependencyVersion(
            "com.google.guava",
            "*",
            "latest.patch",
            null,
            null
          )),
          pomXml(
            """
                  <project>
                      <groupId>com.mycompany.app</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <properties>
                          <dependency.group-id>com.google.guava</dependency.group-id>
                          <dependency.artifact-id>guava</dependency.artifact-id>
                          <dependency.version>13.0</dependency.version>
                      </properties>
                      <dependencies>
                          <dependency>
                              <groupId>${dependency.group-id}</groupId>
                              <artifactId>${dependency.artifact-id}</artifactId>
                              <version>${dependency.version}</version>
                          </dependency>
                      </dependencies>
                  </project>
              """,
            """
                  <project>
                      <groupId>com.mycompany.app</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <properties>
                          <dependency.group-id>com.google.guava</dependency.group-id>
                          <dependency.artifact-id>guava</dependency.artifact-id>
                          <dependency.version>13.0.1</dependency.version>
                      </properties>
                      <dependencies>
                          <dependency>
                              <groupId>${dependency.group-id}</groupId>
                              <artifactId>${dependency.artifact-id}</artifactId>
                              <version>${dependency.version}</version>
                          </dependency>
                      </dependencies>
                  </project>
              """
          )
        );
    }

    @Test
    void upgradeGuava() {
        rewriteRun(
          spec -> spec.recipe(new UpgradeDependencyVersion(
            "com.google.guava",
            "*",
            "25-28",
            "-android",
            null
          )),
          pomXml(
            """
                  <project>
                    <groupId>com.mycompany.app</groupId>
                    <artifactId>my-app</artifactId>
                    <version>1</version>
                    <dependencies>
                      <dependency>
                        <groupId>com.google.guava</groupId>
                        <artifactId>guava</artifactId>
                        <version>25.0-android</version>
                      </dependency>
                    </dependencies>
                  </project>
              """,
            """
                  <project>
                    <groupId>com.mycompany.app</groupId>
                    <artifactId>my-app</artifactId>
                    <version>1</version>
                    <dependencies>
                      <dependency>
                        <groupId>com.google.guava</groupId>
                        <artifactId>guava</artifactId>
                        <version>28.0-android</version>
                      </dependency>
                    </dependencies>
                  </project>
              """
          )
        );
    }

    @Test
    @Issue("https://github.com/openrewrite/rewrite/issues/1334")
    void upgradeGuavaWithExplicitBlankVersionPattern() {
        rewriteRun(
          spec -> spec.recipe(new UpgradeDependencyVersion(
            "com.google.guava",
            "*",
            "latest.release",
            "",
            null
          )),
          pomXml(
            """
                  <project>
                    <groupId>com.mycompany.app</groupId>
                    <artifactId>my-app</artifactId>
                    <version>1</version>
                    <dependencies>
                      <dependency>
                        <groupId>com.google.guava</groupId>
                        <artifactId>guava</artifactId>
                        <version>22.0</version>
                      </dependency>
                    </dependencies>
                  </project>
              """,
            """
                  <project>
                    <groupId>com.mycompany.app</groupId>
                    <artifactId>my-app</artifactId>
                    <version>1</version>
                    <dependencies>
                      <dependency>
                        <groupId>com.google.guava</groupId>
                        <artifactId>guava</artifactId>
                        <version>23.0</version>
                      </dependency>
                    </dependencies>
                  </project>
              """
          )
        );
    }

    @Test
    void upgradeManagedInParent() {
        rewriteRun(
          spec -> spec.recipe(new UpgradeDependencyVersion(
            "com.google.guava",
            "*",
            "25-28",
            "-jre",
            false
          )),
          pomXml(
            """
                  <project>
                      <groupId>com.mycompany.app</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <properties>
                          <guava.version>25.0-jre</guava.version>
                      </properties>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>com.google.guava</groupId>
                                  <artifactId>guava</artifactId>
                                  <version>${guava.version}</version>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                  </project>
              """,
            """
                  <project>
                      <groupId>com.mycompany.app</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <properties>
                          <guava.version>28.0-jre</guava.version>
                      </properties>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>com.google.guava</groupId>
                                  <artifactId>guava</artifactId>
                                  <version>${guava.version}</version>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                  </project>
              """
          ),
          mavenProject("my-app-server",
            pomXml(
              """
                    <project>
                        <parent>
                            <groupId>com.mycompany.app</groupId>
                            <artifactId>my-app</artifactId>
                            <version>1</version>
                        </parent>
                        <groupId>com.mycompany.app</groupId>
                        <artifactId>my-app-server</artifactId>
                        <version>1</version>
                        <dependencies>
                            <dependency>
                                <groupId>com.google.guava</groupId>
                                <artifactId>guava</artifactId>
                            </dependency>
                        </dependencies>
                    </project>
                """
            )
          )
        );
    }

    @Test
    @Issue("https://github.com/openrewrite/rewrite/issues/891")
    void upgradeDependencyOnlyTargetsSpecificDependencyProperty() {
        rewriteRun(
          spec -> spec.recipe(new UpgradeDependencyVersion(
            "com.google.guava",
            "*",
            "25-28",
            "-jre",
            null
          )),
          pomXml(
            """
                  <project>
                      <groupId>org.openrewrite.example</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <properties>
                          <guava.version>25.0-jre</guava.version>
                          <spring.version>5.3.9</spring.version>
                          <spring.artifact-id>spring-jdbc</spring.artifact-id>
                      </properties>
                      <dependencies>
                          <dependency>
                              <groupId>com.google.guava</groupId>
                              <artifactId>guava</artifactId>
                              <version>${guava.version}</version>
                          </dependency>
                          <dependency>
                              <groupId>org.springframework</groupId>
                              <artifactId>${spring.artifact-id}</artifactId>
                              <version>${spring.version}</version>
                          </dependency>
                      </dependencies>
                  </project>
              """,
            """
                  <project>
                      <groupId>org.openrewrite.example</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <properties>
                          <guava.version>28.0-jre</guava.version>
                          <spring.version>5.3.9</spring.version>
                          <spring.artifact-id>spring-jdbc</spring.artifact-id>
                      </properties>
                      <dependencies>
                          <dependency>
                              <groupId>com.google.guava</groupId>
                              <artifactId>guava</artifactId>
                              <version>${guava.version}</version>
                          </dependency>
                          <dependency>
                              <groupId>org.springframework</groupId>
                              <artifactId>${spring.artifact-id}</artifactId>
                              <version>${spring.version}</version>
                          </dependency>
                      </dependencies>
                  </project>
              """
          )
        );
    }

    @Test
    void upgradeBomImport() {
        rewriteRun(
          spec -> spec.recipe(new UpgradeDependencyVersion(
            "io.micronaut",
            "micronaut-bom",
            "3.0.0-M5",
            null,
            null
          )),
          pomXml(
            """
                  <project>
                    <groupId>org.openrewrite.example</groupId>
                    <artifactId>my-app-server</artifactId>
                    <version>1</version>
                    <dependencyManagement>
                      <dependencies>
                        <dependency>
                          <groupId>io.micronaut</groupId>
                          <artifactId>micronaut-bom</artifactId>
                          <version>2.5.10</version>
                          <type>pom</type>
                          <scope>import</scope>
                        </dependency>
                      </dependencies>
                    </dependencyManagement>
                  </project>
              """,
            """
                  <project>
                    <groupId>org.openrewrite.example</groupId>
                    <artifactId>my-app-server</artifactId>
                    <version>1</version>
                    <dependencyManagement>
                      <dependencies>
                        <dependency>
                          <groupId>io.micronaut</groupId>
                          <artifactId>micronaut-bom</artifactId>
                          <version>3.0.0-M5</version>
                          <type>pom</type>
                          <scope>import</scope>
                        </dependency>
                      </dependencies>
                    </dependencyManagement>
                  </project>
              """
          )
        );
    }

    @Test
    void upgradeAllManagedDependenciesToPatchReleases() {
        rewriteRun(
          spec -> spec.recipe(new UpgradeDependencyVersion(
            "*",
            "*",
            "latest.patch",
            null,
            null
          )),
          pomXml(
            """
                  <project>
                      <groupId>org.openrewrite.example</groupId>
                      <artifactId>my-app-server</artifactId>
                      <version>1</version>
                      <properties>
                          <micronaut.version>2.5.10</micronaut.version>
                      </properties>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>io.micronaut</groupId>
                                  <artifactId>micronaut-bom</artifactId>
                                  <version>${micronaut.version}</version>
                                  <type>pom</type>
                                  <scope>import</scope>
                              </dependency>
                              <dependency>
                                  <groupId>javax.servlet</groupId>
                                  <artifactId>javax.servlet-api</artifactId>
                                  <version>4.0.0</version>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                  </project>
              """,
            """
                  <project>
                      <groupId>org.openrewrite.example</groupId>
                      <artifactId>my-app-server</artifactId>
                      <version>1</version>
                      <properties>
                          <micronaut.version>2.5.13</micronaut.version>
                      </properties>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>io.micronaut</groupId>
                                  <artifactId>micronaut-bom</artifactId>
                                  <version>${micronaut.version}</version>
                                  <type>pom</type>
                                  <scope>import</scope>
                              </dependency>
                              <dependency>
                                  <groupId>javax.servlet</groupId>
                                  <artifactId>javax.servlet-api</artifactId>
                                  <version>4.0.1</version>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                  </project>
              """
          )
        );
    }

    @Test
    void upgradeAllDependenciesToPatchReleases() {
        rewriteRun(
          spec -> spec.recipe(new UpgradeDependencyVersion(
            "*",
            "*",
            "latest.patch",
            null,
            null
          )),
          pomXml(
            """
                  <project>
                      <groupId>org.openrewrite.example</groupId>
                      <artifactId>my-app-server</artifactId>
                      <version>1</version>
                      <properties>
                          <guava.version>28.0-jre</guava.version>
                          <spring.version>5.3.4</spring.version>
                          <spring.artifact-id>spring-jdbc</spring.artifact-id>
                      </properties>
                      <dependencies>
                          <dependency>
                              <groupId>com.google.guava</groupId>
                              <artifactId>guava</artifactId>
                              <version>${guava.version}</version>
                          </dependency>
                          <dependency>
                              <groupId>org.springframework</groupId>
                              <artifactId>${spring.artifact-id}</artifactId>
                              <version>${spring.version}</version>
                          </dependency>
                          <dependency>
                              <groupId>com.fasterxml.jackson.core</groupId>
                              <artifactId>jackson-core</artifactId>
                              <version>2.13.1</version>
                          </dependency>
                      </dependencies>
                  </project>
              """,
            """
                  <project>
                      <groupId>org.openrewrite.example</groupId>
                      <artifactId>my-app-server</artifactId>
                      <version>1</version>
                      <properties>
                          <guava.version>28.0-jre</guava.version>
                          <spring.version>5.3.24</spring.version>
                          <spring.artifact-id>spring-jdbc</spring.artifact-id>
                      </properties>
                      <dependencies>
                          <dependency>
                              <groupId>com.google.guava</groupId>
                              <artifactId>guava</artifactId>
                              <version>${guava.version}</version>
                          </dependency>
                          <dependency>
                              <groupId>org.springframework</groupId>
                              <artifactId>${spring.artifact-id}</artifactId>
                              <version>${spring.version}</version>
                          </dependency>
                          <dependency>
                              <groupId>com.fasterxml.jackson.core</groupId>
                              <artifactId>jackson-core</artifactId>
                              <version>2.13.4</version>
                          </dependency>
                      </dependencies>
                  </project>
              """
          )
        );
    }

    @Test
    void dependencyManagementResolvedFromProperty() {
        rewriteRun(
          spec -> spec.recipe(new UpgradeDependencyVersion(
            "io.micronaut",
            "micronaut-bom",
            "3.0.0-M5",
            null,
            null
          )),
          pomXml(
            """
                  <project>
                    <groupId>org.openrewrite</groupId>
                    <artifactId>my-app-server</artifactId>
                    <version>1.0.0</version>
                    <properties>
                      <micronaut.version>2.5.11</micronaut.version>
                    </properties>
                    <dependencyManagement>
                      <dependencies>
                        <dependency>
                          <groupId>io.micronaut</groupId>
                          <artifactId>micronaut-bom</artifactId>
                          <version>${micronaut.version}</version>
                          <type>pom</type>
                          <scope>import</scope>
                        </dependency>
                      </dependencies>
                    </dependencyManagement>
                  </project>
              """,
            """
                  <project>
                    <groupId>org.openrewrite</groupId>
                    <artifactId>my-app-server</artifactId>
                    <version>1.0.0</version>
                    <properties>
                      <micronaut.version>3.0.0-M5</micronaut.version>
                    </properties>
                    <dependencyManagement>
                      <dependencies>
                        <dependency>
                          <groupId>io.micronaut</groupId>
                          <artifactId>micronaut-bom</artifactId>
                          <version>${micronaut.version}</version>
                          <type>pom</type>
                          <scope>import</scope>
                        </dependency>
                      </dependencies>
                    </dependencyManagement>
                  </project>
              """
          )
        );
    }

    @Test
    void upgradeToExactVersion() {
        rewriteRun(
          spec -> spec.recipe(new UpgradeDependencyVersion(
            "org.thymeleaf",
            "thymeleaf-spring5",
            "3.0.12.RELEASE",
            null,
            null
          )),
          pomXml(
            """
                  <project>
                      <groupId>com.mycompany.app</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <dependencies>
                          <dependency>
                              <groupId>org.thymeleaf</groupId>
                              <artifactId>thymeleaf-spring5</artifactId>
                              <version>3.0.8.RELEASE</version>
                          </dependency>
                      </dependencies>
                  </project>
              """,
            """
                  <project>
                      <groupId>com.mycompany.app</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <dependencies>
                          <dependency>
                              <groupId>org.thymeleaf</groupId>
                              <artifactId>thymeleaf-spring5</artifactId>
                              <version>3.0.12.RELEASE</version>
                          </dependency>
                      </dependencies>
                  </project>
              """
          )
        );
    }

    @Issue("https://github.com/openrewrite/rewrite/issues/1248")
    @Test
    void updateWithExactVersionRange() {
        rewriteRun(
          spec -> spec.recipe(new UpgradeDependencyVersion(
            "junit",
            "junit",
            "4.13",
            null,
            false
          )),
          pomXml(
            """
                  <project>
                    <groupId>com.mycompany.app</groupId>
                    <artifactId>my-app</artifactId>
                    <version>1</version>
                    <dependencies>
                      <dependency>
                        <groupId>junit</groupId>
                        <artifactId>junit</artifactId>
                        <version>[4.11]</version>
                      </dependency>
                    </dependencies>
                  </project>
              """,
            """            
                  <project>
                    <groupId>com.mycompany.app</groupId>
                    <artifactId>my-app</artifactId>
                    <version>1</version>
                    <dependencies>
                      <dependency>
                        <groupId>junit</groupId>
                        <artifactId>junit</artifactId>
                        <version>4.13</version>
                      </dependency>
                    </dependencies>
                  </project>
              """
          )
        );
    }

    @Test
    void deriveFromNexus() {
        rewriteRun(
          spec -> spec.recipe(new UpgradeDependencyVersion(
            "*",
            "*",
            "latest.patch", null, null
          )),
          pomXml(
            """
                  <project>
                      <groupId>com.mycompany.app</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>net.sourceforge.saxon</groupId>
                                  <artifactId>saxon</artifactId>
                                  <version>9.1.0.8</version>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                  </project>
              """
          )
        );
    }

    @Test
    void deriveFromNexusUpgrade() {
        rewriteRun(
          spec -> spec.recipe(new UpgradeDependencyVersion(
            "*",
            "*",
            "latest.patch", null, null
          )),
          pomXml(
            """
                  <project>
                      <groupId>com.mycompany.app</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>net.sourceforge.orbroker</groupId>
                                  <artifactId>orbroker</artifactId>
                                  <version>2.0.3</version>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                  </project>
              """,
            """
                  <project>
                      <groupId>com.mycompany.app</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>net.sourceforge.orbroker</groupId>
                                  <artifactId>orbroker</artifactId>
                                  <version>2.0.4</version>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                  </project>
              """
          )
        );
    }

    @Test
    void noManagedVersion() {
        rewriteRun(
          spec -> spec.recipe(new UpgradeDependencyVersion(
            "*",
            "*",
            "latest.patch", null, null
          )),
          pomXml(
            """
                  <project>
                      <groupId>com.mycompany.app</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <dependencyManagement>
                          <dependencies>
                              <dependency>
                                  <groupId>net.sourceforge.orbroker</groupId>
                                  <artifactId>orbroker</artifactId>
                              </dependency>
                          </dependencies>
                      </dependencyManagement>
                  </project>
              """
          )
        );
    }
}
