/*
 * Copyright 2026 the original author or authors.
 * <p>
 * Licensed under the Moderne Source Available License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://docs.moderne.io/licensing/moderne-source-available-license
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/andrew/conductor/workspaces/rewrite/la-paz/rewrite-xml/src/main/antlr/XMLParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace OpenRewrite.Xml.Grammar {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class XMLParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		WS=1, COMMENT=2, CDATA=3, ParamEntityRef=4, EntityRef=5, CharRef=6, SEA_WS=7, 
		UTF_ENCODING_BOM=8, QUESTION_MARK=9, SPECIAL_OPEN_XML=10, OPEN=11, SPECIAL_OPEN=12, 
		DTD_OPEN=13, JSP_COMMENT=14, JSP_DECLARATION=15, JSP_EXPRESSION=16, JSP_SCRIPTLET=17, 
		TEXT=18, DTD_CLOSE=19, DTD_SUBSET_OPEN=20, DTD_S=21, DOCTYPE=22, DTD_SUBSET_CLOSE=23, 
		MARKUP_OPEN=24, DTS_SUBSET_S=25, MARK_UP_CLOSE=26, MARKUP_S=27, MARKUP_TEXT=28, 
		MARKUP_SUBSET=29, PI_S=30, PI_TEXT=31, CLOSE=32, SPECIAL_CLOSE=33, SLASH_CLOSE=34, 
		S=35, DIRECTIVE_OPEN=36, DIRECTIVE_CLOSE=37, SLASH=38, EQUALS=39, STRING=40, 
		Name=41;
	public const int
		RULE_document = 0, RULE_prolog = 1, RULE_xmldecl = 2, RULE_misc = 3, RULE_doctypedecl = 4, 
		RULE_intsubset = 5, RULE_markupdecl = 6, RULE_declSep = 7, RULE_externalid = 8, 
		RULE_processinginstruction = 9, RULE_content = 10, RULE_element = 11, 
		RULE_jspdirective = 12, RULE_jspscriptlet = 13, RULE_jspexpression = 14, 
		RULE_jspdeclaration = 15, RULE_jspcomment = 16, RULE_reference = 17, RULE_attribute = 18, 
		RULE_chardata = 19;
	public static readonly string[] ruleNames = {
		"document", "prolog", "xmldecl", "misc", "doctypedecl", "intsubset", "markupdecl", 
		"declSep", "externalid", "processinginstruction", "content", "element", 
		"jspdirective", "jspscriptlet", "jspexpression", "jspdeclaration", "jspcomment", 
		"reference", "attribute", "chardata"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, null, null, null, "'?'", null, "'<'", 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, "'/>'", null, 
		"'%@'", "'%'", "'/'", "'='"
	};
	private static readonly string[] _SymbolicNames = {
		null, "WS", "COMMENT", "CDATA", "ParamEntityRef", "EntityRef", "CharRef", 
		"SEA_WS", "UTF_ENCODING_BOM", "QUESTION_MARK", "SPECIAL_OPEN_XML", "OPEN", 
		"SPECIAL_OPEN", "DTD_OPEN", "JSP_COMMENT", "JSP_DECLARATION", "JSP_EXPRESSION", 
		"JSP_SCRIPTLET", "TEXT", "DTD_CLOSE", "DTD_SUBSET_OPEN", "DTD_S", "DOCTYPE", 
		"DTD_SUBSET_CLOSE", "MARKUP_OPEN", "DTS_SUBSET_S", "MARK_UP_CLOSE", "MARKUP_S", 
		"MARKUP_TEXT", "MARKUP_SUBSET", "PI_S", "PI_TEXT", "CLOSE", "SPECIAL_CLOSE", 
		"SLASH_CLOSE", "S", "DIRECTIVE_OPEN", "DIRECTIVE_CLOSE", "SLASH", "EQUALS", 
		"STRING", "Name"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "XMLParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static XMLParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public XMLParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public XMLParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class DocumentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PrologContext prolog() {
			return GetRuleContext<PrologContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode UTF_ENCODING_BOM() { return GetToken(XMLParser.UTF_ENCODING_BOM, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ElementContext element() {
			return GetRuleContext<ElementContext>(0);
		}
		public DocumentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_document; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.EnterDocument(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.ExitDocument(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IXMLParserVisitor<TResult> typedVisitor = visitor as IXMLParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDocument(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DocumentContext document() {
		DocumentContext _localctx = new DocumentContext(Context, State);
		EnterRule(_localctx, 0, RULE_document);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 41;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==UTF_ENCODING_BOM) {
				{
				State = 40;
				Match(UTF_ENCODING_BOM);
				}
			}

			State = 43;
			prolog();
			State = 45;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==OPEN) {
				{
				State = 44;
				element();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PrologContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public XmldeclContext xmldecl() {
			return GetRuleContext<XmldeclContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MiscContext[] misc() {
			return GetRuleContexts<MiscContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public MiscContext misc(int i) {
			return GetRuleContext<MiscContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public JspdirectiveContext[] jspdirective() {
			return GetRuleContexts<JspdirectiveContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public JspdirectiveContext jspdirective(int i) {
			return GetRuleContext<JspdirectiveContext>(i);
		}
		public PrologContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_prolog; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.EnterProlog(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.ExitProlog(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IXMLParserVisitor<TResult> typedVisitor = visitor as IXMLParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProlog(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PrologContext prolog() {
		PrologContext _localctx = new PrologContext(Context, State);
		EnterRule(_localctx, 2, RULE_prolog);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 48;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==SPECIAL_OPEN_XML) {
				{
				State = 47;
				xmldecl();
				}
			}

			State = 53;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 61444L) != 0)) {
				{
				{
				State = 50;
				misc();
				}
				}
				State = 55;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 59;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,4,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 56;
					jspdirective();
					}
					} 
				}
				State = 61;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,4,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class XmldeclContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPECIAL_OPEN_XML() { return GetToken(XMLParser.SPECIAL_OPEN_XML, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPECIAL_CLOSE() { return GetToken(XMLParser.SPECIAL_CLOSE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public AttributeContext[] attribute() {
			return GetRuleContexts<AttributeContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public AttributeContext attribute(int i) {
			return GetRuleContext<AttributeContext>(i);
		}
		public XmldeclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_xmldecl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.EnterXmldecl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.ExitXmldecl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IXMLParserVisitor<TResult> typedVisitor = visitor as IXMLParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitXmldecl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public XmldeclContext xmldecl() {
		XmldeclContext _localctx = new XmldeclContext(Context, State);
		EnterRule(_localctx, 4, RULE_xmldecl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 62;
			Match(SPECIAL_OPEN_XML);
			State = 66;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==Name) {
				{
				{
				State = 63;
				attribute();
				}
				}
				State = 68;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 69;
			Match(SPECIAL_CLOSE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MiscContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMENT() { return GetToken(XMLParser.COMMENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public DoctypedeclContext doctypedecl() {
			return GetRuleContext<DoctypedeclContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ProcessinginstructionContext processinginstruction() {
			return GetRuleContext<ProcessinginstructionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public JspdeclarationContext jspdeclaration() {
			return GetRuleContext<JspdeclarationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public JspcommentContext jspcomment() {
			return GetRuleContext<JspcommentContext>(0);
		}
		public MiscContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_misc; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.EnterMisc(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.ExitMisc(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IXMLParserVisitor<TResult> typedVisitor = visitor as IXMLParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMisc(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MiscContext misc() {
		MiscContext _localctx = new MiscContext(Context, State);
		EnterRule(_localctx, 6, RULE_misc);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 76;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case COMMENT:
				{
				State = 71;
				Match(COMMENT);
				}
				break;
			case DTD_OPEN:
				{
				State = 72;
				doctypedecl();
				}
				break;
			case SPECIAL_OPEN:
				{
				State = 73;
				processinginstruction();
				}
				break;
			case JSP_DECLARATION:
				{
				State = 74;
				jspdeclaration();
				}
				break;
			case JSP_COMMENT:
				{
				State = 75;
				jspcomment();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DoctypedeclContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DTD_OPEN() { return GetToken(XMLParser.DTD_OPEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOCTYPE() { return GetToken(XMLParser.DOCTYPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Name() { return GetToken(XMLParser.Name, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExternalidContext externalid() {
			return GetRuleContext<ExternalidContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DTD_CLOSE() { return GetToken(XMLParser.DTD_CLOSE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] STRING() { return GetTokens(XMLParser.STRING); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING(int i) {
			return GetToken(XMLParser.STRING, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DTD_SUBSET_OPEN() { return GetToken(XMLParser.DTD_SUBSET_OPEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public IntsubsetContext intsubset() {
			return GetRuleContext<IntsubsetContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DTD_SUBSET_CLOSE() { return GetToken(XMLParser.DTD_SUBSET_CLOSE, 0); }
		public DoctypedeclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_doctypedecl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.EnterDoctypedecl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.ExitDoctypedecl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IXMLParserVisitor<TResult> typedVisitor = visitor as IXMLParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDoctypedecl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DoctypedeclContext doctypedecl() {
		DoctypedeclContext _localctx = new DoctypedeclContext(Context, State);
		EnterRule(_localctx, 8, RULE_doctypedecl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 78;
			Match(DTD_OPEN);
			State = 79;
			Match(DOCTYPE);
			State = 80;
			Match(Name);
			State = 81;
			externalid();
			State = 85;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==STRING) {
				{
				{
				State = 82;
				Match(STRING);
				}
				}
				State = 87;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 92;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==DTD_SUBSET_OPEN) {
				{
				State = 88;
				Match(DTD_SUBSET_OPEN);
				State = 89;
				intsubset();
				State = 90;
				Match(DTD_SUBSET_CLOSE);
				}
			}

			State = 94;
			Match(DTD_CLOSE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IntsubsetContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public MarkupdeclContext[] markupdecl() {
			return GetRuleContexts<MarkupdeclContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public MarkupdeclContext markupdecl(int i) {
			return GetRuleContext<MarkupdeclContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DeclSepContext[] declSep() {
			return GetRuleContexts<DeclSepContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public DeclSepContext declSep(int i) {
			return GetRuleContext<DeclSepContext>(i);
		}
		public IntsubsetContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_intsubset; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.EnterIntsubset(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.ExitIntsubset(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IXMLParserVisitor<TResult> typedVisitor = visitor as IXMLParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIntsubset(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IntsubsetContext intsubset() {
		IntsubsetContext _localctx = new IntsubsetContext(Context, State);
		EnterRule(_localctx, 10, RULE_intsubset);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 100;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 16781332L) != 0)) {
				{
				State = 98;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case COMMENT:
				case SPECIAL_OPEN:
				case MARKUP_OPEN:
					{
					State = 96;
					markupdecl();
					}
					break;
				case ParamEntityRef:
					{
					State = 97;
					declSep();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 102;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MarkupdeclContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MARKUP_OPEN() { return GetToken(XMLParser.MARKUP_OPEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MARK_UP_CLOSE() { return GetToken(XMLParser.MARK_UP_CLOSE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] MARKUP_TEXT() { return GetTokens(XMLParser.MARKUP_TEXT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MARKUP_TEXT(int i) {
			return GetToken(XMLParser.MARKUP_TEXT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] MARKUP_SUBSET() { return GetTokens(XMLParser.MARKUP_SUBSET); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MARKUP_SUBSET(int i) {
			return GetToken(XMLParser.MARKUP_SUBSET, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ProcessinginstructionContext processinginstruction() {
			return GetRuleContext<ProcessinginstructionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMENT() { return GetToken(XMLParser.COMMENT, 0); }
		public MarkupdeclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_markupdecl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.EnterMarkupdecl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.ExitMarkupdecl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IXMLParserVisitor<TResult> typedVisitor = visitor as IXMLParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMarkupdecl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MarkupdeclContext markupdecl() {
		MarkupdeclContext _localctx = new MarkupdeclContext(Context, State);
		EnterRule(_localctx, 12, RULE_markupdecl);
		int _la;
		try {
			State = 119;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case MARKUP_OPEN:
				EnterOuterAlt(_localctx, 1);
				{
				{
				State = 103;
				Match(MARKUP_OPEN);
				State = 105;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
				case 1:
					{
					State = 104;
					Match(MARKUP_TEXT);
					}
					break;
				}
				State = 110;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==MARKUP_SUBSET) {
					{
					{
					State = 107;
					Match(MARKUP_SUBSET);
					}
					}
					State = 112;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 114;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==MARKUP_TEXT) {
					{
					State = 113;
					Match(MARKUP_TEXT);
					}
				}

				State = 116;
				Match(MARK_UP_CLOSE);
				}
				}
				break;
			case SPECIAL_OPEN:
				EnterOuterAlt(_localctx, 2);
				{
				State = 117;
				processinginstruction();
				}
				break;
			case COMMENT:
				EnterOuterAlt(_localctx, 3);
				{
				State = 118;
				Match(COMMENT);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DeclSepContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ParamEntityRef() { return GetToken(XMLParser.ParamEntityRef, 0); }
		public DeclSepContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_declSep; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.EnterDeclSep(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.ExitDeclSep(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IXMLParserVisitor<TResult> typedVisitor = visitor as IXMLParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDeclSep(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DeclSepContext declSep() {
		DeclSepContext _localctx = new DeclSepContext(Context, State);
		EnterRule(_localctx, 14, RULE_declSep);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 121;
			Match(ParamEntityRef);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExternalidContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Name() { return GetToken(XMLParser.Name, 0); }
		public ExternalidContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_externalid; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.EnterExternalid(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.ExitExternalid(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IXMLParserVisitor<TResult> typedVisitor = visitor as IXMLParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExternalid(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExternalidContext externalid() {
		ExternalidContext _localctx = new ExternalidContext(Context, State);
		EnterRule(_localctx, 16, RULE_externalid);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 124;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Name) {
				{
				State = 123;
				Match(Name);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ProcessinginstructionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPECIAL_OPEN() { return GetToken(XMLParser.SPECIAL_OPEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPECIAL_CLOSE() { return GetToken(XMLParser.SPECIAL_CLOSE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] PI_TEXT() { return GetTokens(XMLParser.PI_TEXT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PI_TEXT(int i) {
			return GetToken(XMLParser.PI_TEXT, i);
		}
		public ProcessinginstructionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_processinginstruction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.EnterProcessinginstruction(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.ExitProcessinginstruction(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IXMLParserVisitor<TResult> typedVisitor = visitor as IXMLParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProcessinginstruction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProcessinginstructionContext processinginstruction() {
		ProcessinginstructionContext _localctx = new ProcessinginstructionContext(Context, State);
		EnterRule(_localctx, 18, RULE_processinginstruction);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 126;
			Match(SPECIAL_OPEN);
			State = 128;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 127;
				Match(PI_TEXT);
				}
				}
				State = 130;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==PI_TEXT );
			State = 132;
			Match(SPECIAL_CLOSE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ContentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ElementContext element() {
			return GetRuleContext<ElementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ReferenceContext reference() {
			return GetRuleContext<ReferenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ProcessinginstructionContext processinginstruction() {
			return GetRuleContext<ProcessinginstructionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CDATA() { return GetToken(XMLParser.CDATA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMENT() { return GetToken(XMLParser.COMMENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public JspscriptletContext jspscriptlet() {
			return GetRuleContext<JspscriptletContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public JspexpressionContext jspexpression() {
			return GetRuleContext<JspexpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public JspdeclarationContext jspdeclaration() {
			return GetRuleContext<JspdeclarationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public JspcommentContext jspcomment() {
			return GetRuleContext<JspcommentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ChardataContext chardata() {
			return GetRuleContext<ChardataContext>(0);
		}
		public ContentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_content; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.EnterContent(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.ExitContent(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IXMLParserVisitor<TResult> typedVisitor = visitor as IXMLParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitContent(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ContentContext content() {
		ContentContext _localctx = new ContentContext(Context, State);
		EnterRule(_localctx, 20, RULE_content);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 144;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case OPEN:
				{
				State = 134;
				element();
				}
				break;
			case EntityRef:
			case CharRef:
				{
				State = 135;
				reference();
				}
				break;
			case SPECIAL_OPEN:
				{
				State = 136;
				processinginstruction();
				}
				break;
			case CDATA:
				{
				State = 137;
				Match(CDATA);
				}
				break;
			case COMMENT:
				{
				State = 138;
				Match(COMMENT);
				}
				break;
			case JSP_SCRIPTLET:
				{
				State = 139;
				jspscriptlet();
				}
				break;
			case JSP_EXPRESSION:
				{
				State = 140;
				jspexpression();
				}
				break;
			case JSP_DECLARATION:
				{
				State = 141;
				jspdeclaration();
				}
				break;
			case JSP_COMMENT:
				{
				State = 142;
				jspcomment();
				}
				break;
			case SEA_WS:
			case QUESTION_MARK:
			case TEXT:
				{
				State = 143;
				chardata();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ElementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] OPEN() { return GetTokens(XMLParser.OPEN); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPEN(int i) {
			return GetToken(XMLParser.OPEN, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Name() { return GetTokens(XMLParser.Name); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Name(int i) {
			return GetToken(XMLParser.Name, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] CLOSE() { return GetTokens(XMLParser.CLOSE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CLOSE(int i) {
			return GetToken(XMLParser.CLOSE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SLASH() { return GetToken(XMLParser.SLASH, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public AttributeContext[] attribute() {
			return GetRuleContexts<AttributeContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public AttributeContext attribute(int i) {
			return GetRuleContext<AttributeContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ContentContext[] content() {
			return GetRuleContexts<ContentContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ContentContext content(int i) {
			return GetRuleContext<ContentContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SLASH_CLOSE() { return GetToken(XMLParser.SLASH_CLOSE, 0); }
		public ElementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_element; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.EnterElement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.ExitElement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IXMLParserVisitor<TResult> typedVisitor = visitor as IXMLParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitElement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ElementContext element() {
		ElementContext _localctx = new ElementContext(Context, State);
		EnterRule(_localctx, 22, RULE_element);
		int _la;
		try {
			int _alt;
			State = 174;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,21,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 146;
				Match(OPEN);
				State = 147;
				Match(Name);
				State = 151;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==Name) {
					{
					{
					State = 148;
					attribute();
					}
					}
					State = 153;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 154;
				Match(CLOSE);
				State = 158;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,19,Context);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
					if ( _alt==1 ) {
						{
						{
						State = 155;
						content();
						}
						} 
					}
					State = 160;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,19,Context);
				}
				State = 161;
				Match(OPEN);
				State = 162;
				Match(SLASH);
				State = 163;
				Match(Name);
				State = 164;
				Match(CLOSE);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 165;
				Match(OPEN);
				State = 166;
				Match(Name);
				State = 170;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==Name) {
					{
					{
					State = 167;
					attribute();
					}
					}
					State = 172;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 173;
				Match(SLASH_CLOSE);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class JspdirectiveContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPEN() { return GetToken(XMLParser.OPEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIRECTIVE_OPEN() { return GetToken(XMLParser.DIRECTIVE_OPEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Name() { return GetToken(XMLParser.Name, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIRECTIVE_CLOSE() { return GetToken(XMLParser.DIRECTIVE_CLOSE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CLOSE() { return GetToken(XMLParser.CLOSE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public AttributeContext[] attribute() {
			return GetRuleContexts<AttributeContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public AttributeContext attribute(int i) {
			return GetRuleContext<AttributeContext>(i);
		}
		public JspdirectiveContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_jspdirective; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.EnterJspdirective(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.ExitJspdirective(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IXMLParserVisitor<TResult> typedVisitor = visitor as IXMLParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJspdirective(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public JspdirectiveContext jspdirective() {
		JspdirectiveContext _localctx = new JspdirectiveContext(Context, State);
		EnterRule(_localctx, 24, RULE_jspdirective);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 176;
			Match(OPEN);
			State = 177;
			Match(DIRECTIVE_OPEN);
			State = 178;
			Match(Name);
			State = 182;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==Name) {
				{
				{
				State = 179;
				attribute();
				}
				}
				State = 184;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 185;
			Match(DIRECTIVE_CLOSE);
			State = 186;
			Match(CLOSE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class JspscriptletContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode JSP_SCRIPTLET() { return GetToken(XMLParser.JSP_SCRIPTLET, 0); }
		public JspscriptletContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_jspscriptlet; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.EnterJspscriptlet(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.ExitJspscriptlet(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IXMLParserVisitor<TResult> typedVisitor = visitor as IXMLParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJspscriptlet(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public JspscriptletContext jspscriptlet() {
		JspscriptletContext _localctx = new JspscriptletContext(Context, State);
		EnterRule(_localctx, 26, RULE_jspscriptlet);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 188;
			Match(JSP_SCRIPTLET);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class JspexpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode JSP_EXPRESSION() { return GetToken(XMLParser.JSP_EXPRESSION, 0); }
		public JspexpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_jspexpression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.EnterJspexpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.ExitJspexpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IXMLParserVisitor<TResult> typedVisitor = visitor as IXMLParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJspexpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public JspexpressionContext jspexpression() {
		JspexpressionContext _localctx = new JspexpressionContext(Context, State);
		EnterRule(_localctx, 28, RULE_jspexpression);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 190;
			Match(JSP_EXPRESSION);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class JspdeclarationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode JSP_DECLARATION() { return GetToken(XMLParser.JSP_DECLARATION, 0); }
		public JspdeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_jspdeclaration; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.EnterJspdeclaration(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.ExitJspdeclaration(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IXMLParserVisitor<TResult> typedVisitor = visitor as IXMLParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJspdeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public JspdeclarationContext jspdeclaration() {
		JspdeclarationContext _localctx = new JspdeclarationContext(Context, State);
		EnterRule(_localctx, 30, RULE_jspdeclaration);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 192;
			Match(JSP_DECLARATION);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class JspcommentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode JSP_COMMENT() { return GetToken(XMLParser.JSP_COMMENT, 0); }
		public JspcommentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_jspcomment; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.EnterJspcomment(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.ExitJspcomment(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IXMLParserVisitor<TResult> typedVisitor = visitor as IXMLParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJspcomment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public JspcommentContext jspcomment() {
		JspcommentContext _localctx = new JspcommentContext(Context, State);
		EnterRule(_localctx, 32, RULE_jspcomment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 194;
			Match(JSP_COMMENT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ReferenceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EntityRef() { return GetToken(XMLParser.EntityRef, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CharRef() { return GetToken(XMLParser.CharRef, 0); }
		public ReferenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_reference; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.EnterReference(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.ExitReference(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IXMLParserVisitor<TResult> typedVisitor = visitor as IXMLParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitReference(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ReferenceContext reference() {
		ReferenceContext _localctx = new ReferenceContext(Context, State);
		EnterRule(_localctx, 34, RULE_reference);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 196;
			_la = TokenStream.LA(1);
			if ( !(_la==EntityRef || _la==CharRef) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AttributeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Name() { return GetToken(XMLParser.Name, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUALS() { return GetToken(XMLParser.EQUALS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(XMLParser.STRING, 0); }
		public AttributeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_attribute; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.EnterAttribute(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.ExitAttribute(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IXMLParserVisitor<TResult> typedVisitor = visitor as IXMLParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAttribute(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AttributeContext attribute() {
		AttributeContext _localctx = new AttributeContext(Context, State);
		EnterRule(_localctx, 36, RULE_attribute);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 198;
			Match(Name);
			State = 199;
			Match(EQUALS);
			State = 200;
			Match(STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ChardataContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TEXT() { return GetToken(XMLParser.TEXT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode QUESTION_MARK() { return GetToken(XMLParser.QUESTION_MARK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEA_WS() { return GetToken(XMLParser.SEA_WS, 0); }
		public ChardataContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_chardata; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.EnterChardata(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IXMLParserListener typedListener = listener as IXMLParserListener;
			if (typedListener != null) typedListener.ExitChardata(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IXMLParserVisitor<TResult> typedVisitor = visitor as IXMLParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitChardata(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ChardataContext chardata() {
		ChardataContext _localctx = new ChardataContext(Context, State);
		EnterRule(_localctx, 38, RULE_chardata);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 202;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 262784L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,41,205,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,1,0,3,0,42,8,0,1,0,1,
		0,3,0,46,8,0,1,1,3,1,49,8,1,1,1,5,1,52,8,1,10,1,12,1,55,9,1,1,1,5,1,58,
		8,1,10,1,12,1,61,9,1,1,2,1,2,5,2,65,8,2,10,2,12,2,68,9,2,1,2,1,2,1,3,1,
		3,1,3,1,3,1,3,3,3,77,8,3,1,4,1,4,1,4,1,4,1,4,5,4,84,8,4,10,4,12,4,87,9,
		4,1,4,1,4,1,4,1,4,3,4,93,8,4,1,4,1,4,1,5,1,5,5,5,99,8,5,10,5,12,5,102,
		9,5,1,6,1,6,3,6,106,8,6,1,6,5,6,109,8,6,10,6,12,6,112,9,6,1,6,3,6,115,
		8,6,1,6,1,6,1,6,3,6,120,8,6,1,7,1,7,1,8,3,8,125,8,8,1,9,1,9,4,9,129,8,
		9,11,9,12,9,130,1,9,1,9,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,
		10,3,10,145,8,10,1,11,1,11,1,11,5,11,150,8,11,10,11,12,11,153,9,11,1,11,
		1,11,5,11,157,8,11,10,11,12,11,160,9,11,1,11,1,11,1,11,1,11,1,11,1,11,
		1,11,5,11,169,8,11,10,11,12,11,172,9,11,1,11,3,11,175,8,11,1,12,1,12,1,
		12,1,12,5,12,181,8,12,10,12,12,12,184,9,12,1,12,1,12,1,12,1,13,1,13,1,
		14,1,14,1,15,1,15,1,16,1,16,1,17,1,17,1,18,1,18,1,18,1,18,1,19,1,19,1,
		19,0,0,20,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,0,2,1,
		0,5,6,3,0,7,7,9,9,18,18,219,0,41,1,0,0,0,2,48,1,0,0,0,4,62,1,0,0,0,6,76,
		1,0,0,0,8,78,1,0,0,0,10,100,1,0,0,0,12,119,1,0,0,0,14,121,1,0,0,0,16,124,
		1,0,0,0,18,126,1,0,0,0,20,144,1,0,0,0,22,174,1,0,0,0,24,176,1,0,0,0,26,
		188,1,0,0,0,28,190,1,0,0,0,30,192,1,0,0,0,32,194,1,0,0,0,34,196,1,0,0,
		0,36,198,1,0,0,0,38,202,1,0,0,0,40,42,5,8,0,0,41,40,1,0,0,0,41,42,1,0,
		0,0,42,43,1,0,0,0,43,45,3,2,1,0,44,46,3,22,11,0,45,44,1,0,0,0,45,46,1,
		0,0,0,46,1,1,0,0,0,47,49,3,4,2,0,48,47,1,0,0,0,48,49,1,0,0,0,49,53,1,0,
		0,0,50,52,3,6,3,0,51,50,1,0,0,0,52,55,1,0,0,0,53,51,1,0,0,0,53,54,1,0,
		0,0,54,59,1,0,0,0,55,53,1,0,0,0,56,58,3,24,12,0,57,56,1,0,0,0,58,61,1,
		0,0,0,59,57,1,0,0,0,59,60,1,0,0,0,60,3,1,0,0,0,61,59,1,0,0,0,62,66,5,10,
		0,0,63,65,3,36,18,0,64,63,1,0,0,0,65,68,1,0,0,0,66,64,1,0,0,0,66,67,1,
		0,0,0,67,69,1,0,0,0,68,66,1,0,0,0,69,70,5,33,0,0,70,5,1,0,0,0,71,77,5,
		2,0,0,72,77,3,8,4,0,73,77,3,18,9,0,74,77,3,30,15,0,75,77,3,32,16,0,76,
		71,1,0,0,0,76,72,1,0,0,0,76,73,1,0,0,0,76,74,1,0,0,0,76,75,1,0,0,0,77,
		7,1,0,0,0,78,79,5,13,0,0,79,80,5,22,0,0,80,81,5,41,0,0,81,85,3,16,8,0,
		82,84,5,40,0,0,83,82,1,0,0,0,84,87,1,0,0,0,85,83,1,0,0,0,85,86,1,0,0,0,
		86,92,1,0,0,0,87,85,1,0,0,0,88,89,5,20,0,0,89,90,3,10,5,0,90,91,5,23,0,
		0,91,93,1,0,0,0,92,88,1,0,0,0,92,93,1,0,0,0,93,94,1,0,0,0,94,95,5,19,0,
		0,95,9,1,0,0,0,96,99,3,12,6,0,97,99,3,14,7,0,98,96,1,0,0,0,98,97,1,0,0,
		0,99,102,1,0,0,0,100,98,1,0,0,0,100,101,1,0,0,0,101,11,1,0,0,0,102,100,
		1,0,0,0,103,105,5,24,0,0,104,106,5,28,0,0,105,104,1,0,0,0,105,106,1,0,
		0,0,106,110,1,0,0,0,107,109,5,29,0,0,108,107,1,0,0,0,109,112,1,0,0,0,110,
		108,1,0,0,0,110,111,1,0,0,0,111,114,1,0,0,0,112,110,1,0,0,0,113,115,5,
		28,0,0,114,113,1,0,0,0,114,115,1,0,0,0,115,116,1,0,0,0,116,120,5,26,0,
		0,117,120,3,18,9,0,118,120,5,2,0,0,119,103,1,0,0,0,119,117,1,0,0,0,119,
		118,1,0,0,0,120,13,1,0,0,0,121,122,5,4,0,0,122,15,1,0,0,0,123,125,5,41,
		0,0,124,123,1,0,0,0,124,125,1,0,0,0,125,17,1,0,0,0,126,128,5,12,0,0,127,
		129,5,31,0,0,128,127,1,0,0,0,129,130,1,0,0,0,130,128,1,0,0,0,130,131,1,
		0,0,0,131,132,1,0,0,0,132,133,5,33,0,0,133,19,1,0,0,0,134,145,3,22,11,
		0,135,145,3,34,17,0,136,145,3,18,9,0,137,145,5,3,0,0,138,145,5,2,0,0,139,
		145,3,26,13,0,140,145,3,28,14,0,141,145,3,30,15,0,142,145,3,32,16,0,143,
		145,3,38,19,0,144,134,1,0,0,0,144,135,1,0,0,0,144,136,1,0,0,0,144,137,
		1,0,0,0,144,138,1,0,0,0,144,139,1,0,0,0,144,140,1,0,0,0,144,141,1,0,0,
		0,144,142,1,0,0,0,144,143,1,0,0,0,145,21,1,0,0,0,146,147,5,11,0,0,147,
		151,5,41,0,0,148,150,3,36,18,0,149,148,1,0,0,0,150,153,1,0,0,0,151,149,
		1,0,0,0,151,152,1,0,0,0,152,154,1,0,0,0,153,151,1,0,0,0,154,158,5,32,0,
		0,155,157,3,20,10,0,156,155,1,0,0,0,157,160,1,0,0,0,158,156,1,0,0,0,158,
		159,1,0,0,0,159,161,1,0,0,0,160,158,1,0,0,0,161,162,5,11,0,0,162,163,5,
		38,0,0,163,164,5,41,0,0,164,175,5,32,0,0,165,166,5,11,0,0,166,170,5,41,
		0,0,167,169,3,36,18,0,168,167,1,0,0,0,169,172,1,0,0,0,170,168,1,0,0,0,
		170,171,1,0,0,0,171,173,1,0,0,0,172,170,1,0,0,0,173,175,5,34,0,0,174,146,
		1,0,0,0,174,165,1,0,0,0,175,23,1,0,0,0,176,177,5,11,0,0,177,178,5,36,0,
		0,178,182,5,41,0,0,179,181,3,36,18,0,180,179,1,0,0,0,181,184,1,0,0,0,182,
		180,1,0,0,0,182,183,1,0,0,0,183,185,1,0,0,0,184,182,1,0,0,0,185,186,5,
		37,0,0,186,187,5,32,0,0,187,25,1,0,0,0,188,189,5,17,0,0,189,27,1,0,0,0,
		190,191,5,16,0,0,191,29,1,0,0,0,192,193,5,15,0,0,193,31,1,0,0,0,194,195,
		5,14,0,0,195,33,1,0,0,0,196,197,7,0,0,0,197,35,1,0,0,0,198,199,5,41,0,
		0,199,200,5,39,0,0,200,201,5,40,0,0,201,37,1,0,0,0,202,203,7,1,0,0,203,
		39,1,0,0,0,23,41,45,48,53,59,66,76,85,92,98,100,105,110,114,119,124,130,
		144,151,158,170,174,182
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace OpenRewrite.Xml.Grammar
