//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/andrew/conductor/workspaces/rewrite/la-paz/rewrite-xml/src/main/antlr/XMLParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace OpenRewrite.Xml.Grammar {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IXMLParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class XMLParserBaseListener : IXMLParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.document"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDocument([NotNull] XMLParser.DocumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.document"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDocument([NotNull] XMLParser.DocumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.prolog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProlog([NotNull] XMLParser.PrologContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.prolog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProlog([NotNull] XMLParser.PrologContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.xmldecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterXmldecl([NotNull] XMLParser.XmldeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.xmldecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitXmldecl([NotNull] XMLParser.XmldeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.misc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMisc([NotNull] XMLParser.MiscContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.misc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMisc([NotNull] XMLParser.MiscContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.doctypedecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDoctypedecl([NotNull] XMLParser.DoctypedeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.doctypedecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDoctypedecl([NotNull] XMLParser.DoctypedeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.intsubset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntsubset([NotNull] XMLParser.IntsubsetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.intsubset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntsubset([NotNull] XMLParser.IntsubsetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.markupdecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMarkupdecl([NotNull] XMLParser.MarkupdeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.markupdecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMarkupdecl([NotNull] XMLParser.MarkupdeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.declSep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclSep([NotNull] XMLParser.DeclSepContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.declSep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclSep([NotNull] XMLParser.DeclSepContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.externalid"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExternalid([NotNull] XMLParser.ExternalidContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.externalid"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExternalid([NotNull] XMLParser.ExternalidContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.processinginstruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcessinginstruction([NotNull] XMLParser.ProcessinginstructionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.processinginstruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcessinginstruction([NotNull] XMLParser.ProcessinginstructionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContent([NotNull] XMLParser.ContentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContent([NotNull] XMLParser.ContentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElement([NotNull] XMLParser.ElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElement([NotNull] XMLParser.ElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.jspdirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJspdirective([NotNull] XMLParser.JspdirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.jspdirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJspdirective([NotNull] XMLParser.JspdirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.jspscriptlet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJspscriptlet([NotNull] XMLParser.JspscriptletContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.jspscriptlet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJspscriptlet([NotNull] XMLParser.JspscriptletContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.jspexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJspexpression([NotNull] XMLParser.JspexpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.jspexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJspexpression([NotNull] XMLParser.JspexpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.jspdeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJspdeclaration([NotNull] XMLParser.JspdeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.jspdeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJspdeclaration([NotNull] XMLParser.JspdeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.jspcomment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJspcomment([NotNull] XMLParser.JspcommentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.jspcomment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJspcomment([NotNull] XMLParser.JspcommentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.reference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReference([NotNull] XMLParser.ReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.reference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReference([NotNull] XMLParser.ReferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribute([NotNull] XMLParser.AttributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribute([NotNull] XMLParser.AttributeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.chardata"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChardata([NotNull] XMLParser.ChardataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.chardata"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChardata([NotNull] XMLParser.ChardataContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace OpenRewrite.Xml.Grammar
