/*
 * Copyright 2026 the original author or authors.
 * <p>
 * Licensed under the Moderne Source Available License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://docs.moderne.io/licensing/moderne-source-available-license
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/andrew/conductor/workspaces/rewrite/la-paz/rewrite-xml/src/main/antlr/XMLParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace OpenRewrite.Xml.Grammar {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="XMLParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IXMLParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="XMLParser.document"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDocument([NotNull] XMLParser.DocumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XMLParser.prolog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProlog([NotNull] XMLParser.PrologContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XMLParser.xmldecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitXmldecl([NotNull] XMLParser.XmldeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XMLParser.misc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMisc([NotNull] XMLParser.MiscContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XMLParser.doctypedecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoctypedecl([NotNull] XMLParser.DoctypedeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XMLParser.intsubset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntsubset([NotNull] XMLParser.IntsubsetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XMLParser.markupdecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMarkupdecl([NotNull] XMLParser.MarkupdeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XMLParser.declSep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclSep([NotNull] XMLParser.DeclSepContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XMLParser.externalid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExternalid([NotNull] XMLParser.ExternalidContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XMLParser.processinginstruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcessinginstruction([NotNull] XMLParser.ProcessinginstructionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XMLParser.content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContent([NotNull] XMLParser.ContentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XMLParser.element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElement([NotNull] XMLParser.ElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XMLParser.jspdirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJspdirective([NotNull] XMLParser.JspdirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XMLParser.jspscriptlet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJspscriptlet([NotNull] XMLParser.JspscriptletContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XMLParser.jspexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJspexpression([NotNull] XMLParser.JspexpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XMLParser.jspdeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJspdeclaration([NotNull] XMLParser.JspdeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XMLParser.jspcomment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJspcomment([NotNull] XMLParser.JspcommentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XMLParser.reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReference([NotNull] XMLParser.ReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XMLParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute([NotNull] XMLParser.AttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XMLParser.chardata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChardata([NotNull] XMLParser.ChardataContext context);
}
} // namespace OpenRewrite.Xml.Grammar
