/*
 * Copyright 2026 the original author or authors.
 * <p>
 * Licensed under the Moderne Source Available License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://docs.moderne.io/licensing/moderne-source-available-license
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/andrew/conductor/workspaces/rewrite/la-paz/rewrite-xml/src/main/antlr/XMLParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace OpenRewrite.Xml.Grammar {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="XMLParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IXMLParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.document"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDocument([NotNull] XMLParser.DocumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.document"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDocument([NotNull] XMLParser.DocumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.prolog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProlog([NotNull] XMLParser.PrologContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.prolog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProlog([NotNull] XMLParser.PrologContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.xmldecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterXmldecl([NotNull] XMLParser.XmldeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.xmldecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitXmldecl([NotNull] XMLParser.XmldeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.misc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMisc([NotNull] XMLParser.MiscContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.misc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMisc([NotNull] XMLParser.MiscContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.doctypedecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoctypedecl([NotNull] XMLParser.DoctypedeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.doctypedecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoctypedecl([NotNull] XMLParser.DoctypedeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.intsubset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntsubset([NotNull] XMLParser.IntsubsetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.intsubset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntsubset([NotNull] XMLParser.IntsubsetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.markupdecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMarkupdecl([NotNull] XMLParser.MarkupdeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.markupdecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMarkupdecl([NotNull] XMLParser.MarkupdeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.declSep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclSep([NotNull] XMLParser.DeclSepContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.declSep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclSep([NotNull] XMLParser.DeclSepContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.externalid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExternalid([NotNull] XMLParser.ExternalidContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.externalid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExternalid([NotNull] XMLParser.ExternalidContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.processinginstruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcessinginstruction([NotNull] XMLParser.ProcessinginstructionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.processinginstruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcessinginstruction([NotNull] XMLParser.ProcessinginstructionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContent([NotNull] XMLParser.ContentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContent([NotNull] XMLParser.ContentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElement([NotNull] XMLParser.ElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElement([NotNull] XMLParser.ElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.jspdirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJspdirective([NotNull] XMLParser.JspdirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.jspdirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJspdirective([NotNull] XMLParser.JspdirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.jspscriptlet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJspscriptlet([NotNull] XMLParser.JspscriptletContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.jspscriptlet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJspscriptlet([NotNull] XMLParser.JspscriptletContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.jspexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJspexpression([NotNull] XMLParser.JspexpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.jspexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJspexpression([NotNull] XMLParser.JspexpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.jspdeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJspdeclaration([NotNull] XMLParser.JspdeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.jspdeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJspdeclaration([NotNull] XMLParser.JspdeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.jspcomment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJspcomment([NotNull] XMLParser.JspcommentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.jspcomment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJspcomment([NotNull] XMLParser.JspcommentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReference([NotNull] XMLParser.ReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReference([NotNull] XMLParser.ReferenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribute([NotNull] XMLParser.AttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribute([NotNull] XMLParser.AttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XMLParser.chardata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChardata([NotNull] XMLParser.ChardataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XMLParser.chardata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChardata([NotNull] XMLParser.ChardataContext context);
}
} // namespace OpenRewrite.Xml.Grammar
