# Auto-generated stub file for IDE autocomplete support.
# Do not edit manually - regenerate with: python scripts/generate_stubs.py

from dataclasses import dataclass
from typing import Any, ClassVar, List, Optional, Dict
from typing_extensions import Self
from uuid import UUID
import weakref

from enum import Enum, auto
from rewrite import Marker

@dataclass(frozen=True)
class KeywordArguments(Marker):
    _id: UUID

    def replace(self, **kwargs: Any) -> Self: ...

    @property
    def id(self) -> UUID: ...

    def with_id(self, id_: UUID) -> 'KeywordArguments': ...

@dataclass(frozen=True)
class KeywordOnlyArguments(Marker):
    _id: UUID

    def replace(self, **kwargs: Any) -> Self: ...

    @property
    def id(self) -> UUID: ...

    def with_id(self, id_: UUID) -> 'KeywordOnlyArguments': ...

@dataclass(frozen=True)
class Quoted(Marker):
    class Style(Enum):
        SINGLE: Style
        DOUBLE: Style
        TRIPLE_SINGLE: Style
        TRIPLE_DOUBLE: Style
        BACKTICK: Style

    _id: UUID
    _style: Style

    def replace(self, **kwargs: Any) -> Self: ...

    @property
    def id(self) -> UUID: ...
    @property
    def style(self) -> Style: ...

    def with_id(self, id_: UUID) -> Quoted: ...
    def with_style(self, style: Style) -> Quoted: ...

@dataclass(frozen=True)
class SuppressNewline(Marker):
    _id: UUID

    def replace(self, **kwargs: Any) -> Self: ...

    @property
    def id(self) -> UUID: ...

    def with_id(self, id_: UUID) -> 'SuppressNewline': ...

@dataclass(frozen=True)
class LegacyNotEqual(Marker):
    _id: UUID

    def replace(self, **kwargs: Any) -> Self: ...

    @property
    def id(self) -> UUID: ...

    def with_id(self, id_: UUID) -> 'LegacyNotEqual': ...

@dataclass(frozen=True)
class RaiseTuple(Marker):
    _id: UUID

    def replace(self, **kwargs: Any) -> Self: ...

    @property
    def id(self) -> UUID: ...

    def with_id(self, id_: UUID) -> 'RaiseTuple': ...

@dataclass(frozen=True)
class TupleExceptClause(Marker):
    _id: UUID

    def replace(self, **kwargs: Any) -> Self: ...

    @property
    def id(self) -> UUID: ...

    def with_id(self, id_: UUID) -> 'TupleExceptClause': ...

@dataclass(frozen=True)
class PrintSyntax(Marker):
    _id: UUID
    _has_destination: bool
    _trailing_comma: bool

    def replace(self, **kwargs: Any) -> Self: ...

    @property
    def id(self) -> UUID: ...
    @property
    def has_destination(self) -> bool: ...
    @property
    def trailing_comma(self) -> bool: ...

    def with_id(self, id_: UUID) -> 'PrintSyntax': ...
    def with_has_destination(self, has_destination: bool) -> 'PrintSyntax': ...
    def with_trailing_comma(self, trailing_comma: bool) -> 'PrintSyntax': ...

@dataclass(frozen=True)
class ExecSyntax(Marker):
    _id: UUID

    def replace(self, **kwargs: Any) -> Self: ...

    @property
    def id(self) -> UUID: ...

    def with_id(self, id_: UUID) -> 'ExecSyntax': ...

@dataclass(frozen=True)
class PythonResolutionResult(Marker):
    class PackageManager(Enum):
        Uv: PackageManager
        Pip: PackageManager
        Pipenv: PackageManager
        Poetry: PackageManager
        Pdm: PackageManager

    @dataclass(frozen=True)
    class SourceIndex:
        _name: str
        _url: str
        _default_index: bool

        def replace(self, **kwargs: Any) -> Self: ...

        @property
        def name(self) -> str: ...
        @property
        def url(self) -> str: ...
        @property
        def default_index(self) -> bool: ...

        def with_name(self, name: str) -> PythonResolutionResult.SourceIndex: ...
        def with_url(self, url: str) -> PythonResolutionResult.SourceIndex: ...
        def with_default_index(self, default_index: bool) -> PythonResolutionResult.SourceIndex: ...

    @dataclass(frozen=True)
    class ResolvedDependency:
        _name: str
        _version: str
        _source: Optional[str]
        _dependencies: Optional[List[PythonResolutionResult.ResolvedDependency]]

        def replace(self, **kwargs: Any) -> Self: ...

        @property
        def name(self) -> str: ...
        @property
        def version(self) -> str: ...
        @property
        def source(self) -> Optional[str]: ...
        @property
        def dependencies(self) -> Optional[List[PythonResolutionResult.ResolvedDependency]]: ...

        def with_name(self, name: str) -> PythonResolutionResult.ResolvedDependency: ...
        def with_version(self, version: str) -> PythonResolutionResult.ResolvedDependency: ...
        def with_source(self, source: Optional[str]) -> PythonResolutionResult.ResolvedDependency: ...
        def with_dependencies(self, dependencies: Optional[List[PythonResolutionResult.ResolvedDependency]]) -> PythonResolutionResult.ResolvedDependency: ...

    @dataclass(frozen=True)
    class Dependency:
        _name: str
        _version_constraint: Optional[str]
        _extras: Optional[List[str]]
        _marker: Optional[str]
        _resolved: Optional[PythonResolutionResult.ResolvedDependency]

        def replace(self, **kwargs: Any) -> Self: ...

        @property
        def name(self) -> str: ...
        @property
        def version_constraint(self) -> Optional[str]: ...
        @property
        def extras(self) -> Optional[List[str]]: ...
        @property
        def marker(self) -> Optional[str]: ...
        @property
        def resolved(self) -> Optional[PythonResolutionResult.ResolvedDependency]: ...

        def with_name(self, name: str) -> PythonResolutionResult.Dependency: ...
        def with_version_constraint(self, version_constraint: Optional[str]) -> PythonResolutionResult.Dependency: ...
        def with_extras(self, extras: Optional[List[str]]) -> PythonResolutionResult.Dependency: ...
        def with_marker(self, marker: Optional[str]) -> PythonResolutionResult.Dependency: ...
        def with_resolved(self, resolved: Optional[PythonResolutionResult.ResolvedDependency]) -> PythonResolutionResult.Dependency: ...

    _id: UUID
    _name: Optional[str]
    _version: Optional[str]
    _description: Optional[str]
    _license: Optional[str]
    _path: str
    _requires_python: Optional[str]
    _build_backend: Optional[str]
    _build_requires: List[Dependency]
    _dependencies: List[Dependency]
    _optional_dependencies: Dict[str, List]
    _dependency_groups: Dict[str, List]
    _constraint_dependencies: List[Dependency]
    _override_dependencies: List[Dependency]
    _resolved_dependencies: List[ResolvedDependency]
    _package_manager: Optional[PackageManager]
    _source_indexes: Optional[List[SourceIndex]]

    def replace(self, **kwargs: Any) -> Self: ...

    @property
    def id(self) -> UUID: ...
    @property
    def name(self) -> Optional[str]: ...
    @property
    def version(self) -> Optional[str]: ...
    @property
    def description(self) -> Optional[str]: ...
    @property
    def license(self) -> Optional[str]: ...
    @property
    def path(self) -> str: ...
    @property
    def requires_python(self) -> Optional[str]: ...
    @property
    def build_backend(self) -> Optional[str]: ...
    @property
    def build_requires(self) -> List[Dependency]: ...
    @property
    def dependencies(self) -> List[Dependency]: ...
    @property
    def optional_dependencies(self) -> Dict[str, List]: ...
    @property
    def dependency_groups(self) -> Dict[str, List]: ...
    @property
    def constraint_dependencies(self) -> List[Dependency]: ...
    @property
    def override_dependencies(self) -> List[Dependency]: ...
    @property
    def resolved_dependencies(self) -> List[ResolvedDependency]: ...
    @property
    def package_manager(self) -> Optional[PackageManager]: ...
    @property
    def source_indexes(self) -> Optional[List[SourceIndex]]: ...

    def with_id(self, id_: UUID) -> PythonResolutionResult: ...
    def with_name(self, name: Optional[str]) -> PythonResolutionResult: ...
    def with_version(self, version: Optional[str]) -> PythonResolutionResult: ...
    def with_description(self, description: Optional[str]) -> PythonResolutionResult: ...
    def with_license(self, license: Optional[str]) -> PythonResolutionResult: ...
    def with_path(self, path: str) -> PythonResolutionResult: ...
    def with_requires_python(self, requires_python: Optional[str]) -> PythonResolutionResult: ...
    def with_build_backend(self, build_backend: Optional[str]) -> PythonResolutionResult: ...
    def with_build_requires(self, build_requires: List[Dependency]) -> PythonResolutionResult: ...
    def with_dependencies(self, dependencies: List[Dependency]) -> PythonResolutionResult: ...
    def with_optional_dependencies(self, optional_dependencies: Dict[str, List]) -> PythonResolutionResult: ...
    def with_dependency_groups(self, dependency_groups: Dict[str, List]) -> PythonResolutionResult: ...
    def with_constraint_dependencies(self, constraint_dependencies: List[Dependency]) -> PythonResolutionResult: ...
    def with_override_dependencies(self, override_dependencies: List[Dependency]) -> PythonResolutionResult: ...
    def with_resolved_dependencies(self, resolved_dependencies: List[ResolvedDependency]) -> PythonResolutionResult: ...
    def with_package_manager(self, package_manager: Optional[PackageManager]) -> PythonResolutionResult: ...
    def with_source_indexes(self, source_indexes: Optional[List[SourceIndex]]) -> PythonResolutionResult: ...
