/*
 * Copyright 2026 the original author or authors.
 * <p>
 * Licensed under the Moderne Source Available License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://docs.moderne.io/licensing/moderne-source-available-license
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openrewrite.javascript.internal.lock;

import org.jspecify.annotations.Nullable;
import org.junit.jupiter.api.Test;
import org.openrewrite.javascript.internal.lock.LockEditSet.PackageEdit;
import org.openrewrite.javascript.internal.registry.VersionManifest;

import java.util.*;

import static java.util.Collections.emptyMap;
import static java.util.Collections.singletonMap;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatExceptionOfType;

/**
 * Unit tests for the graph-to-yarn.lock diff's decisions, driven by an in-memory {@link Registry}. The
 * end-to-end byte contract lives in {@code YarnClassicResolveAndPatchLockRegenTest}; these pin the decisions
 * themselves — which block is untouched, which merges a selector, which moves in place, and which shapes defer.
 */
class YarnClassicLockDiffTest {

    private static final String HEADER =
            "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n";

    @Test
    void untouchedClosureEmitsNoEdits() {
        FakeRegistry registry = new FakeRegistry()
                .add("a", "1.2.0", singletonMap("b", "^2.0.0"))
                .add("b", "2.3.0", emptyMap());
        String lock = HEADER +
                "a@^1.0.0:\n" +
                "  version \"1.2.0\"\n" +
                "  resolved \"https://registry.yarnpkg.com/a/-/a-1.2.0.tgz#sha1-a-1.2.0\"\n" +
                "  integrity sha512-a-1.2.0\n" +
                "  dependencies:\n" +
                "    b \"^2.0.0\"\n" +
                "\n" +
                "b@^2.0.0:\n" +
                "  version \"2.3.0\"\n" +
                "  resolved \"https://registry.yarnpkg.com/b/-/b-2.3.0.tgz#sha1-b-2.3.0\"\n" +
                "  integrity sha512-b-2.3.0\n";

        assertThat(diff(registry, app(singletonMap("a", "^1.0.0")), lock)).isEmpty();
    }

    @Test
    void gainedSelectorMergesIntoTheExistingBlock() {
        // The root newly declares n@1.0.0, which resolves to the version p already required at ^1.0.0: yarn
        // merges the new selector into the existing block's header rather than adding a block.
        FakeRegistry registry = new FakeRegistry()
                .add("n", "1.0.0", emptyMap())
                .add("p", "1.0.0", singletonMap("n", "^1.0.0"));
        Map<String, String> deps = new LinkedHashMap<>();
        deps.put("n", "1.0.0");
        deps.put("p", "^1.0.0");
        String lock = HEADER +
                "n@^1.0.0:\n" +
                "  version \"1.0.0\"\n" +
                "  resolved \"https://registry.yarnpkg.com/n/-/n-1.0.0.tgz#sha1-n-1.0.0\"\n" +
                "  integrity sha512-n-1.0.0\n" +
                "\n" +
                "p@^1.0.0:\n" +
                "  version \"1.0.0\"\n" +
                "  resolved \"https://registry.yarnpkg.com/p/-/p-1.0.0.tgz#sha1-p-1.0.0\"\n" +
                "  integrity sha512-p-1.0.0\n" +
                "  dependencies:\n" +
                "    n \"^1.0.0\"\n";

        List<PackageEdit> edits = diff(registry, app(deps), lock);
        assertThat(edits).hasSize(1);
        assertThat(edits.get(0).getKind()).isEqualTo(PackageEdit.Kind.PROMOTION);
        assertThat(edits.get(0).getName()).isEqualTo("n");
        assertThat(edits.get(0).getNewConstraint()).isEqualTo("1.0.0");
    }

    @Test
    void directlyDeclaredForkAddsSecondFlatBlock() {
        // The lock already resolves shared@1.0.0 for parent; pinning shared@2.0.0 at the root forks — yarn
        // keeps both flat blocks, so the diff is a single fresh add beside the untouched member.
        FakeRegistry registry = new FakeRegistry()
                .add("parent", "1.0.0", singletonMap("shared", "1.0.0"))
                .add("shared", "1.0.0", emptyMap())
                .add("shared", "2.0.0", emptyMap());
        Map<String, String> deps = new LinkedHashMap<>();
        deps.put("parent", "^1.0.0");
        deps.put("shared", "2.0.0");
        String lock = HEADER +
                "parent@^1.0.0:\n" +
                "  version \"1.0.0\"\n" +
                "  resolved \"https://registry.yarnpkg.com/parent/-/parent-1.0.0.tgz#sha1-parent-1.0.0\"\n" +
                "  integrity sha512-parent-1.0.0\n" +
                "  dependencies:\n" +
                "    shared \"1.0.0\"\n" +
                "\n" +
                "shared@1.0.0:\n" +
                "  version \"1.0.0\"\n" +
                "  resolved \"https://registry.yarnpkg.com/shared/-/shared-1.0.0.tgz#sha1-shared-1.0.0\"\n" +
                "  integrity sha512-shared-1.0.0\n";

        List<PackageEdit> edits = diff(registry, app(deps), lock);
        assertThat(edits).hasSize(1);
        assertThat(edits.get(0).getKind()).isEqualTo(PackageEdit.Kind.ADD);
        assertThat(edits.get(0).getName()).isEqualTo("shared");
        assertThat(edits.get(0).getNewVersion()).isEqualTo("2.0.0");
    }

    @Test
    void satisfiedPeerClosureAddsOnePlainBlock() {
        // has-peer's react peer is satisfied by the installed react; yarn v1 records no peer surface, so the
        // fresh block is plain and the react block is untouched.
        FakeRegistry registry = new FakeRegistry()
                .addWithPeers("has-peer", "1.0.0", emptyMap(), singletonMap("react", ">=17"))
                .add("react", "18.2.0", emptyMap());
        Map<String, String> deps = new LinkedHashMap<>();
        deps.put("has-peer", "^1.0.0");
        deps.put("react", "^18.0.0");
        String lock = HEADER +
                "react@^18.0.0:\n" +
                "  version \"18.2.0\"\n" +
                "  resolved \"https://registry.yarnpkg.com/react/-/react-18.2.0.tgz#sha1-react-18.2.0\"\n" +
                "  integrity sha512-react-18.2.0\n";

        List<PackageEdit> edits = diff(registry, app(deps), lock);
        assertThat(edits).hasSize(1);
        assertThat(edits.get(0).getKind()).isEqualTo(PackageEdit.Kind.ADD);
        assertThat(edits.get(0).getName()).isEqualTo("has-peer");
        assertThat(edits.get(0).getMetadata()).isNull();
        assertThat(edits.get(0).getNewDependencies()).isNull();
    }

    @Test
    void rootDeclaredMoveIsAnInPlaceBump() {
        FakeRegistry registry = new FakeRegistry()
                .add("a", "1.0.0", emptyMap())
                .add("a", "1.5.0", emptyMap());
        String lock = HEADER +
                "a@^1.0.0:\n" +
                "  version \"1.0.0\"\n" +
                "  resolved \"https://registry.yarnpkg.com/a/-/a-1.0.0.tgz#sha1-a-1.0.0\"\n" +
                "  integrity sha512-a-1.0.0\n";

        List<PackageEdit> edits = diff(registry, app(singletonMap("a", "^1.0.0")), lock);
        assertThat(edits).hasSize(1);
        assertThat(edits.get(0).getKind()).isEqualTo(PackageEdit.Kind.BUMP);
        assertThat(edits.get(0).getOldConstraint()).isEqualTo("^1.0.0");
        assertThat(edits.get(0).getNewVersion()).isEqualTo("1.5.0");
    }

    @Test
    void transitiveMoveIsAForcedMove() {
        FakeRegistry registry = new FakeRegistry()
                .add("a", "1.0.0", singletonMap("b", "^1.0.0"))
                .add("b", "1.0.0", emptyMap())
                .add("b", "1.2.0", emptyMap());
        String lock = HEADER +
                "a@^1.0.0:\n" +
                "  version \"1.0.0\"\n" +
                "  resolved \"https://registry.yarnpkg.com/a/-/a-1.0.0.tgz#sha1-a-1.0.0\"\n" +
                "  integrity sha512-a-1.0.0\n" +
                "  dependencies:\n" +
                "    b \"^1.0.0\"\n" +
                "\n" +
                "b@^1.0.0:\n" +
                "  version \"1.0.0\"\n" +
                "  resolved \"https://registry.yarnpkg.com/b/-/b-1.0.0.tgz#sha1-b-1.0.0\"\n" +
                "  integrity sha512-b-1.0.0\n";

        List<PackageEdit> edits = diff(registry, app(singletonMap("a", "^1.0.0")), lock);
        assertThat(edits).hasSize(1);
        assertThat(edits.get(0).getKind()).isEqualTo(PackageEdit.Kind.FORCED_MOVE);
        assertThat(edits.get(0).getName()).isEqualTo("b");
        assertThat(edits.get(0).getNewVersion()).isEqualTo("1.2.0");
        assertThat(edits.get(0).getNewConstraint()).isEqualTo("^1.0.0");
    }

    @Test
    void undeclaredLeftoverBlockIsARemoval() {
        FakeRegistry registry = new FakeRegistry();
        String lock = HEADER +
                "ms@^2.1.3:\n" +
                "  version \"2.1.3\"\n" +
                "  resolved \"https://registry.yarnpkg.com/ms/-/ms-2.1.3.tgz#sha1-ms-2.1.3\"\n" +
                "  integrity sha512-ms-2.1.3\n";

        List<PackageEdit> edits = diff(registry, "{\"name\":\"app\",\"version\":\"1.0.0\"}", lock);
        assertThat(edits).hasSize(1);
        assertThat(edits.get(0).getName()).isEqualTo("ms");
        assertThat(edits.get(0).getNewVersion()).isNull();
        assertThat(edits.get(0).getOldConstraint()).isEqualTo("^2.1.3");
    }

    @Test
    void mergedHeaderThatMustDropASelectorDefers() {
        // The block serves n@1.0.0 and n@^1.0.0; the edit drops the exact pin, so the header must split, which
        // the patcher cannot do byte-exact.
        FakeRegistry registry = new FakeRegistry().add("n", "1.0.0", emptyMap());
        String lock = HEADER +
                "n@1.0.0, n@^1.0.0:\n" +
                "  version \"1.0.0\"\n" +
                "  resolved \"https://registry.yarnpkg.com/n/-/n-1.0.0.tgz#sha1-n-1.0.0\"\n" +
                "  integrity sha512-n-1.0.0\n";

        assertThatExceptionOfType(EngineFailure.class)
                .isThrownBy(() -> diff(registry, app(singletonMap("n", "^1.0.0")), lock))
                .withMessageContaining("merged header");
    }

    @Test
    void freshForkBesideADeclaredMemberDefers() {
        // b forks fresh: the root declares ^1.0.0 and c needs ^2.0.0, both new. The patcher would fold the
        // declared range into the transitive member's header, so the shape defers.
        FakeRegistry registry = new FakeRegistry()
                .add("c", "1.0.0", singletonMap("b", "^2.0.0"))
                .add("b", "1.9.0", emptyMap())
                .add("b", "2.0.0", emptyMap());
        Map<String, String> deps = new LinkedHashMap<>();
        deps.put("b", "^1.0.0");
        deps.put("c", "^1.0.0");

        assertThatExceptionOfType(EngineFailure.class)
                .isThrownBy(() -> diff(registry, app(deps), HEADER))
                .withMessageContaining("header cannot be derived");
    }

    @Test
    void optionalDependenciesDeclaringAddDefers() {
        // A resolved package whose own manifest declares optionalDependencies gets a block shape that is not
        // yet byte-verified (an importer's optionalDependencies are ordinary unmarked entries and resolve fine).
        FakeRegistry registry = new FakeRegistry()
                .addWithOptional("opt", "1.0.0", emptyMap(), singletonMap("fsevents", "^2.0.0"))
                .add("fsevents", "2.3.0", emptyMap());

        assertThatExceptionOfType(EngineFailure.class)
                .isThrownBy(() -> diff(registry, app(singletonMap("opt", "^1.0.0")), HEADER))
                .withMessageContaining("optionalDependencies");
    }

    @Test
    void missingLocatorDefers() {
        VersionManifest noDist = vm("a", "1.0.0", emptyMap(), null, null, null);
        ResolutionGraph graph = new ResolutionGraph(
                Collections.singletonList(new ResolutionGraph.Importer("", "app", "1.0.0",
                        singletonMap("dependencies", singletonMap("a", "^1.0.0")), singletonMap("a", "1.0.0"))),
                singletonMap("a@1.0.0", new ResolvedNode(noDist, emptyMap())));
        assertThatExceptionOfType(EngineFailure.class)
                .isThrownBy(() -> YarnClassicLockDiff.diff(graph, HEADER))
                .withMessageContaining("registry locator");
    }

    @Test
    void workspaceImporterDefers() {
        ResolutionGraph graph = new ResolutionGraph(
                Collections.singletonList(new ResolutionGraph.Importer("packages/app", "app", "1.0.0",
                        emptyMap(), emptyMap())),
                emptyMap());
        assertThatExceptionOfType(EngineFailure.class)
                .isThrownBy(() -> YarnClassicLockDiff.diff(graph, HEADER))
                .withMessageContaining("single root importer");
    }

    // --- in-memory registry + manifest builders ---------------------------

    private static List<PackageEdit> diff(Registry registry, String manifest, String lock) {
        return YarnClassicLockDiff.diff(new NpmGraphBuilder(registry).build(singletonMap("", manifest)), lock);
    }

    private static String app(Map<String, String> dependencies) {
        StringBuilder deps = new StringBuilder();
        for (Map.Entry<String, String> e : dependencies.entrySet()) {
            if (deps.length() > 0) {
                deps.append(',');
            }
            deps.append('"').append(e.getKey()).append("\":\"").append(e.getValue()).append('"');
        }
        return "{\"name\":\"app\",\"version\":\"1.0.0\",\"dependencies\":{" + deps + "}}";
    }

    private static VersionManifest vm(String name, String version, Map<String, String> deps,
                                      @Nullable Map<String, String> optional, @Nullable Map<String, String> peers,
                                      VersionManifest.@Nullable Dist dist) {
        return new VersionManifest(name, version, null, null, deps.isEmpty() ? null : deps, optional, peers, null,
                null, null, null, null, null, null, null, null, null, null, dist, null, null, null);
    }

    private static final class FakeRegistry implements Registry {
        final Map<String, Set<String>> versionsByName = new HashMap<>();
        final Map<String, VersionManifest> manifests = new HashMap<>();

        FakeRegistry add(String name, String version, Map<String, String> deps) {
            return put(name, version, deps, null, null);
        }

        FakeRegistry addWithPeers(String name, String version, Map<String, String> deps, Map<String, String> peers) {
            return put(name, version, deps, null, peers);
        }

        FakeRegistry addWithOptional(String name, String version, Map<String, String> deps,
                                     Map<String, String> optional) {
            return put(name, version, deps, optional, null);
        }

        private FakeRegistry put(String name, String version, Map<String, String> deps,
                                 @Nullable Map<String, String> optional, @Nullable Map<String, String> peers) {
            versionsByName.computeIfAbsent(name, k -> new TreeSet<>()).add(version);
            VersionManifest.Dist dist = new VersionManifest.Dist(
                    "https://registry.npmjs.org/" + name + "/-/" + name + "-" + version + ".tgz",
                    "sha1-" + name + "-" + version, "sha512-" + name + "-" + version);
            manifests.put(name + "@" + version, vm(name, version, deps, optional, peers, dist));
            return this;
        }

        @Override
        public Set<String> versions(String name) {
            return versionsByName.getOrDefault(name, Collections.emptySet());
        }

        @Override
        public VersionManifest manifest(String name, String version) {
            return manifests.get(name + "@" + version);
        }
    }
}
