/*
 * Copyright 2026 the original author or authors.
 * <p>
 * Licensed under the Moderne Source Available License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://docs.moderne.io/licensing/moderne-source-available-license
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openrewrite.python.internal;

import org.junit.jupiter.api.Test;
import org.openrewrite.python.marker.PythonResolutionResult.ResolvedDependency;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class PdmLockParserTest {

    @Test
    void linksTransitiveDependenciesDeeply() {
        String lock = """
          # This file is @generated by PDM.
          # It is not intended for manual editing.

          [metadata]
          groups = ["default"]
          strategy = ["inherit_metadata"]
          lock_version = "4.5.0"
          content_hash = "sha256:0000000000000000000000000000000000000000000000000000000000000000"

          [[metadata.targets]]
          requires_python = ">=3.10"

          [[package]]
          name = "a"
          version = "1.0.0"
          requires_python = ">=3.10"
          summary = ""
          groups = ["default"]
          dependencies = [
              "b>=1.0",
          ]
          files = [
              {file = "a-1.0.0.tar.gz", hash = "sha256:0000000000000000000000000000000000000000000000000000000000000000"},
          ]

          [[package]]
          name = "b"
          version = "1.0.0"
          requires_python = ">=3.10"
          summary = ""
          groups = ["default"]
          dependencies = [
              "c>=1.0",
          ]
          files = [
              {file = "b-1.0.0.tar.gz", hash = "sha256:0000000000000000000000000000000000000000000000000000000000000000"},
          ]

          [[package]]
          name = "c"
          version = "1.0.0"
          requires_python = ">=3.10"
          summary = ""
          groups = ["default"]
          files = [
              {file = "c-1.0.0.tar.gz", hash = "sha256:0000000000000000000000000000000000000000000000000000000000000000"},
          ]
          """;

        List<ResolvedDependency> resolved = PdmLockParser.parse(lock);

        assertThat(resolved).hasSize(3);
        ResolvedDependency a = resolved.get(0);
        ResolvedDependency b = resolved.get(1);
        ResolvedDependency c = resolved.get(2);
        // Children must be the graph's own instances, so navigation via
        // getDependencies() works at arbitrary depth.
        assertThat(a.getDependencies().get(0)).isSameAs(b);
        assertThat(b.getDependencies().get(0)).isSameAs(c);
        assertThat(a.getDependencies().get(0).getDependencies().get(0)).isSameAs(c);
    }
}
