/*
 * Copyright 2026 the original author or authors.
 * <p>
 * Licensed under the Moderne Source Available License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://docs.moderne.io/licensing/moderne-source-available-license
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openrewrite.python.internal;

import org.junit.jupiter.api.Test;
import org.openrewrite.python.marker.PythonResolutionResult.ResolvedDependency;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class PoetryLockParserTest {

    @Test
    void linksTransitiveDependenciesDeeply() {
        String lock = """
          # This file is automatically @generated by Poetry 2.4.1 and should not be changed by hand.

          [[package]]
          name = "a"
          version = "1.0.0"
          description = ""
          optional = false
          python-versions = ">=3.10"
          groups = ["main"]
          files = [
              {file = "a-1.0.0.tar.gz", hash = "sha256:0000000000000000000000000000000000000000000000000000000000000000"},
          ]

          [package.dependencies]
          b = ">=1.0"

          [[package]]
          name = "b"
          version = "1.0.0"
          description = ""
          optional = false
          python-versions = ">=3.10"
          groups = ["main"]
          files = [
              {file = "b-1.0.0.tar.gz", hash = "sha256:0000000000000000000000000000000000000000000000000000000000000000"},
          ]

          [package.dependencies]
          c = ">=1.0"

          [[package]]
          name = "c"
          version = "1.0.0"
          description = ""
          optional = false
          python-versions = ">=3.10"
          groups = ["main"]
          files = [
              {file = "c-1.0.0.tar.gz", hash = "sha256:0000000000000000000000000000000000000000000000000000000000000000"},
          ]

          [metadata]
          lock-version = "2.1"
          python-versions = ">=3.10"
          content-hash = "0000000000000000000000000000000000000000000000000000000000000000"
          """;

        List<ResolvedDependency> resolved = PoetryLockParser.parse(lock);

        assertThat(resolved).hasSize(3);
        ResolvedDependency a = resolved.get(0);
        ResolvedDependency b = resolved.get(1);
        ResolvedDependency c = resolved.get(2);
        // Children must be the graph's own instances, so navigation via
        // getDependencies() works at arbitrary depth.
        assertThat(a.getDependencies().get(0)).isSameAs(b);
        assertThat(b.getDependencies().get(0)).isSameAs(c);
        assertThat(a.getDependencies().get(0).getDependencies().get(0)).isSameAs(c);
    }
}
