/*
 * Copyright 2026 the original author or authors.
 * <p>
 * Licensed under the Moderne Source Available License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://docs.moderne.io/licensing/moderne-source-available-license
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openrewrite.javascript.internal.lock;

/**
 * The byte-exact classic {@code yarn.lock} (v1) serialization primitives used by {@link YarnClassicLockPatcher}.
 * yarn's own {@code _stringify} orders keys by {@link #sortAlpha} and quotes only the tokens {@code shouldWrapKey}
 * demands; the tarball host is mirrored to the configured registry.
 */
public final class YarnLock {

    /** The exact bytes every yarn v1 lock opens with, up to the first block. */
    public static final String HEADER =
            "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n";

    public static final String NPM_REGISTRY = "https://registry.npmjs.org/";
    public static final String YARN_REGISTRY = "https://registry.yarnpkg.com/";

    private YarnLock() {
    }

    /** yarn's {@code sortAlpha}: char-by-char, then by length (identical to {@link String#compareTo}, kept explicit). */
    public static int sortAlpha(String a, String b) {
        int shortLen = Math.min(a.length(), b.length());
        for (int i = 0; i < shortLen; i++) {
            int diff = a.charAt(i) - b.charAt(i);
            if (diff != 0) {
                return diff;
            }
        }
        return a.length() - b.length();
    }

    /** Quote a key/value iff yarn's {@code shouldWrapKey} would; otherwise emit it bare. */
    public static String maybeWrap(String s) {
        return shouldWrapKey(s) ? jsonQuote(s) : s;
    }

    private static boolean shouldWrapKey(String s) {
        if (s.startsWith("true") || s.startsWith("false")) {
            return true;
        }
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (c == ':' || c == '\n' || c == '\\' || c == '"' || c == ',' || c == '[' || c == ']' || Character.isWhitespace(c)) {
                return true;
            }
        }
        if (s.isEmpty()) {
            return true;
        }
        char c0 = s.charAt(0);
        if (c0 >= '0' && c0 <= '9') {
            return true;
        }
        return !((c0 >= 'a' && c0 <= 'z') || (c0 >= 'A' && c0 <= 'Z'));
    }

    private static String jsonQuote(String s) {
        StringBuilder b = new StringBuilder("\"");
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (c == '"' || c == '\\') {
                b.append('\\');
            }
            b.append(c);
        }
        return b.append('"').toString();
    }

    public static String unwrap(String token) {
        if (token.length() >= 2 && token.charAt(0) == '"' && token.charAt(token.length() - 1) == '"') {
            return token.substring(1, token.length() - 1).replace("\\\"", "\"").replace("\\\\", "\\");
        }
        return token;
    }

    /** Rewrite a registry tarball URL's host to the yarnpkg mirror when the sibling entries use it. */
    public static String mirrorHost(String url, boolean mirrorToYarnpkg) {
        return mirrorToYarnpkg && url.startsWith(NPM_REGISTRY)
                ? YARN_REGISTRY + url.substring(NPM_REGISTRY.length())
                : url;
    }
}
