include(
        "rewrite-core",
        "rewrite-java",
        "rewrite-java-11",
        "rewrite-maven",
        "rewrite-properties",
        "rewrite-xml",
        "rewrite-yaml",
        "rewrite-test"
)
