/*
 * Copyright 2022 the original author or authors.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openrewrite.xml.format

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test
import org.openrewrite.Issue
import org.openrewrite.xml.XmlParser
import org.openrewrite.xml.style.Autodetect
import org.openrewrite.xml.style.TabsAndIndentsStyle

class AutoDetectTest  {

    @Test
    fun autoDetectSimple() {
        val pom = XmlParser().parse(
            """
            <project>
              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                  <exclusions>
                    <exclusion>
                      <groupId>org.junit.vintage</groupId>
                      <artifactId>junit-vintage-engine</artifactId>
                    </exclusion>
                  </exclusions>
                </dependency>
              </dependencies>
            </project>
        """.trimIndent())
        val autodetect = Autodetect.detect(pom)
        val tabsAndIndents: TabsAndIndentsStyle =
            autodetect.styles.stream().filter(TabsAndIndentsStyle::class::isInstance).findFirst().get() as TabsAndIndentsStyle
        assertThat(tabsAndIndents.tabSize).isEqualTo(1)
        assertThat(tabsAndIndents.indentSize).isEqualTo(2)
        assertThat(tabsAndIndents.useTabCharacter).isFalse
    }

    @Disabled
    @Issue("https://github.com/openrewrite/rewrite/issues/1498")
    @Test
    fun autoDetectQuarkus() {
        val pom = XmlParser().parse(
            """
                <project xmlns="http://maven.apache.org/POM/4.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
                    <modelVersion>4.0.0</modelVersion>
                    <parent>
                        <groupId>io.quarkus</groupId>
                        <artifactId>quarkus-bootstrap-parent</artifactId>
                        <version>999-SNAPSHOT</version>
                    </parent>
                    <artifactId>quarkus-bootstrap-bom</artifactId>
                    <name>Quarkus - Bootstrap - BOM</name>
                    <packaging>pom</packaging>
                    <dependencyManagement>
                        <dependencies>
                            <dependency>
                                <groupId>com.google.guava</groupId>
                                <artifactId>guava</artifactId>
                                <version>1.0.0</version>
                                <exclusions>
                                    <exclusion>
                                        <groupId>com.google.code.findbugs</groupId>
                                        <artifactId>jsr305</artifactId>
                                    </exclusion>
                                    <exclusion>
                                        <groupId>com.google.guava</groupId>
                                        <artifactId>listenablefuture</artifactId>
                                    </exclusion>
                                </exclusions>
                            </dependency>
                            <dependency>
                                <groupId>com.google.guava</groupId>
                                <artifactId>failureaccess</artifactId>
                                <version>1.0.0</version>
                            </dependency>
                            <dependency>
                                <groupId>org.apache.commons</groupId>
                                <artifactId>commons-lang3</artifactId>
                                <version>1.0.0</version>
                            </dependency>
                            <dependency>
                                <groupId>io.quarkus</groupId>
                                <artifactId>quarkus-bootstrap-core</artifactId>
                                <version>1.0.0</version>
                            </dependency>
                            <dependency>
                                <groupId>io.quarkus</groupId>
                                <artifactId>quarkus-bootstrap-app-model</artifactId>
                                <version>1.0.0</version>
                            </dependency>
                            <dependency>
                                <groupId>io.quarkus</groupId>
                                <artifactId>quarkus-bootstrap-runner</artifactId>
                                <version>1.0.0</version>
                            </dependency>
                            <dependency>
                                <groupId>io.quarkus</groupId>
                                <artifactId>quarkus-bootstrap-maven-resolver</artifactId>
                                <version>1.0.0</version>
                            </dependency>
                            <dependency>
                                <groupId>io.quarkus</groupId>
                                <artifactId>quarkus-bootstrap-gradle-resolver</artifactId>
                                <version>1.0.0</version>
                            </dependency>
                            <dependency>
                                <groupId>io.quarkus</groupId>
                                <artifactId>quarkus-fs-util</artifactId>
                                <version>1.0.0</version>
                            </dependency>
                            <dependency>
                                <groupId>org.apache.maven</groupId>
                                <artifactId>maven-plugin-api</artifactId>
                                <version>1.0.0</version>
                                <exclusions>
                                    <exclusion>
                                        <groupId>javax.annotation</groupId>
                                        <artifactId>javax.annotation-api</artifactId>
                                    </exclusion>
                                    <exclusion>
                                        <groupId>javax.inject</groupId>
                                        <artifactId>javax.inject</artifactId>
                                    </exclusion>
                                </exclusions>
                            </dependency>
                            <dependency>
                                <groupId>org.apache.maven</groupId>
                                <artifactId>maven-model</artifactId>
                                <version>1.0.0</version>
                            </dependency>
                            <dependency>
                                <groupId>org.apache.maven</groupId>
                                <artifactId>maven-core</artifactId>
                                <version>1.0.0</version>
                                <exclusions>
                                    <exclusion>
                                        <groupId>javax.inject</groupId>
                                        <artifactId>javax.inject</artifactId>
                                    </exclusion>
                                    <exclusion>
                                        <groupId>org.checkerframework</groupId>
                                        <artifactId>checker-qual</artifactId>
                                    </exclusion>
                                    <exclusion>
                                        <groupId>org.slf4j</groupId>
                                        <artifactId>slf4j-api</artifactId>
                                    </exclusion>
                                </exclusions>
                            </dependency>
                            <dependency>
                                <groupId>org.apache.maven</groupId>
                                <artifactId>maven-embedder</artifactId>
                                <version>1.0.0</version>
                                <exclusions>
                                    <exclusion>
                                        <groupId>org.sonatype.plexus</groupId>
                                        <artifactId>plexus-sec-dispatcher</artifactId>
                                    </exclusion>
                                    <exclusion>
                                        <groupId>org.sonatype.plexus</groupId>
                                        <artifactId>plexus-cipher</artifactId>
                                    </exclusion>
                                    <exclusion>
                                        <groupId>javax.annotation</groupId>
                                        <artifactId>javax.annotation-api</artifactId>
                                    </exclusion>
                                    <exclusion>
                                        <groupId>javax.inject</groupId>
                                        <artifactId>javax.inject</artifactId>
                                    </exclusion>
                                    <exclusion>
                                        <groupId>org.slf4j</groupId>
                                        <artifactId>slf4j-api</artifactId>
                                    </exclusion>
                                    <exclusion><!-- let's prefer the plexus-utils pulled by maven-resolver-provider -->
                                        <groupId>org.codehaus.plexus</groupId>
                                        <artifactId>plexus-utils</artifactId>
                                    </exclusion>
                                </exclusions>
                            </dependency>
                            <dependency>
                                <groupId>org.apache.maven</groupId>
                                <artifactId>maven-settings</artifactId>
                                <version>1.0.0</version>
                            </dependency>
                            <dependency>
                                <groupId>org.gradle</groupId>
                                <artifactId>gradle-tooling-api</artifactId>
                                <version>1.0.0</version>
                                <exclusions>
                                    <exclusion>
                                        <groupId>org.slf4j</groupId>
                                        <artifactId>slf4j-api</artifactId>
                                    </exclusion>
                                </exclusions>
                            </dependency>
                            <dependency>
                                <groupId>org.apache.maven.shared</groupId>
                                <artifactId>maven-shared-utils</artifactId>
                                <version>1.0.0</version>
                            </dependency>
                            <dependency>
                                <groupId>jakarta.annotation</groupId>
                                <artifactId>jakarta.annotation-api</artifactId>
                                <version>1.0.0</version>
                            </dependency>
                            <dependency>
                                <groupId>jakarta.inject</groupId>
                                <artifactId>jakarta.inject-api</artifactId>
                                <version>1.0.0</version>
                            </dependency>
                            <dependency>
                                <groupId>org.apache.maven</groupId>
                                <artifactId>maven-resolver-provider</artifactId>
                                <version>1.0.0</version>
                                <exclusions>
                                    <exclusion>
                                        <groupId>javax.inject</groupId>
                                        <artifactId>javax.inject</artifactId>
                                    </exclusion>
                                    <exclusion>
                                        <groupId>org.slf4j</groupId>
                                        <artifactId>slf4j-api</artifactId>
                                    </exclusion>
                                </exclusions>
                            </dependency>
                            <dependency>
                                <groupId>org.apache.maven</groupId>
                                <artifactId>maven-settings-builder</artifactId>
                                <version>1.0.0</version>
                                <exclusions>
                                    <exclusion>
                                        <groupId>javax.inject</groupId>
                                        <artifactId>javax.inject</artifactId>
                                    </exclusion>
                                    <exclusion>
                                        <groupId>org.codehaus.plexus</groupId>
                                        <artifactId>plexus-utils</artifactId>
                                    </exclusion>
                                </exclusions>
                            </dependency>
                            <dependency>
                                <groupId>org.apache.maven.plugin-tools</groupId>
                                <artifactId>maven-plugin-annotations</artifactId>
                                <version>1.0.0</version>
                                <exclusions>
                                    <exclusion>
                                        <groupId>org.apache.maven</groupId>
                                        <artifactId>maven-artifact</artifactId>
                                    </exclusion>
                                </exclusions>
                            </dependency>
                            <dependency>
                                <groupId>org.apache.maven.resolver</groupId>
                                <artifactId>maven-resolver-connector-basic</artifactId>
                                <version>1.0.0</version>
                                <exclusions>
                                    <exclusion>
                                        <groupId>org.slf4j</groupId>
                                        <artifactId>slf4j-api</artifactId>
                                    </exclusion>
                                </exclusions>
                            </dependency>
                            <dependency>
                                <groupId>org.apache.maven.resolver</groupId>
                                <artifactId>maven-resolver-transport-wagon</artifactId>
                                <version>1.0.0</version>
                                <exclusions>
                                    <exclusion>
                                        <groupId>org.slf4j</groupId>
                                        <artifactId>slf4j-api</artifactId>
                                    </exclusion>
                                </exclusions>
                            </dependency>
                            <dependency>
                                <groupId>org.apache.maven.resolver</groupId>
                                <artifactId>maven-resolver-api</artifactId>
                                <version>1.0.0</version>
                            </dependency>
                            <dependency>
                                <groupId>org.apache.maven.resolver</groupId>
                                <artifactId>maven-resolver-util</artifactId>
                                <version>1.0.0</version>
                            </dependency>
                            <dependency>
                                <groupId>org.apache.maven.wagon</groupId>
                                <artifactId>wagon-file</artifactId>
                                <version>1.0.0</version>
                                <exclusions>
                                    <exclusion>
                                        <groupId>org.codehaus.plexus</groupId>
                                        <artifactId>plexus-utils</artifactId>
                                    </exclusion>
                                </exclusions>
                            </dependency>
                            <dependency>
                                <groupId>org.apache.maven.wagon</groupId>
                                <artifactId>wagon-http</artifactId>
                                <version>1.0.0</version>
                                <exclusions>
                                    <exclusion>
                                        <groupId>org.slf4j</groupId>
                                        <artifactId>slf4j-api</artifactId>
                                    </exclusion>
                                    <exclusion>
                                        <groupId>org.codehaus.plexus</groupId>
                                        <artifactId>plexus-utils</artifactId>
                                    </exclusion>
                                    <exclusion>
                                        <groupId>commons-io</groupId>
                                        <artifactId>commons-io</artifactId>
                                    </exclusion>
                                </exclusions>
                            </dependency>
                            <dependency>
                                <groupId>org.apache.maven.wagon</groupId>
                                <artifactId>wagon-provider-api</artifactId>
                                <version>1.0.0</version>
                            </dependency>
                            <dependency>
                                <groupId>org.apache.httpcomponents</groupId>
                                <artifactId>httpcore</artifactId>
                                <version>1.0.0</version>
                            </dependency>
                            <dependency>
                                <groupId>org.eclipse.sisu</groupId>
                                <artifactId>org.eclipse.sisu.inject</artifactId>
                                <version>1.0.0</version>
                            </dependency>
                            <dependency>
                                <groupId>org.eclipse.sisu</groupId>
                                <artifactId>org.eclipse.sisu.plexus</artifactId>
                                <version>1.0.0</version>
                                <exclusions>
                                    <exclusion>
                                        <groupId>*</groupId>
                                        <artifactId>*</artifactId>
                                    </exclusion>
                                </exclusions>
                            </dependency>
                            <dependency>
                                <groupId>org.graalvm.sdk</groupId>
                                <artifactId>graal-sdk</artifactId>
                                <version>1.0.0</version>
                            </dependency>
                            <dependency>
                                <groupId>org.jboss.logmanager</groupId>
                                <artifactId>jboss-logmanager-embedded</artifactId>
                                <version>1.0.0</version>
                            </dependency>
                            <dependency>
                                <groupId>org.jboss.logging</groupId>
                                <artifactId>jboss-logging</artifactId>
                                <version>1.0.0</version>
                            </dependency>
                            <dependency>
                                <groupId>org.jboss.logging</groupId>
                                <artifactId>commons-logging-jboss-logging</artifactId>
                                <version>1.0.0</version>
                            </dependency>
                            <dependency>
                                <groupId>org.jboss.slf4j</groupId>
                                <artifactId>slf4j-jboss-logmanager</artifactId>
                                <version>1.0.0</version>
                            </dependency>
                            <dependency>
                                <groupId>org.slf4j</groupId>
                                <artifactId>slf4j-api</artifactId>
                                <version>1.0.0</version>
                            </dependency>
                            <dependency>
                                <groupId>org.codehaus.plexus</groupId>
                                <artifactId>plexus-classworlds</artifactId>
                                <version>1.0.0</version>
                                <exclusions>
                                    <exclusion>
                                        <groupId>*</groupId>
                                        <artifactId>*</artifactId>
                                    </exclusion>
                                </exclusions>
                            </dependency>
                            <dependency>
                                <groupId>org.jsoup</groupId>
                                <artifactId>jsoup</artifactId>
                                <version>1.0.0</version>
                            </dependency>
                            <!-- Smallrye Common dependencies, imported as a BOM -->
                            <dependency>
                                <groupId>io.smallrye.common</groupId>
                                <artifactId>smallrye-common-bom</artifactId>
                                <version>1.0.0</version>
                                <scope>import</scope>
                                <type>pom</type>
                            </dependency>
                        </dependencies>
                    </dependencyManagement>
                    <build>
                        <plugins>
                            <plugin>
                                <groupId>org.openrewrite.maven</groupId>
                                <artifactId>rewrite-maven-plugin</artifactId>
                                <configuration>
                                    <activeRecipes>
                                        <recipe>io.quarkus.maven.javax.allow</recipe>
                                        <recipe>io.quarkus.maven.javax.managed</recipe>
                                    </activeRecipes>
                                </configuration>
                            </plugin>
                        </plugins>
                    </build>
                </project>
            """.trimIndent())
        val autodetect = Autodetect.detect(pom)
        val tabsAndIndents: TabsAndIndentsStyle =
            autodetect.styles.stream().filter(TabsAndIndentsStyle::class::isInstance).findFirst().get() as TabsAndIndentsStyle
        assertThat(tabsAndIndents.tabSize).isEqualTo(1)
        assertThat(tabsAndIndents.indentSize).isEqualTo(4)
        assertThat(tabsAndIndents.useTabCharacter).isFalse
    }

}