/*
 * Copyright 2024 the original author or authors.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openrewrite.maven.trait;

import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.openrewrite.DocumentExample;
import org.openrewrite.marker.SearchResult;
import org.openrewrite.test.RecipeSpec;
import org.openrewrite.test.RewriteTest;

import static org.openrewrite.maven.Assertions.pomXml;

class MavenPluginTest implements RewriteTest {

    @Override
    public void defaults(RecipeSpec spec) {
        spec.recipe(RewriteTest.toRecipe(() -> new MavenPlugin.Matcher().asVisitor(plugin ->
          SearchResult.found(plugin.getTree(), plugin.getGroupId() + ":" + plugin.getArtifactId()))));
    }

    @DocumentExample
    @Test
    void findAllPlugin() {
        rewriteRun(
          spec -> spec.recipe(RewriteTest.toRecipe(() -> new MavenPlugin.Matcher(null, null, null).asVisitor(plugin ->
            SearchResult.found(plugin.getTree(), plugin.getGroupId() + ":" + plugin.getArtifactId())))),
          pomXml(
            """
              <project>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <build>
                      <pluginManagement>
                          <plugins>
                              <plugin>
                                  <groupId>org.apache.maven</groupId>
                                  <artifactId>maven-compiler-plugin</artifactId>
                              </plugin>
                          </plugins>
                      </pluginManagement>
                      <plugins>
                          <plugin>
                              <groupId>io.quarkus</groupId>
                              <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                              <version>3.0.0.Beta1</version>
                          </plugin>
                      </plugins>
                  </build>
              </project>
              """,
            """
              <project>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <build>
                      <pluginManagement>
                          <plugins>
                              <!--~~(org.apache.maven:maven-compiler-plugin)~~>--><plugin>
                                  <groupId>org.apache.maven</groupId>
                                  <artifactId>maven-compiler-plugin</artifactId>
                              </plugin>
                          </plugins>
                      </pluginManagement>
                      <plugins>
                          <!--~~(io.quarkus:quarkus-bootstrap-maven-plugin)~~>--><plugin>
                              <groupId>io.quarkus</groupId>
                              <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                              <version>3.0.0.Beta1</version>
                          </plugin>
                      </plugins>
                  </build>
              </project>
              """
          )
        );
    }

    @Nested
    class TypeOfPlugin {
        @Test
        void findBuildPlugin() {
            rewriteRun(
              spec -> spec.recipe(RewriteTest.toRecipe(() -> new MavenPlugin.Matcher(false, null, null).asVisitor(plugin ->
                SearchResult.found(plugin.getTree(), plugin.getGroupId() + ":" + plugin.getArtifactId())))),
              pomXml(
                """
                  <project>
                      <groupId>com.mycompany.app</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <build>
                          <pluginManagement>
                              <plugins>
                                  <plugin>
                                      <groupId>io.quarkus</groupId>
                                      <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                      <version>3.0.0.Beta1</version>
                                  </plugin>
                              </plugins>
                          </pluginManagement>
                          <plugins>
                              <plugin>
                                  <groupId>io.quarkus</groupId>
                                  <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                  <version>3.0.0.Beta1</version>
                              </plugin>
                          </plugins>
                      </build>
                  </project>
                  """,
                """
                  <project>
                      <groupId>com.mycompany.app</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <build>
                          <pluginManagement>
                              <plugins>
                                  <plugin>
                                      <groupId>io.quarkus</groupId>
                                      <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                      <version>3.0.0.Beta1</version>
                                  </plugin>
                              </plugins>
                          </pluginManagement>
                          <plugins>
                              <!--~~(io.quarkus:quarkus-bootstrap-maven-plugin)~~>--><plugin>
                                  <groupId>io.quarkus</groupId>
                                  <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                  <version>3.0.0.Beta1</version>
                              </plugin>
                          </plugins>
                      </build>
                  </project>
                  """
              )
            );
        }

        @Test
        void findManagedPlugin() {
            rewriteRun(
              spec -> spec.recipe(RewriteTest.toRecipe(() -> new MavenPlugin.Matcher(true, null, null).asVisitor(plugin ->
                SearchResult.found(plugin.getTree(), plugin.getGroupId() + ":" + plugin.getArtifactId())))),
              pomXml(
                """
                  <project>
                      <groupId>com.mycompany.app</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <build>
                          <pluginManagement>
                              <plugins>
                                  <plugin>
                                      <groupId>io.quarkus</groupId>
                                      <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                      <version>3.0.0.Beta1</version>
                                  </plugin>
                              </plugins>
                          </pluginManagement>
                          <plugins>
                              <plugin>
                                  <groupId>io.quarkus</groupId>
                                  <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                  <version>3.0.0.Beta1</version>
                              </plugin>
                          </plugins>
                      </build>
                  </project>
                  """,
                """
                  <project>
                      <groupId>com.mycompany.app</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <build>
                          <pluginManagement>
                              <plugins>
                                  <!--~~(io.quarkus:quarkus-bootstrap-maven-plugin)~~>--><plugin>
                                      <groupId>io.quarkus</groupId>
                                      <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                      <version>3.0.0.Beta1</version>
                                  </plugin>
                              </plugins>
                          </pluginManagement>
                          <plugins>
                              <plugin>
                                  <groupId>io.quarkus</groupId>
                                  <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                  <version>3.0.0.Beta1</version>
                              </plugin>
                          </plugins>
                      </build>
                  </project>
                  """
              )
            );
        }
    }

    @Nested
    class FilterByIDs {
        @Test
        void matchByGroup() {
            rewriteRun(
              spec -> spec.recipe(RewriteTest.toRecipe(() -> new MavenPlugin.Matcher(null, "org.apache.maven.plugins", null).asVisitor(plugin ->
                SearchResult.found(plugin.getTree(), plugin.getGroupId() + ":" + plugin.getArtifactId())))),
              pomXml(
                """
                    <project>
                      <groupId>com.mycompany.app</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <build>
                          <pluginManagement>
                              <plugins>
                                  <plugin>
                                      <groupId>org.apache.maven.plugins</groupId>
                                      <artifactId>maven-compiler-plugin</artifactId>
                                  </plugin>
                                  <plugin>
                                      <groupId>org.apache.maven.plugins</groupId>
                                      <artifactId>maven-javadoc-plugin</artifactId>
                                  </plugin>
                                  <plugin>
                                      <groupId>io.quarkus</groupId>
                                      <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                      <version>3.0.0.Beta1</version>
                                  </plugin>
                              </plugins>
                          </pluginManagement>
                          <plugins>
                              <plugin>
                                  <groupId>org.apache.maven.plugins</groupId>
                                  <artifactId>maven-compiler-plugin</artifactId>
                              </plugin>
                              <plugin>
                                  <groupId>org.apache.maven.plugins</groupId>
                                  <artifactId>maven-javadoc-plugin</artifactId>
                              </plugin>
                              <plugin>
                                  <groupId>io.quarkus</groupId>
                                  <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                  <version>3.0.0.Beta1</version>
                              </plugin>
                          </plugins>
                      </build>
                  </project>
                  """,
              """
                  <project>
                    <groupId>com.mycompany.app</groupId>
                    <artifactId>my-app</artifactId>
                    <version>1</version>
                    <build>
                        <pluginManagement>
                            <plugins>
                                <!--~~(org.apache.maven.plugins:maven-compiler-plugin)~~>--><plugin>
                                    <groupId>org.apache.maven.plugins</groupId>
                                    <artifactId>maven-compiler-plugin</artifactId>
                                </plugin>
                                <!--~~(org.apache.maven.plugins:maven-javadoc-plugin)~~>--><plugin>
                                    <groupId>org.apache.maven.plugins</groupId>
                                    <artifactId>maven-javadoc-plugin</artifactId>
                                </plugin>
                                <plugin>
                                    <groupId>io.quarkus</groupId>
                                    <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                    <version>3.0.0.Beta1</version>
                                </plugin>
                            </plugins>
                        </pluginManagement>
                        <plugins>
                            <!--~~(org.apache.maven.plugins:maven-compiler-plugin)~~>--><plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-compiler-plugin</artifactId>
                            </plugin>
                            <!--~~(org.apache.maven.plugins:maven-javadoc-plugin)~~>--><plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-javadoc-plugin</artifactId>
                            </plugin>
                            <plugin>
                                <groupId>io.quarkus</groupId>
                                <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                <version>3.0.0.Beta1</version>
                            </plugin>
                        </plugins>
                    </build>
                </project>
                """
              )
            );
        }

        @Test
        void matchByArtifact() {
            rewriteRun(
              spec -> spec.recipe(RewriteTest.toRecipe(() -> new MavenPlugin.Matcher(null, null, "quarkus-bootstrap-maven-plugin").asVisitor(plugin ->
                SearchResult.found(plugin.getTree(), plugin.getGroupId() + ":" + plugin.getArtifactId())))),
              pomXml(
                """
                    <project>
                      <groupId>com.mycompany.app</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <build>
                          <pluginManagement>
                              <plugins>
                                  <plugin>
                                      <groupId>org.apache.maven.plugins</groupId>
                                      <artifactId>maven-compiler-plugin</artifactId>
                                  </plugin>
                                  <plugin>
                                      <groupId>org.apache.maven.plugins</groupId>
                                      <artifactId>maven-javadoc-plugin</artifactId>
                                  </plugin>
                                  <plugin>
                                      <groupId>io.quarkus</groupId>
                                      <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                      <version>3.0.0.Beta1</version>
                                  </plugin>
                              </plugins>
                          </pluginManagement>
                          <plugins>
                              <plugin>
                                  <groupId>org.apache.maven.plugins</groupId>
                                  <artifactId>maven-compiler-plugin</artifactId>
                              </plugin>
                              <plugin>
                                  <groupId>org.apache.maven.plugins</groupId>
                                  <artifactId>maven-javadoc-plugin</artifactId>
                              </plugin>
                              <plugin>
                                  <groupId>io.quarkus</groupId>
                                  <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                  <version>3.0.0.Beta1</version>
                              </plugin>
                          </plugins>
                      </build>
                  </project>
                  """,
                """
                    <project>
                      <groupId>com.mycompany.app</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <build>
                          <pluginManagement>
                              <plugins>
                                  <plugin>
                                      <groupId>org.apache.maven.plugins</groupId>
                                      <artifactId>maven-compiler-plugin</artifactId>
                                  </plugin>
                                  <plugin>
                                      <groupId>org.apache.maven.plugins</groupId>
                                      <artifactId>maven-javadoc-plugin</artifactId>
                                  </plugin>
                                  <!--~~(io.quarkus:quarkus-bootstrap-maven-plugin)~~>--><plugin>
                                      <groupId>io.quarkus</groupId>
                                      <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                      <version>3.0.0.Beta1</version>
                                  </plugin>
                              </plugins>
                          </pluginManagement>
                          <plugins>
                              <plugin>
                                  <groupId>org.apache.maven.plugins</groupId>
                                  <artifactId>maven-compiler-plugin</artifactId>
                              </plugin>
                              <plugin>
                                  <groupId>org.apache.maven.plugins</groupId>
                                  <artifactId>maven-javadoc-plugin</artifactId>
                              </plugin>
                              <!--~~(io.quarkus:quarkus-bootstrap-maven-plugin)~~>--><plugin>
                                  <groupId>io.quarkus</groupId>
                                  <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                  <version>3.0.0.Beta1</version>
                              </plugin>
                          </plugins>
                      </build>
                  </project>
                  """
              )
            );
        }

        @Test
        void matchByGroupAndId() {
            rewriteRun(
              spec -> spec.recipe(RewriteTest.toRecipe(() -> new MavenPlugin.Matcher(null, "org.apache.maven.plugins", "maven-javadoc-plugin").asVisitor(plugin ->
                SearchResult.found(plugin.getTree(), plugin.getGroupId() + ":" + plugin.getArtifactId())))),
              pomXml(
                """
                    <project>
                      <groupId>com.mycompany.app</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <build>
                          <pluginManagement>
                              <plugins>
                                  <plugin>
                                      <groupId>org.apache.maven.plugins</groupId>
                                      <artifactId>maven-compiler-plugin</artifactId>
                                  </plugin>
                                  <plugin>
                                      <groupId>org.apache.maven.plugins</groupId>
                                      <artifactId>maven-javadoc-plugin</artifactId>
                                  </plugin>
                                  <plugin>
                                      <groupId>io.quarkus</groupId>
                                      <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                      <version>3.0.0.Beta1</version>
                                  </plugin>
                              </plugins>
                          </pluginManagement>
                          <plugins>
                              <plugin>
                                  <groupId>org.apache.maven.plugins</groupId>
                                  <artifactId>maven-compiler-plugin</artifactId>
                              </plugin>
                              <plugin>
                                  <groupId>org.apache.maven.plugins</groupId>
                                  <artifactId>maven-javadoc-plugin</artifactId>
                              </plugin>
                              <plugin>
                                  <groupId>io.quarkus</groupId>
                                  <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                  <version>3.0.0.Beta1</version>
                              </plugin>
                          </plugins>
                      </build>
                  </project>
                  """,
                """
                    <project>
                      <groupId>com.mycompany.app</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <build>
                          <pluginManagement>
                              <plugins>
                                  <plugin>
                                      <groupId>org.apache.maven.plugins</groupId>
                                      <artifactId>maven-compiler-plugin</artifactId>
                                  </plugin>
                                  <!--~~(org.apache.maven.plugins:maven-javadoc-plugin)~~>--><plugin>
                                      <groupId>org.apache.maven.plugins</groupId>
                                      <artifactId>maven-javadoc-plugin</artifactId>
                                  </plugin>
                                  <plugin>
                                      <groupId>io.quarkus</groupId>
                                      <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                      <version>3.0.0.Beta1</version>
                                  </plugin>
                              </plugins>
                          </pluginManagement>
                          <plugins>
                              <plugin>
                                  <groupId>org.apache.maven.plugins</groupId>
                                  <artifactId>maven-compiler-plugin</artifactId>
                              </plugin>
                              <!--~~(org.apache.maven.plugins:maven-javadoc-plugin)~~>--><plugin>
                                  <groupId>org.apache.maven.plugins</groupId>
                                  <artifactId>maven-javadoc-plugin</artifactId>
                              </plugin>
                              <plugin>
                                  <groupId>io.quarkus</groupId>
                                  <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                  <version>3.0.0.Beta1</version>
                              </plugin>
                          </plugins>
                      </build>
                  </project>
                  """
              )
            );
        }

        @Test
        void managedOnly() {
            rewriteRun(
              spec -> spec.recipe(RewriteTest.toRecipe(() -> new MavenPlugin.Matcher(true, "org.apache.maven.plugins", "maven-javadoc-plugin").asVisitor(plugin ->
                SearchResult.found(plugin.getTree(), plugin.getGroupId() + ":" + plugin.getArtifactId())))),
              pomXml(
                """
                    <project>
                      <groupId>com.mycompany.app</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <build>
                          <pluginManagement>
                              <plugins>
                                  <plugin>
                                      <groupId>org.apache.maven.plugins</groupId>
                                      <artifactId>maven-compiler-plugin</artifactId>
                                  </plugin>
                                  <plugin>
                                      <groupId>org.apache.maven.plugins</groupId>
                                      <artifactId>maven-javadoc-plugin</artifactId>
                                  </plugin>
                                  <plugin>
                                      <groupId>io.quarkus</groupId>
                                      <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                      <version>3.0.0.Beta1</version>
                                  </plugin>
                              </plugins>
                          </pluginManagement>
                          <plugins>
                              <plugin>
                                  <groupId>org.apache.maven.plugins</groupId>
                                  <artifactId>maven-compiler-plugin</artifactId>
                              </plugin>
                              <plugin>
                                  <groupId>org.apache.maven.plugins</groupId>
                                  <artifactId>maven-javadoc-plugin</artifactId>
                              </plugin>
                              <plugin>
                                  <groupId>io.quarkus</groupId>
                                  <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                  <version>3.0.0.Beta1</version>
                              </plugin>
                          </plugins>
                      </build>
                  </project>
                  """,
                """
                    <project>
                      <groupId>com.mycompany.app</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <build>
                          <pluginManagement>
                              <plugins>
                                  <plugin>
                                      <groupId>org.apache.maven.plugins</groupId>
                                      <artifactId>maven-compiler-plugin</artifactId>
                                  </plugin>
                                  <!--~~(org.apache.maven.plugins:maven-javadoc-plugin)~~>--><plugin>
                                      <groupId>org.apache.maven.plugins</groupId>
                                      <artifactId>maven-javadoc-plugin</artifactId>
                                  </plugin>
                                  <plugin>
                                      <groupId>io.quarkus</groupId>
                                      <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                      <version>3.0.0.Beta1</version>
                                  </plugin>
                              </plugins>
                          </pluginManagement>
                          <plugins>
                              <plugin>
                                  <groupId>org.apache.maven.plugins</groupId>
                                  <artifactId>maven-compiler-plugin</artifactId>
                              </plugin>
                              <plugin>
                                  <groupId>org.apache.maven.plugins</groupId>
                                  <artifactId>maven-javadoc-plugin</artifactId>
                              </plugin>
                              <plugin>
                                  <groupId>io.quarkus</groupId>
                                  <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                  <version>3.0.0.Beta1</version>
                              </plugin>
                          </plugins>
                      </build>
                  </project>
                  """
              )
            );
        }

        @Test
        void buildOnly() {
            rewriteRun(
              spec -> spec.recipe(RewriteTest.toRecipe(() -> new MavenPlugin.Matcher(false, "org.apache.maven.plugins", "maven-javadoc-plugin").asVisitor(plugin ->
                SearchResult.found(plugin.getTree(), plugin.getGroupId() + ":" + plugin.getArtifactId())))),
              pomXml(
                """
                    <project>
                      <groupId>com.mycompany.app</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <build>
                          <pluginManagement>
                              <plugins>
                                  <plugin>
                                      <groupId>org.apache.maven.plugins</groupId>
                                      <artifactId>maven-compiler-plugin</artifactId>
                                  </plugin>
                                  <plugin>
                                      <groupId>org.apache.maven.plugins</groupId>
                                      <artifactId>maven-javadoc-plugin</artifactId>
                                  </plugin>
                                  <plugin>
                                      <groupId>io.quarkus</groupId>
                                      <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                      <version>3.0.0.Beta1</version>
                                  </plugin>
                              </plugins>
                          </pluginManagement>
                          <plugins>
                              <plugin>
                                  <groupId>org.apache.maven.plugins</groupId>
                                  <artifactId>maven-compiler-plugin</artifactId>
                              </plugin>
                              <plugin>
                                  <groupId>org.apache.maven.plugins</groupId>
                                  <artifactId>maven-javadoc-plugin</artifactId>
                              </plugin>
                              <plugin>
                                  <groupId>io.quarkus</groupId>
                                  <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                  <version>3.0.0.Beta1</version>
                              </plugin>
                          </plugins>
                      </build>
                  </project>
                  """,
                """
                    <project>
                      <groupId>com.mycompany.app</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <build>
                          <pluginManagement>
                              <plugins>
                                  <plugin>
                                      <groupId>org.apache.maven.plugins</groupId>
                                      <artifactId>maven-compiler-plugin</artifactId>
                                  </plugin>
                                  <plugin>
                                      <groupId>org.apache.maven.plugins</groupId>
                                      <artifactId>maven-javadoc-plugin</artifactId>
                                  </plugin>
                                  <plugin>
                                      <groupId>io.quarkus</groupId>
                                      <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                      <version>3.0.0.Beta1</version>
                                  </plugin>
                              </plugins>
                          </pluginManagement>
                          <plugins>
                              <plugin>
                                  <groupId>org.apache.maven.plugins</groupId>
                                  <artifactId>maven-compiler-plugin</artifactId>
                              </plugin>
                              <!--~~(org.apache.maven.plugins:maven-javadoc-plugin)~~>--><plugin>
                                  <groupId>org.apache.maven.plugins</groupId>
                                  <artifactId>maven-javadoc-plugin</artifactId>
                              </plugin>
                              <plugin>
                                  <groupId>io.quarkus</groupId>
                                  <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                  <version>3.0.0.Beta1</version>
                              </plugin>
                          </plugins>
                      </build>
                  </project>
                  """
              )
            );
        }

        @Test
        void findNone() {
            rewriteRun(
              spec -> spec.recipe(RewriteTest.toRecipe(() -> new MavenPlugin.Matcher(null, "org.apache.maven.plugins", "other").asVisitor(plugin ->
                SearchResult.found(plugin.getTree(), plugin.getGroupId() + ":" + plugin.getArtifactId())))),
              pomXml(
                """
                    <project>
                      <groupId>com.mycompany.app</groupId>
                      <artifactId>my-app</artifactId>
                      <version>1</version>
                      <build>
                          <pluginManagement>
                              <plugins>
                                  <plugin>
                                      <groupId>org.apache.maven.plugins</groupId>
                                      <artifactId>maven-compiler-plugin</artifactId>
                                  </plugin>
                                  <plugin>
                                      <groupId>org.apache.maven.plugins</groupId>
                                      <artifactId>maven-javadoc-plugin</artifactId>
                                  </plugin>
                                  <plugin>
                                      <groupId>io.quarkus</groupId>
                                      <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                      <version>3.0.0.Beta1</version>
                                  </plugin>
                              </plugins>
                          </pluginManagement>
                          <plugins>
                              <plugin>
                                  <groupId>org.apache.maven.plugins</groupId>
                                  <artifactId>maven-compiler-plugin</artifactId>
                              </plugin>
                              <plugin>
                                  <groupId>org.apache.maven.plugins</groupId>
                                  <artifactId>maven-javadoc-plugin</artifactId>
                              </plugin>
                              <plugin>
                                  <groupId>io.quarkus</groupId>
                                  <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
                                  <version>3.0.0.Beta1</version>
                              </plugin>
                          </plugins>
                      </build>
                  </project>
                  """
              )
            );
        }
    }
}
