/*
 * Copyright 2026 the original author or authors.
 * <p>
 * Licensed under the Moderne Source Available License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://docs.moderne.io/licensing/moderne-source-available-license
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openrewrite.python.internal.pdmlock;

import lombok.Value;
import lombok.With;

import java.util.List;
import java.util.Map;

/**
 * Typed document model of a pdm.lock file (lock_version 4.5.0). Values are stored as read;
 * {@link PdmLockWriter} re-emits without reformatting.
 */
@Value
@With
public class PdmLock {

    /** The two-line {@code # This file is @generated by PDM.} header, preserved verbatim. */
    String header;

    List<String> groups;
    List<String> strategy;

    /** {@code [[metadata.targets]]} entries, each an ordered map (e.g. {@code requires_python}). */
    List<Map<String, String>> targets;

    String lockVersion;

    /** The {@code algo:hex} content hash, stored with its algorithm prefix. */
    String contentHash;

    List<PdmLockPackage> packages;
}
