/*
 * Copyright 2026 the original author or authors.
 * <p>
 * Licensed under the Moderne Source Available License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://docs.moderne.io/licensing/moderne-source-available-license
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openrewrite.javascript.internal.lock.resolve;

import org.jspecify.annotations.Nullable;
import org.junit.jupiter.api.Test;
import org.openrewrite.javascript.internal.lock.EngineFailure;
import org.openrewrite.javascript.internal.registry.VersionManifest;

import java.util.*;

import static java.util.Collections.emptyMap;
import static java.util.Collections.singletonMap;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatExceptionOfType;

/**
 * Pure serializer tests: a {@link ResolutionGraph} built from an in-memory {@link Registry} (no network) is written
 * and byte-compared against the exact {@code yarn.lock} shape yarn v1 produces — the flat closure, merged selectors,
 * a directly-declared fork's two flat blocks — plus the fail-loud boundaries. Registry tarball hosts are mirrored to
 * registry.yarnpkg.com exactly as yarn does.
 */
class YarnClassicLockWriterTest {

    private static final String HEADER =
            "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n";

    @Test
    void flatClosure() {
        FakeRegistry registry = new FakeRegistry()
                .add("a", "1.2.0", singletonMap("b", "^2.0.0"))
                .add("b", "2.3.0", emptyMap());

        ResolutionGraph graph = new NpmGraphBuilder(registry)
                .build(singletonMap("", app(singletonMap("a", "^1.0.0"))));

        assertThat(new YarnClassicLockWriter(true).write(graph)).isEqualTo(HEADER +
                "a@^1.0.0:\n" +
                "  version \"1.2.0\"\n" +
                "  resolved \"https://registry.yarnpkg.com/a/-/a-1.2.0.tgz#sha1-a-1.2.0\"\n" +
                "  integrity sha512-a-1.2.0\n" +
                "  dependencies:\n" +
                "    b \"^2.0.0\"\n" +
                "\n" +
                "b@^2.0.0:\n" +
                "  version \"2.3.0\"\n" +
                "  resolved \"https://registry.yarnpkg.com/b/-/b-2.3.0.tgz#sha1-b-2.3.0\"\n" +
                "  integrity sha512-b-2.3.0\n");
    }

    @Test
    void mergedSelectorsSortAlpha() {
        // root declares n@1.0.0 (exact) and p@^1.0.0; p requires n@^1.0.0 -> both resolve to n@1.0.0, one block.
        FakeRegistry registry = new FakeRegistry()
                .add("n", "1.0.0", emptyMap())
                .add("p", "1.0.0", singletonMap("n", "^1.0.0"));
        Map<String, String> deps = new LinkedHashMap<>();
        deps.put("n", "1.0.0");
        deps.put("p", "^1.0.0");

        String lock = new YarnClassicLockWriter(true).write(new NpmGraphBuilder(registry).build(singletonMap("", app(deps))));
        assertThat(lock).contains("n@1.0.0, n@^1.0.0:\n");
    }

    @Test
    void directlyDeclaredForkIsTwoFlatBlocks() {
        FakeRegistry registry = new FakeRegistry()
                .add("parent", "1.0.0", singletonMap("shared", "1.0.0"))
                .add("shared", "1.0.0", emptyMap())
                .add("shared", "2.0.0", emptyMap());
        Map<String, String> deps = new LinkedHashMap<>();
        deps.put("parent", "^1.0.0");
        deps.put("shared", "2.0.0");

        String lock = new YarnClassicLockWriter(true).write(new NpmGraphBuilder(registry).build(singletonMap("", app(deps))));
        assertThat(lock).contains("shared@1.0.0:\n  version \"1.0.0\"");
        assertThat(lock).contains("shared@2.0.0:\n  version \"2.0.0\"");
    }

    @Test
    void satisfiedPeerSurfaceOmitsPeerSection() {
        // has-peer declares a `react` peer satisfied by the top-level react; yarn v1 records no peer surface, so
        // has-peer's block is byte-identical to a peer-free one (no dependencies:, no peerDependencies:).
        FakeRegistry registry = new FakeRegistry()
                .addWithPeers("has-peer", "1.0.0", emptyMap(), singletonMap("react", ">=17"))
                .add("react", "18.2.0", emptyMap());
        Map<String, String> deps = new LinkedHashMap<>();
        deps.put("has-peer", "^1.0.0");
        deps.put("react", "^18.0.0");

        String lock = new YarnClassicLockWriter(true).write(new NpmGraphBuilder(registry).build(singletonMap("", app(deps))));
        assertThat(lock).isEqualTo(HEADER +
                "has-peer@^1.0.0:\n" +
                "  version \"1.0.0\"\n" +
                "  resolved \"https://registry.yarnpkg.com/has-peer/-/has-peer-1.0.0.tgz#sha1-has-peer-1.0.0\"\n" +
                "  integrity sha512-has-peer-1.0.0\n" +
                "\n" +
                "react@^18.0.0:\n" +
                "  version \"18.2.0\"\n" +
                "  resolved \"https://registry.yarnpkg.com/react/-/react-18.2.0.tgz#sha1-react-18.2.0\"\n" +
                "  integrity sha512-react-18.2.0\n");
    }

    @Test
    void peerDeclarerStillEmitsItsOwnDependencies() {
        // widget carries both a regular dep and a satisfied `react` peer; its block keeps dependencies: but the
        // peer is neither a peerDependencies: section nor folded into dependencies:.
        FakeRegistry registry = new FakeRegistry()
                .addWithPeers("widget", "1.0.0", singletonMap("dep", "^1.0.0"), singletonMap("react", ">=17"))
                .add("dep", "1.0.0", emptyMap())
                .add("react", "18.2.0", emptyMap());
        Map<String, String> deps = new LinkedHashMap<>();
        deps.put("widget", "^1.0.0");
        deps.put("react", "^18.0.0");

        String lock = new YarnClassicLockWriter(true).write(new NpmGraphBuilder(registry).build(singletonMap("", app(deps))));
        assertThat(lock).contains("widget@^1.0.0:\n" +
                "  version \"1.0.0\"\n" +
                "  resolved \"https://registry.yarnpkg.com/widget/-/widget-1.0.0.tgz#sha1-widget-1.0.0\"\n" +
                "  integrity sha512-widget-1.0.0\n" +
                "  dependencies:\n" +
                "    dep \"^1.0.0\"\n");
        assertThat(lock).doesNotContain("peerDependencies");
    }

    @Test
    void dependenciesBlockComesFromManifestNotOptionalEdges() {
        // resolvedEdges now merges optional edges too; the dependencies: block must render only manifest.dependencies
        // (b), never the optional edge (c) that a real yarn.lock would place under optionalDependencies elsewhere.
        VersionManifest a = vm("a", "1.0.0", singletonMap("b", "^1.0.0"), dist("a", "1.0.0"));
        VersionManifest b = vm("b", "1.0.0", emptyMap(), dist("b", "1.0.0"));
        Map<String, String> aEdges = new LinkedHashMap<>();
        aEdges.put("b", "1.0.0");
        aEdges.put("c", "2.0.0"); // stray optional edge folded into resolvedEdges
        Map<String, ResolvedNode> nodes = new LinkedHashMap<>();
        nodes.put("a@1.0.0", new ResolvedNode(a, aEdges));
        nodes.put("b@1.0.0", new ResolvedNode(b, emptyMap()));
        ResolutionGraph graph = new ResolutionGraph(
                Collections.singletonList(new ResolutionGraph.Importer("", "app", "1.0.0",
                        singletonMap("dependencies", singletonMap("a", "^1.0.0")), singletonMap("a", "1.0.0"))),
                nodes);

        String lock = new YarnClassicLockWriter(true).write(graph);
        assertThat(lock).contains("a@^1.0.0:\n" +
                "  version \"1.0.0\"\n" +
                "  resolved \"https://registry.yarnpkg.com/a/-/a-1.0.0.tgz#sha1-a-1.0.0\"\n" +
                "  integrity sha512-a-1.0.0\n" +
                "  dependencies:\n" +
                "    b \"^1.0.0\"\n");
        assertThat(lock).doesNotContain("2.0.0");
    }

    @Test
    void keepsNpmjsHostWhenNotMirroring() {
        FakeRegistry registry = new FakeRegistry().add("a", "1.0.0", emptyMap());
        String lock = new YarnClassicLockWriter(false)
                .write(new NpmGraphBuilder(registry).build(singletonMap("", app(singletonMap("a", "^1.0.0")))));
        assertThat(lock).contains("resolved \"https://registry.npmjs.org/a/-/a-1.0.0.tgz#sha1-a-1.0.0\"");
    }

    @Test
    void missingLocatorDefers() {
        VersionManifest noDist = vm("a", "1.0.0", emptyMap(), null);
        ResolutionGraph graph = new ResolutionGraph(
                Collections.singletonList(new ResolutionGraph.Importer("", "app", "1.0.0",
                        singletonMap("dependencies", singletonMap("a", "^1.0.0")), singletonMap("a", "1.0.0"))),
                singletonMap("a@1.0.0", new ResolvedNode(noDist, emptyMap())));
        assertThatExceptionOfType(EngineFailure.class).isThrownBy(() -> new YarnClassicLockWriter(true).write(graph));
    }

    @Test
    void workspaceImporterDefers() {
        ResolutionGraph graph = new ResolutionGraph(
                Collections.singletonList(new ResolutionGraph.Importer("packages/app", "app", "1.0.0",
                        emptyMap(), emptyMap())),
                emptyMap());
        assertThatExceptionOfType(EngineFailure.class).isThrownBy(() -> new YarnClassicLockWriter(true).write(graph));
    }

    // --- in-memory registry + manifest builders ---------------------------

    private static String app(Map<String, String> dependencies) {
        StringBuilder deps = new StringBuilder();
        for (Map.Entry<String, String> e : dependencies.entrySet()) {
            if (deps.length() > 0) {
                deps.append(',');
            }
            deps.append('"').append(e.getKey()).append("\":\"").append(e.getValue()).append('"');
        }
        return "{\"name\":\"app\",\"version\":\"1.0.0\",\"dependencies\":{" + deps + "}}";
    }

    private static VersionManifest.Dist dist(String name, String version) {
        return new VersionManifest.Dist(
                "https://registry.npmjs.org/" + name + "/-/" + name + "-" + version + ".tgz",
                "sha1-" + name + "-" + version, "sha512-" + name + "-" + version);
    }

    private static VersionManifest vm(String name, String version, Map<String, String> deps, VersionManifest.@Nullable Dist dist) {
        return vm(name, version, deps, null, dist);
    }

    private static VersionManifest vm(String name, String version, Map<String, String> deps,
                                      @Nullable Map<String, String> peers, VersionManifest.@Nullable Dist dist) {
        return new VersionManifest(name, version, null, null, deps.isEmpty() ? null : deps, null, peers, null, null,
                null, null, null, null, null, null, null, null, null, dist, null, null, null);
    }

    private static final class FakeRegistry implements Registry {
        final Map<String, Set<String>> versionsByName = new HashMap<>();
        final Map<String, VersionManifest> manifests = new HashMap<>();

        FakeRegistry add(String name, String version, Map<String, String> deps) {
            return addWithPeers(name, version, deps, null);
        }

        FakeRegistry addWithPeers(String name, String version, Map<String, String> deps, @Nullable Map<String, String> peers) {
            versionsByName.computeIfAbsent(name, k -> new TreeSet<>()).add(version);
            VersionManifest.Dist dist = new VersionManifest.Dist(
                    "https://registry.npmjs.org/" + name + "/-/" + name + "-" + version + ".tgz",
                    "sha1-" + name + "-" + version, "sha512-" + name + "-" + version);
            manifests.put(name + "@" + version, vm(name, version, deps, peers, dist));
            return this;
        }

        @Override
        public Set<String> versions(String name) {
            return versionsByName.getOrDefault(name, Collections.emptySet());
        }

        @Override
        public VersionManifest manifest(String name, String version) {
            return manifests.get(name + "@" + version);
        }
    }
}
