/*
 * Copyright 2026 the original author or authors.
 * <p>
 * Licensed under the Moderne Source Available License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://docs.moderne.io/licensing/moderne-source-available-license
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openrewrite.javascript.internal.lock.resolve;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fasterxml.jackson.databind.node.TextNode;
import org.jspecify.annotations.Nullable;
import org.junit.jupiter.api.Test;
import org.openrewrite.javascript.internal.lock.EngineFailure;
import org.openrewrite.javascript.internal.registry.VersionManifest;

import java.util.*;

import static java.util.Collections.*;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatExceptionOfType;

/**
 * Pure serializer tests: a {@link ResolutionGraph} built from an in-memory {@link Registry} (no network) is
 * written and byte-compared against the exact {@code yarn.lock} shape yarn 4.x produces — the flat descriptor
 * closure with a workspace importer entry, merged/sorted descriptor keys, and reproduced checksums (threaded in
 * verbatim by the {@link YarnBerryLockWriter.Checksums} stub) — plus the fail-loud boundaries.
 */
class YarnBerryLockWriterTest {

    // The real yarn 4.5.3 (cacheKey 10c0) checksums for these leaves, so the writer output is byte-exact.
    private static final Map<String, String> SUMS = new HashMap<>();

    static {
        SUMS.put("is-number@6.0.0", "10c0/5da4c68401529675c575878d2760d66f18eaef4b014858577f6003daf66488d7fe4eae684b1e8574e3fa1bb447c6c6c56b8491d2b4b3239da2d32e5f6f218008");
        SUMS.put("is-odd@3.0.1", "10c0/89ee2e353c5a3f3bd400c79db1c307a5b3506198ee8169d521e533a9b1d8a08fc95f21a919c084e98845b4286d7ffe309778da03744dfe66c3c1763ab1a030c6");
        SUMS.put("ms@2.1.3", "10c0/d924b57e7312b3b63ad21fc5b3dc0af5e78d61a1fc7cfb5457edaf26326bf62be5307cc87ffb6862ef1c2b33b0233cdb5d4f01c4c958cc0d660948b65a287a48");
    }

    private static final YarnBerryLockWriter.Checksums CHECKSUMS = (name, version, url) -> SUMS.get(name + "@" + version);

    @Test
    void flatClosure() {
        // baddc -> is-odd@3.0.1 (-> is-number ^6.0.0) + ms@2.1.3: a flat berry lock, entries sorted by descriptor.
        FakeRegistry registry = new FakeRegistry()
                .add("is-odd", "3.0.1", singletonMap("is-number", "^6.0.0"))
                .add("is-number", "6.0.0", emptyMap())
                .add("ms", "2.1.3", emptyMap());

        Map<String, String> deps = new LinkedHashMap<>();
        deps.put("is-odd", "3.0.1");
        deps.put("ms", "2.1.3");
        ResolutionGraph graph = new NpmGraphBuilder(registry).build(singletonMap("", app("baddc", deps)));

        assertThat(new YarnBerryLockWriter().write(graph, "10c0", 8, CHECKSUMS)).isEqualTo(
                "# This file is generated by running \"yarn install\" inside your project.\n" +
                "# Manual changes might be lost - proceed with caution!\n" +
                "\n" +
                "__metadata:\n" +
                "  version: 8\n" +
                "  cacheKey: 10c0\n" +
                "\n" +
                "\"baddc@workspace:.\":\n" +
                "  version: 0.0.0-use.local\n" +
                "  resolution: \"baddc@workspace:.\"\n" +
                "  dependencies:\n" +
                "    is-odd: \"npm:3.0.1\"\n" +
                "    ms: \"npm:2.1.3\"\n" +
                "  languageName: unknown\n" +
                "  linkType: soft\n" +
                "\n" +
                "\"is-number@npm:^6.0.0\":\n" +
                "  version: 6.0.0\n" +
                "  resolution: \"is-number@npm:6.0.0\"\n" +
                "  checksum: " + SUMS.get("is-number@6.0.0") + "\n" +
                "  languageName: node\n" +
                "  linkType: hard\n" +
                "\n" +
                "\"is-odd@npm:3.0.1\":\n" +
                "  version: 3.0.1\n" +
                "  resolution: \"is-odd@npm:3.0.1\"\n" +
                "  dependencies:\n" +
                "    is-number: \"npm:^6.0.0\"\n" +
                "  checksum: " + SUMS.get("is-odd@3.0.1") + "\n" +
                "  languageName: node\n" +
                "  linkType: hard\n" +
                "\n" +
                "\"ms@npm:2.1.3\":\n" +
                "  version: 2.1.3\n" +
                "  resolution: \"ms@npm:2.1.3\"\n" +
                "  checksum: " + SUMS.get("ms@2.1.3") + "\n" +
                "  languageName: node\n" +
                "  linkType: hard\n");
    }

    @Test
    void devAndOptionalImporterMerged() {
        // Root declares once (prod), supports-color (dev), is-odd (optional): berry merges all three into one
        // sorted dependencies block and flags the optional-scope is-odd in dependenciesMeta.
        Map<String, Map<String, String>> declared = new LinkedHashMap<>();
        declared.put("dependencies", singletonMap("once", "1.4.0"));
        declared.put("devDependencies", singletonMap("supports-color", "7.2.0"));
        declared.put("optionalDependencies", singletonMap("is-odd", "3.0.1"));
        Map<String, String> resolved = new LinkedHashMap<>();
        resolved.put("once", "1.4.0");
        resolved.put("supports-color", "7.2.0");
        resolved.put("is-odd", "3.0.1");
        ResolutionGraph graph = new ResolutionGraph(
                singletonList(new ResolutionGraph.Importer("", "resolve-devopt", "1.0.0", declared, resolved)),
                nodes(new ResolvedNode(leaf("once", "1.4.0"), emptyMap()),
                        new ResolvedNode(leaf("supports-color", "7.2.0"), emptyMap()),
                        new ResolvedNode(leaf("is-odd", "3.0.1"), emptyMap())));

        assertThat(new YarnBerryLockWriter().write(graph, "10c0", 8, CHECKSUMS)).contains(
                "\"resolve-devopt@workspace:.\":\n" +
                "  version: 0.0.0-use.local\n" +
                "  resolution: \"resolve-devopt@workspace:.\"\n" +
                "  dependencies:\n" +
                "    is-odd: \"npm:3.0.1\"\n" +
                "    once: \"npm:1.4.0\"\n" +
                "    supports-color: \"npm:7.2.0\"\n" +
                "  dependenciesMeta:\n" +
                "    is-odd:\n" +
                "      optional: true\n" +
                "  languageName: unknown\n" +
                "  linkType: soft\n");
    }

    @Test
    void forkDefers() {
        // Two versions of one name is a fork; berry's flat descriptor layout for a fork is not yet reproduced.
        ResolutionGraph graph = new ResolutionGraph(
                singletonList(new ResolutionGraph.Importer("", "app", "1.0.0",
                        singletonMap("dependencies", singletonMap("foo", "^1.0.0")), singletonMap("foo", "1.0.0"))),
                nodes(new ResolvedNode(leaf("foo", "1.0.0"), emptyMap()),
                        new ResolvedNode(leaf("foo", "2.0.0"), emptyMap())));

        assertThatExceptionOfType(EngineFailure.class)
                .isThrownBy(() -> new YarnBerryLockWriter().write(graph, "10c0", 8, CHECKSUMS));
    }

    @Test
    void peerSurfaceSerialized() {
        // plugin declares two peers (one raw, one range-quoted with a scoped, quoted key) and an optional-peer meta.
        Map<String, String> peers = new LinkedHashMap<>();
        peers.put("react", "^18.0.0");
        peers.put("@scope/host", ">=1.0.0");
        ObjectNode meta = JsonNodeFactory.instance.objectNode();
        meta.putObject("@scope/host").put("optional", true);
        VersionManifest plugin = manifestWithPeers("plugin", "1.0.0", singletonMap("dep", "^2.0.0"), peers, meta);
        ResolutionGraph graph = new ResolutionGraph(
                singletonList(new ResolutionGraph.Importer("", "app", "1.0.0",
                        singletonMap("dependencies", singletonMap("plugin", "^1.0.0")), singletonMap("plugin", "1.0.0"))),
                singletonMap("plugin@1.0.0", new ResolvedNode(plugin, emptyMap())));

        // dependencies -> peerDependencies (sorted; scoped key + `>=` value quoted, `react`/`^18.0.0` raw) ->
        // peerDependenciesMeta (scoped key quoted) -> checksum. `@` sorts before `r`.
        assertThat(new YarnBerryLockWriter().write(graph, "10c0", 8, CHECKSUMS)).contains(
                "\"plugin@npm:^1.0.0\":\n" +
                "  version: 1.0.0\n" +
                "  resolution: \"plugin@npm:1.0.0\"\n" +
                "  dependencies:\n" +
                "    dep: \"npm:^2.0.0\"\n" +
                "  peerDependencies:\n" +
                "    \"@scope/host\": \">=1.0.0\"\n" +
                "    react: ^18.0.0\n" +
                "  peerDependenciesMeta:\n" +
                "    \"@scope/host\":\n" +
                "      optional: true\n" +
                "  checksum: ");
    }

    @Test
    void peerMetaOnlySerialized() {
        // debug's shape: peerDependenciesMeta with no peerDependencies still writes the meta block.
        ObjectNode meta = JsonNodeFactory.instance.objectNode();
        meta.putObject("supports-color").put("optional", true);
        VersionManifest leaf = manifestWithPeers("debug", "4.4.1", singletonMap("ms", "^2.1.3"), null, meta);
        ResolutionGraph graph = new ResolutionGraph(
                singletonList(new ResolutionGraph.Importer("", "app", "1.0.0",
                        singletonMap("dependencies", singletonMap("debug", "^4.0.0")), singletonMap("debug", "4.4.1"))),
                singletonMap("debug@4.4.1", new ResolvedNode(leaf, emptyMap())));

        assertThat(new YarnBerryLockWriter().write(graph, "10c0", 8, CHECKSUMS)).contains(
                "  dependencies:\n" +
                "    ms: \"npm:^2.1.3\"\n" +
                "  peerDependenciesMeta:\n" +
                "    supports-color:\n" +
                "      optional: true\n" +
                "  checksum: ");
    }

    @Test
    void nonBooleanPeerMetaDefers() {
        ObjectNode meta = JsonNodeFactory.instance.objectNode();
        meta.putObject("x").put("optional", "yes");
        VersionManifest plugin = manifestWithPeers("plugin", "1.0.0", null, singletonMap("react", "^18.0.0"), meta);
        ResolutionGraph graph = new ResolutionGraph(
                singletonList(new ResolutionGraph.Importer("", "app", "1.0.0",
                        singletonMap("dependencies", singletonMap("plugin", "^1.0.0")), singletonMap("plugin", "1.0.0"))),
                singletonMap("plugin@1.0.0", new ResolvedNode(plugin, emptyMap())));

        assertThatExceptionOfType(EngineFailure.class)
                .isThrownBy(() -> new YarnBerryLockWriter().write(graph, "10c0", 8, CHECKSUMS));
    }

    @Test
    void binBearingManifestDefers() {
        VersionManifest withBin = buildManifest("cli", "1.0.0", null, TextNode.valueOf("cli.js"));
        ResolutionGraph graph = new ResolutionGraph(
                singletonList(new ResolutionGraph.Importer("", "app", "1.0.0",
                        singletonMap("dependencies", singletonMap("cli", "^1.0.0")), singletonMap("cli", "1.0.0"))),
                singletonMap("cli@1.0.0", new ResolvedNode(withBin, emptyMap())));

        assertThatExceptionOfType(EngineFailure.class)
                .isThrownBy(() -> new YarnBerryLockWriter().write(graph, "10c0", 8, CHECKSUMS));
    }

    @Test
    void unsupportedCacheKeyDefers() {
        ResolutionGraph graph = new ResolutionGraph(
                singletonList(new ResolutionGraph.Importer("", "app", "1.0.0", emptyMap(), emptyMap())),
                emptyMap());
        assertThatExceptionOfType(EngineFailure.class)
                .isThrownBy(() -> new YarnBerryLockWriter().write(graph, "9", 8, CHECKSUMS));
    }

    @Test
    void workspaceImporterDefers() {
        ResolutionGraph graph = new ResolutionGraph(
                singletonList(new ResolutionGraph.Importer("packages/app", "app", "1.0.0", emptyMap(), emptyMap())),
                emptyMap());
        assertThatExceptionOfType(EngineFailure.class)
                .isThrownBy(() -> new YarnBerryLockWriter().write(graph, "10c0", 8, CHECKSUMS));
    }

    // --- builders ---------------------------------------------------------

    private static String app(String name, Map<String, String> dependencies) {
        StringBuilder deps = new StringBuilder();
        for (Map.Entry<String, String> e : dependencies.entrySet()) {
            if (deps.length() > 0) {
                deps.append(',');
            }
            deps.append('"').append(e.getKey()).append("\":\"").append(e.getValue()).append('"');
        }
        return "{\"name\":\"" + name + "\",\"version\":\"1.0.0\",\"dependencies\":{" + deps + "}}";
    }

    private static Map<String, ResolvedNode> nodes(ResolvedNode... resolved) {
        Map<String, ResolvedNode> map = new LinkedHashMap<>();
        for (ResolvedNode node : resolved) {
            map.put(node.getName() + "@" + node.getVersion(), node);
        }
        return map;
    }

    private static VersionManifest leaf(String name, String version) {
        return buildManifest(name, version, null, null);
    }

    private static VersionManifest buildManifest(String name, String version,
                                            @Nullable Map<String, String> deps, @Nullable JsonNode bin) {
        VersionManifest.Dist dist = new VersionManifest.Dist(
                "https://r/" + name + "/-/" + name + "-" + version + ".tgz", null, "sha512-" + name + "-" + version);
        return new VersionManifest(name, version, null, null, deps, null, null, null, bin, null, null, null, null,
                null, null, null, null, null, dist, null, null, null);
    }

    private static VersionManifest manifestWithPeers(String name, String version, @Nullable Map<String, String> deps,
                                            @Nullable Map<String, String> peers, @Nullable JsonNode meta) {
        VersionManifest.Dist dist = new VersionManifest.Dist(
                "https://r/" + name + "/-/" + name + "-" + version + ".tgz", null, "sha512-" + name + "-" + version);
        return new VersionManifest(name, version, null, null, deps, null, peers, meta, null, null, null, null, null,
                null, null, null, null, null, dist, null, null, null);
    }

    private static final class FakeRegistry implements Registry {
        final Map<String, Set<String>> versionsByName = new HashMap<>();
        final Map<String, VersionManifest> manifests = new HashMap<>();

        FakeRegistry add(String name, String version, Map<String, String> deps) {
            versionsByName.computeIfAbsent(name, k -> new TreeSet<>()).add(version);
            manifests.put(name + "@" + version, buildManifest(name, version, deps.isEmpty() ? null : deps, null));
            return this;
        }

        @Override
        public Set<String> versions(String name) {
            return versionsByName.getOrDefault(name, emptySet());
        }

        @Override
        public VersionManifest manifest(String name, String version) {
            return manifests.get(name + "@" + version);
        }
    }
}
