/*
 * Copyright 2026 the original author or authors.
 *
 * Licensed under the Moderne Source Available License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://docs.moderne.io/licensing/moderne-source-available-license
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Command goexportdata writes the export data for a set of packages into a Go
// package a recipe module embeds, so its templates attribute against the real
// API on machines that cannot reach a module proxy. Run it where the packages
// resolve; commit what it writes. See doc/recipe-authoring.md: Shipped export data.
//
//	goexportdata -o internal/exportdata encoding/json/jsontext github.com/pkg/errors
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/openrewrite/rewrite/rewrite-go/pkg/exportdata"
)

const (
	blobDir  = "blobs"
	shimFile = "exportdata.go"
)

func main() {
	out := flag.String("o", "", "directory to write the generated package into")
	dir := flag.String("C", ".", "module directory the import paths resolve in")
	pkg := flag.String("pkg", "", "name of the generated package (default: the -o directory's name)")
	flag.Parse()

	if *out == "" || flag.NArg() == 0 {
		fmt.Fprintf(os.Stderr, "usage: goexportdata -o <dir> [-C <module dir>] [-pkg <name>] <import path>...\n")
		os.Exit(2)
	}
	if err := generate(*dir, *out, flag.Args(), *pkg); err != nil {
		fmt.Fprintln(os.Stderr, "goexportdata:", err)
		os.Exit(1)
	}
}

func generate(moduleDir, outDir string, importPaths []string, pkgName string) error {
	if pkgName == "" {
		pkgName = filepath.Base(outDir)
	}
	if !token.IsIdentifier(pkgName) || token.IsKeyword(pkgName) {
		return fmt.Errorf("%q is not a usable package name; pass -pkg", pkgName)
	}
	// The shim embeds the whole directory, so a stale blob would keep shadowing
	// the toolchain for a path Paths no longer names.
	if err := os.RemoveAll(filepath.Join(outDir, blobDir)); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(outDir, blobDir), 0o755); err != nil {
		return err
	}
	for _, path := range importPaths {
		blob, err := exportDataFor(moduleDir, path)
		if err != nil {
			return fmt.Errorf("%s: %w", path, err)
		}
		name := filepath.Join(outDir, blobDir, filepath.FromSlash(exportdata.BlobName(path)))
		if err := os.MkdirAll(filepath.Dir(name), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(name, blob, 0o644); err != nil {
			return err
		}
	}
	return writeShim(outDir, importPaths, pkgName)
}

func exportDataFor(moduleDir, importPath string) ([]byte, error) {
	cmd := exec.Command("go", "list", "-export", "-f", "{{.Export}}", importPath)
	cmd.Dir = moduleDir
	// `go` reports progress on stderr while it downloads, which must stay out
	// of the one path stdout carries.
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("go list -export: %w: %s", err, bytes.TrimSpace(stderr.Bytes()))
	}
	archivePath := strings.TrimSpace(string(out))
	if archivePath == "" {
		return nil, fmt.Errorf("go list reported no export data")
	}
	archive, err := os.ReadFile(archivePath)
	if err != nil {
		return nil, err
	}
	return exportdata.Pack(archive)
}

var shimTemplate = template.Must(template.New("shim").Parse(`// Code generated by goexportdata. DO NOT EDIT.

package {{.Package}}

import (
	"embed"
	"io/fs"
)

//go:embed {{.BlobDir}}
var blobs embed.FS

// FS holds the export data for Paths, ready to hand to a template's
// ExportData option.
var FS, _ = fs.Sub(blobs, "{{.BlobDir}}")

// Paths are the import paths FS covers, for exportdata.Verify to check.
var Paths = []string{
{{- range .Paths}}
	{{printf "%q" .}},
{{- end}}
}
`))

func writeShim(outDir string, importPaths []string, pkgName string) error {
	var buf bytes.Buffer
	err := shimTemplate.Execute(&buf, struct {
		Package string
		BlobDir string
		Paths   []string
	}{pkgName, blobDir, importPaths})
	if err != nil {
		return err
	}
	src, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(outDir, shimFile), src, 0o644)
}
