{
 "title": "Rewrite Java",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Java Parsing Cumulative Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "rewrite_parse_seconds_sum", "legendFormat": "{{step}}" }
   ]
  },
  {
   "title": "Java Parsing Cumulative Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "rewrite_parse_seconds_sum", "legendFormat": "{{step}}" }
   ]
  },
  {
   "title": "Java parsing by phase",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "operations (cumulative)" }
   ],
   "targets": [
    { "expr": "rewrite_parse_seconds_count", "legendFormat": "{{step}}" }
   ]
  },
  {
   "title": "GC Overhead",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "jvm_gc_overhead_percent", "legendFormat": "gc overhead" }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "process_cpu_usage" }
   ]
  }
 ]
}