/*
 * Copyright 2026 the original author or authors.
 * <p>
 * Licensed under the Moderne Source Available License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://docs.moderne.io/licensing/moderne-source-available-license
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openrewrite.python.internal.poetrylock;

import lombok.Value;
import lombok.With;
import org.jspecify.annotations.Nullable;

import java.util.List;
import java.util.Map;

/**
 * Typed document model of a poetry.lock file (lock-version 2.1). Values are stored as read
 * (poetry has already normalized them); {@link PoetryLockWriter} re-emits without reformatting.
 */
@Value
@With
public class PoetryLock {

    /**
     * The full {@code # This file is automatically @generated by Poetry X.Y.Z ...} header line,
     * preserved verbatim so a surgical edit keeps the generating tool's version.
     */
    String header;

    List<PoetryLockPackage> packages;

    /** Root project extras from the optional top-level {@code [extras]} table (rare). */
    @Nullable Map<String, List<String>> rootExtras;

    String lockVersion;
    @Nullable String pythonVersions;
    String contentHash;

    public @Nullable PoetryLockPackage getPackage(String name) {
        for (PoetryLockPackage pkg : packages) {
            if (pkg.getName().equals(name)) {
                return pkg;
            }
        }
        return null;
    }
}
