/*
 * Copyright 2026 the original author or authors.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openrewrite.gradle.internal;

import org.openrewrite.ExecutionContext;
import org.openrewrite.SourceFile;
import org.openrewrite.gradle.GradleParser;
import org.openrewrite.groovy.tree.G;
import org.openrewrite.java.tree.J;
import org.openrewrite.java.tree.Statement;
import org.openrewrite.tree.ParseError;

import java.util.function.Function;

public final class GradleParseUtils {
    private GradleParseUtils() {
    }

    /**
     * Parse a constant, valid Gradle Groovy snippet whose first statement is a method invocation (e.g. a
     * {@code project(...)} or {@code version { }} template generated by a recipe) and return that invocation.
     *
     * @param ctx     the execution context to parse within
     * @param snippet the Gradle Groovy snippet; its first statement must be a {@link J.MethodInvocation}
     * @return the first statement parsed as a {@link J.MethodInvocation}
     * @throws IllegalStateException if the snippet fails to parse or its first statement is not a method invocation
     */
    public static J.MethodInvocation parseMethodInvocation(ExecutionContext ctx, String snippet) {
        G.CompilationUnit cu = GradleParser.builder().build()
                .parse(ctx, snippet)
                .findFirst()
                .map(requireParsed(G.CompilationUnit.class))
                .orElseThrow(() -> new IllegalStateException("Unable to parse Gradle snippet: " + snippet));
        Statement first = cu.getStatements().get(0);
        if (!(first instanceof J.MethodInvocation)) {
            throw new IllegalStateException("Expected a method invocation, got " + first.getClass().getName());
        }
        return (J.MethodInvocation) first;
    }

    /**
     * A mapping {@link Function} for use in a {@code stream.map(...)} / {@code optional.map(...)} chain over the
     * result of parsing a generated Gradle code snippet, in place of {@code SomeType.class::cast}.
     * <p>
     * Recipes parse constant, valid Gradle snippets, so a {@link ParseError} here means the underlying Groovy or
     * Kotlin parser threw while parsing the snippet. Rethrow that real cause — its
     * {@link org.openrewrite.ParseExceptionResult} carries the full stack trace — instead of letting the cast mask
     * it with an opaque {@link ClassCastException} ("Cannot cast ParseError to ...").
     *
     * @param expected the {@link SourceFile} subtype the snippet is expected to parse into
     * @return a function that casts to {@code expected}, or throws with the underlying parse failure as its cause
     */
    public static <S extends SourceFile> Function<SourceFile, S> requireParsed(Class<S> expected) {
        return sourceFile -> {
            if (sourceFile instanceof ParseError) {
                throw new IllegalStateException(
                        "Failed to parse generated Gradle code as " + expected.getSimpleName(),
                        ((ParseError) sourceFile).toException());
            }
            return expected.cast(sourceFile);
        };
    }
}
