@file:Suppress("UnstableApiUsage")

import com.gradle.develocity.agent.gradle.test.ImportJUnitXmlReports
import com.gradle.develocity.agent.gradle.test.JUnitXmlDialect
import com.hierynomus.gradle.license.tasks.LicenseCheck
import com.hierynomus.gradle.license.tasks.LicenseFormat
import nl.javadude.gradle.plugins.license.License
import java.util.Calendar

plugins {
    id("org.openrewrite.build.language-library")
    id("org.openrewrite.build.moderne-source-available-license")
    id("jvm-test-suite")
}

dependencies {
    api(project(":rewrite-core"))
    api(project(":rewrite-java"))

    api("org.jetbrains:annotations:latest.release")
    api("com.fasterxml.jackson.core:jackson-annotations")

    implementation("io.moderne:jsonrpc:latest.integration")

    compileOnly(project(":rewrite-test"))

    testImplementation(project(":rewrite-test"))
    testImplementation("io.moderne:jsonrpc:latest.integration")
    testRuntimeOnly(project(":rewrite-java-21"))
}

tasks.withType<Javadoc>().configureEach {
    (options as StandardJavadocDocletOptions).addStringOption("Xdoclint:none", "-quiet")
    exclude("**/G.java")
}

// Test fixtures for the GoMod conformance corpus are .gomod / .gosum / .json
// files; none of these formats accept a leading license header. The default
// license task excludes all .go files (the vendored Go staged into main
// resources must never be stamped); first-party Go sources are instead managed
// by the dedicated licenseGo / licenseFormatGo tasks below, which scope precisely
// to our own code. vendor/ (third-party) and testdata/ (sample user programs)
// are never stamped.
configure<nl.javadude.gradle.plugins.license.LicenseExtension> {
    excludePatterns.addAll(listOf(
        "**/*.gomod",
        "**/*.gosum",
        "**/*.json",
        "**/*.go",
        "**/go.mod",
        "**/go.sum",
        "**/vendor/**",
    ))

    // A /* */ header style for Go that tolerates leading build-constraint lines.
    // Go requires `//go:build` (and legacy `// +build`) to precede the package
    // clause and allows only line comments and blank lines before them, so a
    // block-comment license header must come *after* the constraint. skipLinePattern
    // keeps that leading line in place and applies/detects the header below it; for
    // files without a constraint it behaves exactly like SLASHSTAR_STYLE.
    headerDefinitions.create("go_slashstar_style") {
        withFirstLine("/*")
        withBeforeEachLine(" * ")
        withEndLine(" */")
        withSkipLinePattern("^//\\s*(go:build|\\+build).*\$")
        withFirstLineDetectionDetectionPattern("(\\s|\\t)*/\\*.*\$")
        withLastLineDetectionDetectionPattern(".*\\*/(\\s|\\t)*\$")
        multiline()
        withNoBlankLines()
    }
}

// First-party Go sources use a blank-line header variant (not the <p> form used
// by .java/.cs/.ts), so they get their own header template. The shared
// LicenseExtension excludes **/*.go globally; that exclude is applied to every
// License task via conventionMapping, i.e. only when the task does not set its
// own excludes. These tasks therefore set excludes explicitly to override it and
// actually scan our Go — while still skipping vendor/ and testdata/.
val goLicenseHeader = file("${rootProject.projectDir}/gradle/msalLicenseHeaderGo.txt")
val goLicenseExcludes = listOf("**/vendor/**", "**/testdata/**")
fun License.configureForFirstPartyGo() {
    group = "license"
    source = fileTree(projectDir) { include("cmd/**/*.go", "pkg/**/*.go", "test/**/*.go", "*.go") }
    setExcludes(goLicenseExcludes)
    header = goLicenseHeader
    mapping("go", "go_slashstar_style")
    ext["year"] = Calendar.getInstance().get(Calendar.YEAR)
}

val licenseGo by tasks.registering(LicenseCheck::class) {
    description = "Check license headers on first-party Go files"
    configureForFirstPartyGo()
}

val licenseFormatGo by tasks.registering(LicenseFormat::class) {
    description = "Apply license headers to first-party Go files"
    configureForFirstPartyGo()
}

tasks.named("licenseMain") { dependsOn(licenseGo) }
tasks.named("licenseFormatMain") { dependsOn(licenseFormatGo) }

// ============================================
// Go RPC Source Packaging
// ============================================
// Ships the Go RPC server source (cmd/rpc + the complete pkg/ tree +
// vendored dependencies) inside the rewrite-go JAR under
// META-INF/rewrite-go/src/. The Moderne CLI extracts these via
// GoRpcSourceExtractor and runs `go build` against them to launch the RPC
// server. Vendoring keeps the build hermetic (no network on the consumer
// side) and is regenerated by Gradle — vendor/ is gitignored, not committed.
//
// All pkg/ submodules are shipped — not just those reachable from
// ./cmd/rpc — so that Moderne CLI can regenerate a custom RPC main that
// links additional recipe modules (which may pull in any pkg/ subpackage)
// without us needing to keep an allowlist in sync.

val goRpcSourceStaging: Provider<Directory> =
    layout.buildDirectory.dir("generated/go-rpc-src")

val goModVendor = tasks.register<Exec>("goModVendor") {
    group = "golang"
    description = "Populate vendor/ via `go mod vendor` for source packaging"

    workingDir = projectDir
    commandLine("go", "mod", "vendor")

    inputs.file("go.mod").withPathSensitivity(PathSensitivity.RELATIVE)
    inputs.file("go.sum").withPathSensitivity(PathSensitivity.RELATIVE)
    outputs.dir(projectDir.resolve("vendor"))
}

val prepareGoRpcSources = tasks.register<Sync>("prepareGoRpcSources") {
    group = "golang"
    description = "Stage Go RPC sources + vendored deps under META-INF/rewrite-go/src/"

    dependsOn(goModVendor)

    into(goRpcSourceStaging.map { it.dir("META-INF/rewrite-go/src") })

    from(projectDir) {
        include("go.mod", "go.sum")
        include("cmd/rpc/**/*.go")
        include("pkg/**/*.go")
        include("vendor/**")
        exclude("**/*_test.go")
        exclude("**/testdata/**")
    }
    from(rootProject.file("LICENSE"))
}

sourceSets.named("main") {
    resources.srcDir(goRpcSourceStaging)
}

listOf("processResources", "sourcesJar", "licenseMain", "assemble").forEach {
    tasks.named(it) {
        dependsOn(prepareGoRpcSources)
    }
}

val goBuild = tasks.register<Exec>("goBuild") {
    workingDir = projectDir
    // Use relative path to avoid absolute paths in cache key (Exec args are cache inputs)
    commandLine("go", "build", "-o", layout.buildDirectory.file("rewrite-go-rpc").get().asFile.relativeTo(projectDir).path, "./cmd/rpc")

    inputs.files(fileTree(projectDir) {
        include("**/*.go")
        include("go.mod")
        include("go.sum")
        exclude("build/**")
        // vendor/ is reproducible from go.mod/go.sum (already inputs) and is
        // declared as goModVendor's output; excluding it avoids a spurious
        // implicit-dependency validation error from Gradle.
        exclude("vendor/**")
    }).withPathSensitivity(PathSensitivity.RELATIVE)
    outputs.file(layout.buildDirectory.file("rewrite-go-rpc"))
}

testing {
    suites {
        register<JvmTestSuite>("integTest") {
            useJUnitJupiter()

            targets {
                all {
                    testTask.configure {
                        dependsOn(goBuild)
                    }
                }
            }

            dependencies {
                implementation(project())
                implementation(project(":rewrite-java-21"))
                implementation(project(":rewrite-test"))
                implementation("org.assertj:assertj-core:latest.release")
            }
        }
    }
}

// ============================================
// Go Test Support Tasks
// ============================================

// Configuration to collect classpath for the Java RPC server
val javaRpcClasspath by configurations.creating {
    isCanBeConsumed = false
    isCanBeResolved = true
    extendsFrom(configurations.getByName("runtimeClasspath"))
}

dependencies {
    javaRpcClasspath(project(":rewrite-maven"))
}

// Task to generate classpath file for Java RPC server testing from Go
val generateTestClasspath by tasks.registering {
    group = "golang"
    description = "Generate classpath file for Java RPC server (used by Go tests)"

    val outputFile = file("test-classpath.txt")
    outputs.file(outputFile)

    dependsOn(tasks.named("compileJava"))

    doLast {
        val classpath = (
            javaRpcClasspath.files +
            tasks.named("compileJava").get().outputs.files +
            tasks.named("processResources").get().outputs.files
        ).distinctBy { it.absolutePath }
         .joinToString(File.pathSeparator) { it.absolutePath }
        outputFile.writeText(classpath)
        logger.lifecycle("Generated test classpath to ${outputFile.absolutePath}")
    }
}

val junitXmlFile = file("build/test-results/gotest/junit.xml")

val goTest = tasks.register<Exec>("goTest") {
    group = "verification"
    description = "Run Go tests"

    workingDir = projectDir
    commandLine("go", "run", "gotest.tools/gotestsum@latest",
        "--junitfile", junitXmlFile.relativeTo(projectDir).path,
        "--format", "standard-verbose",
        "--", "-count=1", "./test/...")

    dependsOn(generateTestClasspath)

    inputs.files(fileTree(projectDir) {
        include("**/*.go")
        include("go.mod")
        include("go.sum")
        exclude("build/**")
        exclude("vendor/**")
    }).withPathSensitivity(PathSensitivity.RELATIVE)
    inputs.file(file("test-classpath.txt"))
    outputs.file(junitXmlFile)
    outputs.cacheIf { true }
}

ImportJUnitXmlReports.register(tasks, goTest, JUnitXmlDialect.GENERIC)

tasks.named("check") {
    dependsOn(goTest)
}
