/*
 * Copyright 2026 the original author or authors.
 * <p>
 * Licensed under the Moderne Source Available License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://docs.moderne.io/licensing/moderne-source-available-license
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openrewrite.javascript.internal.lock.resolve;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.jspecify.annotations.Nullable;
import org.openrewrite.javascript.internal.LockFileRegeneration.Reason;
import org.openrewrite.javascript.internal.lock.EngineFailure;
import org.openrewrite.javascript.internal.registry.VersionManifest;

import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.regex.Pattern;

/**
 * Serializes a {@link ResolutionGraph} to a Yarn Berry {@code yarn.lock}, byte-for-byte identical to what a real
 * {@code yarn install} (yarn 4.x, {@code cacheKey: 10c0}) would write. The lock is a flat map: a fixed header, the
 * {@code __metadata} block, one workspace importer entry, and one entry per resolved node keyed by its merged,
 * sorted {@code name@npm:range} descriptor(s). Each registry entry carries the {@code checksum} reproduced by
 * {@code BerryZipChecksum} from the tarball (threaded in via {@link Checksums}). A satisfied {@code peerDependencies}
 * surface is reproduced too — its declaration and any {@code peerDependenciesMeta} copied verbatim (the graph proved
 * the peers already resolved), sitting between {@code dependencies} and {@code checksum} and quoted by yarn's own
 * syml stringifier. The field order and quoting mirror {@code YarnBerryLockPatcher}. Anything not yet proven
 * byte-exact — a fork, a manifest surfacing another lock field, a non-10c0 cacheKey — fails loud rather than emit a
 * wrong lock.
 */
public final class YarnBerryLockWriter {

    private static final ObjectMapper JSON = new ObjectMapper();

    /** Yarn's syml stringifier emits a scalar raw when it matches this, else JSON-quotes it (yarnpkg/parsers). */
    private static final Pattern SYML_SAFE = Pattern.compile(
            "^(?![-?:,\\]\\[{}#&*!|>'\"%@` \\t\\r\\n]).([ \\t]*(?![,\\]\\[{}:# \\t\\r\\n]).)*$");

    private static final String HEADER =
            "# This file is generated by running \"yarn install\" inside your project.\n" +
            "# Manual changes might be lost - proceed with caution!\n";

    /** Reproduces a resolved node's {@code <cacheKey>/<sha512>} checksum from its registry tarball. */
    @FunctionalInterface
    public interface Checksums {
        String checksum(String name, String version, String tarballUrl);
    }

    public String write(ResolutionGraph graph, String cacheKey, int metadataVersion, Checksums checksums) {
        if (!"10c0".equals(cacheKey)) {
            throw new EngineFailure(Reason.CHECKSUM_UNAVAILABLE, null,
                    "yarn berry cacheKey " + cacheKey + " is not a validated checksum format (only 10c0 so far)");
        }
        ResolutionGraph.Importer root = singleRootImporter(graph);
        requireNoFork(graph);
        Map<String, Set<String>> descriptors = collectDescriptors(graph);

        // Berry sorts every entry by its descriptor key; __metadata is pinned first and emitted separately.
        TreeMap<String, String> entries = new TreeMap<>();
        entries.put(importerDescriptor(root), importerEntry(root));
        for (Map.Entry<String, ResolvedNode> e : graph.getNodes().entrySet()) {
            ResolvedNode node = e.getValue();
            Set<String> ranges = descriptors.get(e.getKey());
            if (ranges == null || ranges.isEmpty()) {
                throw new EngineFailure(Reason.RESOLUTION_REQUIRED, node.getName(),
                        node.getName() + "@" + node.getVersion() + " resolved but no descriptor requires it");
            }
            entries.put(String.join(", ", ranges), registryEntry(node, ranges, checksums));
        }

        StringBuilder out = new StringBuilder(HEADER);
        out.append("\n__metadata:\n  version: ").append(metadataVersion)
                .append("\n  cacheKey: ").append(cacheKey).append('\n');
        for (String body : entries.values()) {
            out.append('\n').append(body);
        }
        return out.toString();
    }

    // --- workspace importer entry -----------------------------------------

    private static String importerDescriptor(ResolutionGraph.Importer root) {
        if (root.getName() == null) {
            throw new EngineFailure(Reason.RESOLUTION_REQUIRED, null, "workspace importer manifest declares no name");
        }
        String dir = root.getDir().isEmpty() ? "." : root.getDir();
        return root.getName() + "@workspace:" + dir;
    }

    private static String importerEntry(ResolutionGraph.Importer root) {
        String descriptor = importerDescriptor(root);
        StringBuilder body = new StringBuilder();
        body.append('"').append(descriptor).append("\":\n");
        body.append("  version: 0.0.0-use.local\n");
        body.append("  resolution: \"").append(descriptor).append("\"\n");
        for (Map.Entry<String, Map<String, String>> scope : root.getDeclared().entrySet()) {
            if (!"dependencies".equals(scope.getKey())) {
                throw new EngineFailure(Reason.RESOLUTION_REQUIRED, null,
                        "workspace importer declares " + scope.getKey() + " (only prod dependencies are resolved today)");
            }
            appendDependencies(body, scope.getValue());
        }
        body.append("  languageName: unknown\n");
        body.append("  linkType: soft\n");
        return body.toString();
    }

    // --- registry entry ---------------------------------------------------

    private static String registryEntry(ResolvedNode node, Set<String> descriptors, Checksums checksums) {
        VersionManifest m = node.getManifest();
        requireEmittable(m);
        VersionManifest.Dist dist = m.getDist();
        String tarball = dist == null ? null : dist.getTarball();
        if (tarball == null) {
            throw new EngineFailure(Reason.UNSUPPORTED_ENTRY_TYPE, m.getName(),
                    m.getName() + "@" + m.getVersion() + " has no registry tarball to checksum");
        }

        StringBuilder body = new StringBuilder();
        body.append('"').append(String.join(", ", descriptors)).append("\":\n");
        body.append("  version: ").append(m.getVersion()).append('\n');
        body.append("  resolution: \"").append(m.getName()).append("@npm:").append(m.getVersion()).append("\"\n");
        appendDependencies(body, m.getDependencies());
        appendPeerDependencies(body, m.getPeerDependencies());
        appendPeerDependenciesMeta(body, m.getPeerDependenciesMeta());
        body.append("  checksum: ").append(checksums.checksum(m.getName(), m.getVersion(), tarball)).append('\n');
        body.append("  languageName: node\n");
        body.append("  linkType: hard\n");
        return body.toString();
    }

    /**
     * The writer reproduces version/resolution/dependencies/peerDependencies/peerDependenciesMeta/checksum; the peer
     * surface is recorded verbatim (the graph proved the peers already satisfied). Any other lock-surfaced field
     * reshapes the entry in a way not yet byte-verified, so it defers.
     */
    private static void requireEmittable(VersionManifest m) {
        deferIf(m, "optionalDependencies", notEmpty(m.getOptionalDependencies()));
        deferIf(m, "bin", m.getBin() != null);
        deferIf(m, "os", m.getOs() != null);
        deferIf(m, "cpu", m.getCpu() != null);
        deferIf(m, "libc", m.getLibc() != null);
        deferIf(m, "bundleDependencies", m.getBundleDependencies() != null);
    }

    private static void deferIf(VersionManifest m, String field, boolean present) {
        if (present) {
            throw new EngineFailure(Reason.RESOLUTION_REQUIRED, m.getName(),
                    m.getName() + "@" + m.getVersion() + " declares " + field + " (berry entry shape not yet reproduced)");
        }
    }

    // --- descriptors ------------------------------------------------------

    /**
     * For each resolved node, the merged set of {@code name@npm:range} descriptors: every range — the importer's
     * declared one and every transitive requirer's — that resolved to this exact {@code name@version}. Sorted so a
     * merged key is stable.
     */
    private static Map<String, Set<String>> collectDescriptors(ResolutionGraph graph) {
        Map<String, Set<String>> byNode = new TreeMap<>();
        for (ResolutionGraph.Importer imp : graph.getImporters()) {
            for (Map<String, String> scope : imp.getDeclared().values()) {
                for (Map.Entry<String, String> dep : scope.entrySet()) {
                    add(byNode, dep.getKey(), imp.getResolved().get(dep.getKey()), dep.getValue());
                }
            }
        }
        for (ResolvedNode node : graph.getNodes().values()) {
            Map<String, String> deps = node.getManifest().getDependencies();
            if (deps != null) {
                for (Map.Entry<String, String> dep : deps.entrySet()) {
                    add(byNode, dep.getKey(), node.getResolvedEdges().get(dep.getKey()), dep.getValue());
                }
            }
        }
        return byNode;
    }

    private static void add(Map<String, Set<String>> byNode, String name, @Nullable String version, String range) {
        if (version != null) {
            byNode.computeIfAbsent(ResolutionGraph.key(name, version), k -> new TreeSet<>())
                    .add(name + "@npm:" + range);
        }
    }

    // --- helpers ----------------------------------------------------------

    /** Emit a sorted {@code dependencies:} block ({@code name: "npm:range"}, scoped keys quoted); omit if empty. */
    private static void appendDependencies(StringBuilder body, @Nullable Map<String, String> deps) {
        if (notEmpty(deps)) {
            body.append("  dependencies:\n");
            for (Map.Entry<String, String> dep : new TreeMap<>(deps).entrySet()) {
                String key = dep.getKey().startsWith("@") ? "\"" + dep.getKey() + "\"" : dep.getKey();
                body.append("    ").append(key).append(": \"npm:").append(dep.getValue()).append("\"\n");
            }
        }
    }

    /**
     * Emit a sorted {@code peerDependencies:} block; unlike {@code dependencies}, the value is the raw range with no
     * {@code npm:} prefix, quoted only when yarn's syml stringifier would ({@link #symlScalar}).
     */
    private static void appendPeerDependencies(StringBuilder body, @Nullable Map<String, String> peers) {
        if (notEmpty(peers)) {
            body.append("  peerDependencies:\n");
            for (Map.Entry<String, String> peer : new TreeMap<>(peers).entrySet()) {
                String key = peer.getKey().startsWith("@") ? "\"" + peer.getKey() + "\"" : peer.getKey();
                body.append("    ").append(key).append(": ").append(symlScalar(peer.getValue())).append('\n');
            }
        }
    }

    /**
     * Emit a sorted {@code peerDependenciesMeta:} block. Yarn reduces each entry to {@code {optional: <boolean>}}, so
     * a manifest entry that is not exactly that shape defers rather than guess its normalization.
     */
    private static void appendPeerDependenciesMeta(StringBuilder body, @Nullable JsonNode meta) {
        if (meta == null || !meta.isObject() || meta.size() == 0) {
            return;
        }
        List<String> names = new ArrayList<>();
        meta.fieldNames().forEachRemaining(names::add);
        Collections.sort(names);
        body.append("  peerDependenciesMeta:\n");
        for (String name : names) {
            JsonNode entry = meta.get(name);
            JsonNode optional = entry == null ? null : entry.get("optional");
            if (entry == null || !entry.isObject() || optional == null || !optional.isBoolean()) {
                throw new EngineFailure(Reason.RESOLUTION_REQUIRED, name,
                        "peerDependenciesMeta." + name + " is not a simple {optional: <boolean>} (berry meta shape not reproduced)");
            }
            String key = name.startsWith("@") ? "\"" + name + "\"" : name;
            body.append("    ").append(key).append(":\n");
            body.append("      optional: ").append(optional.booleanValue()).append('\n');
        }
    }

    /** A scalar as yarn's syml stringifier writes it: raw when {@link #SYML_SAFE} admits it, else JSON-quoted. */
    private static String symlScalar(String value) {
        if (SYML_SAFE.matcher(value).matches()) {
            return value;
        }
        try {
            return JSON.writeValueAsString(value);
        } catch (JsonProcessingException e) {
            throw new EngineFailure(Reason.RESOLUTION_REQUIRED, null, "could not serialize peer range " + value);
        }
    }

    /** Berry lists one flat entry per resolved {@code (name, version)}; a name at two versions is a fork, deferred. */
    private static void requireNoFork(ResolutionGraph graph) {
        Map<String, Set<String>> versionsByName = new TreeMap<>();
        for (ResolvedNode node : graph.getNodes().values()) {
            versionsByName.computeIfAbsent(node.getName(), k -> new LinkedHashSet<>()).add(node.getVersion());
        }
        for (Map.Entry<String, Set<String>> e : versionsByName.entrySet()) {
            if (e.getValue().size() > 1) {
                throw new EngineFailure(Reason.RESOLUTION_REQUIRED, e.getKey(),
                        e.getKey() + " forks (" + e.getValue() + "); yarn berry fork layout is not yet reproduced");
            }
        }
    }

    private static boolean notEmpty(@Nullable Map<String, String> m) {
        return m != null && !m.isEmpty();
    }

    private static ResolutionGraph.Importer singleRootImporter(ResolutionGraph graph) {
        if (graph.getImporters().size() != 1) {
            throw new EngineFailure(Reason.RESOLUTION_REQUIRED, null,
                    "only a single-importer project is reproduced (found " + graph.getImporters().size() + ")");
        }
        ResolutionGraph.Importer root = graph.getImporters().get(0);
        if (!root.getDir().isEmpty()) {
            throw new EngineFailure(Reason.RESOLUTION_REQUIRED, null,
                    "only a root importer is reproduced (found importer dir '" + root.getDir() + "')");
        }
        return root;
    }
}
