/*
 * Copyright 2026 the original author or authors.
 *
 * Licensed under the Moderne Source Available License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://docs.moderne.io/licensing/moderne-source-available-license
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by hand for J interface conformance — keep in sync
// with the J types declared in j.go and go.go. Each J node satisfies
// the polymorphic accessors GetID / WithID / GetPrefix / GetMarkers,
// mirroring rewrite-java's J.getId() / J.withId() / J.getPrefix() /
// J.getMarkers().
//
// WithID returns a fresh instance, which is what the visitor framework's
// pointer-identity change detection requires. Prefix/marker withers remain
// typed per node in j.go / go.go.
package tree

import "github.com/google/uuid"

func (n *Annotation) GetID() uuid.UUID { return n.ID }
func (n *Annotation) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *Annotation) GetPrefix() Space    { return n.Prefix }
func (n *Annotation) GetMarkers() Markers { return n.Markers }

func (n *ArrayAccess) GetID() uuid.UUID { return n.ID }
func (n *ArrayAccess) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *ArrayAccess) GetPrefix() Space    { return n.Prefix }
func (n *ArrayAccess) GetMarkers() Markers { return n.Markers }

func (n *ArrayDimension) GetID() uuid.UUID { return n.ID }
func (n *ArrayDimension) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *ArrayDimension) GetPrefix() Space    { return n.Prefix }
func (n *ArrayDimension) GetMarkers() Markers { return n.Markers }

func (n *ArrayType) GetID() uuid.UUID { return n.ID }
func (n *ArrayType) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *ArrayType) GetPrefix() Space    { return n.Prefix }
func (n *ArrayType) GetMarkers() Markers { return n.Markers }

func (n *Assignment) GetID() uuid.UUID { return n.ID }
func (n *Assignment) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *Assignment) GetPrefix() Space    { return n.Prefix }
func (n *Assignment) GetMarkers() Markers { return n.Markers }

func (n *AssignmentOperation) GetID() uuid.UUID { return n.ID }
func (n *AssignmentOperation) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *AssignmentOperation) GetPrefix() Space    { return n.Prefix }
func (n *AssignmentOperation) GetMarkers() Markers { return n.Markers }

func (n *Binary) GetID() uuid.UUID { return n.ID }
func (n *Binary) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *Binary) GetPrefix() Space    { return n.Prefix }
func (n *Binary) GetMarkers() Markers { return n.Markers }

func (n *Block) GetID() uuid.UUID { return n.ID }
func (n *Block) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *Block) GetPrefix() Space    { return n.Prefix }
func (n *Block) GetMarkers() Markers { return n.Markers }

func (n *Break) GetID() uuid.UUID { return n.ID }
func (n *Break) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *Break) GetPrefix() Space    { return n.Prefix }
func (n *Break) GetMarkers() Markers { return n.Markers }

func (n *Case) GetID() uuid.UUID { return n.ID }
func (n *Case) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *Case) GetPrefix() Space    { return n.Prefix }
func (n *Case) GetMarkers() Markers { return n.Markers }

func (n *Channel) GetID() uuid.UUID { return n.ID }
func (n *Channel) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *Channel) GetPrefix() Space    { return n.Prefix }
func (n *Channel) GetMarkers() Markers { return n.Markers }

func (n *CommClause) GetID() uuid.UUID { return n.ID }
func (n *CommClause) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *CommClause) GetPrefix() Space    { return n.Prefix }
func (n *CommClause) GetMarkers() Markers { return n.Markers }

func (n *CompilationUnit) GetID() uuid.UUID { return n.ID }
func (n *CompilationUnit) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *CompilationUnit) GetPrefix() Space    { return n.Prefix }
func (n *CompilationUnit) GetMarkers() Markers { return n.Markers }

func (n *Composite) GetID() uuid.UUID { return n.ID }
func (n *Composite) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *Composite) GetPrefix() Space    { return n.Prefix }
func (n *Composite) GetMarkers() Markers { return n.Markers }

func (n *Continue) GetID() uuid.UUID { return n.ID }
func (n *Continue) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *Continue) GetPrefix() Space    { return n.Prefix }
func (n *Continue) GetMarkers() Markers { return n.Markers }

func (n *ControlParentheses) GetID() uuid.UUID { return n.ID }
func (n *ControlParentheses) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *ControlParentheses) GetPrefix() Space    { return n.Prefix }
func (n *ControlParentheses) GetMarkers() Markers { return n.Markers }

func (n *Defer) GetID() uuid.UUID { return n.ID }
func (n *Defer) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *Defer) GetPrefix() Space    { return n.Prefix }
func (n *Defer) GetMarkers() Markers { return n.Markers }

func (n *Else) GetID() uuid.UUID { return n.ID }
func (n *Else) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *Else) GetPrefix() Space    { return n.Prefix }
func (n *Else) GetMarkers() Markers { return n.Markers }

func (n *Empty) GetID() uuid.UUID { return n.ID }
func (n *Empty) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *Empty) GetPrefix() Space    { return n.Prefix }
func (n *Empty) GetMarkers() Markers { return n.Markers }

func (n *Fallthrough) GetID() uuid.UUID { return n.ID }
func (n *Fallthrough) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *Fallthrough) GetPrefix() Space    { return n.Prefix }
func (n *Fallthrough) GetMarkers() Markers { return n.Markers }

func (n *FieldAccess) GetID() uuid.UUID { return n.ID }
func (n *FieldAccess) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *FieldAccess) GetPrefix() Space    { return n.Prefix }
func (n *FieldAccess) GetMarkers() Markers { return n.Markers }

func (n *ForControl) GetID() uuid.UUID { return n.ID }
func (n *ForControl) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *ForControl) GetPrefix() Space    { return n.Prefix }
func (n *ForControl) GetMarkers() Markers { return n.Markers }

func (n *ForEachControl) GetID() uuid.UUID { return n.ID }
func (n *ForEachControl) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *ForEachControl) GetPrefix() Space    { return n.Prefix }
func (n *ForEachControl) GetMarkers() Markers { return n.Markers }

func (n *ForEachLoop) GetID() uuid.UUID { return n.ID }
func (n *ForEachLoop) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *ForEachLoop) GetPrefix() Space    { return n.Prefix }
func (n *ForEachLoop) GetMarkers() Markers { return n.Markers }

func (n *ForLoop) GetID() uuid.UUID { return n.ID }
func (n *ForLoop) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *ForLoop) GetPrefix() Space    { return n.Prefix }
func (n *ForLoop) GetMarkers() Markers { return n.Markers }

func (n *FuncType) GetID() uuid.UUID { return n.ID }
func (n *FuncType) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *FuncType) GetPrefix() Space    { return n.Prefix }
func (n *FuncType) GetMarkers() Markers { return n.Markers }

func (n *GoStmt) GetID() uuid.UUID { return n.ID }
func (n *GoStmt) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *GoStmt) GetPrefix() Space    { return n.Prefix }
func (n *GoStmt) GetMarkers() Markers { return n.Markers }

func (n *Goto) GetID() uuid.UUID { return n.ID }
func (n *Goto) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *Goto) GetPrefix() Space    { return n.Prefix }
func (n *Goto) GetMarkers() Markers { return n.Markers }

func (n *Identifier) GetID() uuid.UUID { return n.ID }
func (n *Identifier) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *Identifier) GetPrefix() Space    { return n.Prefix }
func (n *Identifier) GetMarkers() Markers { return n.Markers }

func (n *If) GetID() uuid.UUID { return n.ID }
func (n *If) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *If) GetPrefix() Space    { return n.Prefix }
func (n *If) GetMarkers() Markers { return n.Markers }

func (n *Import) GetID() uuid.UUID { return n.ID }
func (n *Import) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *Import) GetPrefix() Space    { return n.Prefix }
func (n *Import) GetMarkers() Markers { return n.Markers }

func (n *IndexList) GetID() uuid.UUID { return n.ID }
func (n *IndexList) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *IndexList) GetPrefix() Space    { return n.Prefix }
func (n *IndexList) GetMarkers() Markers { return n.Markers }

func (n *InterfaceType) GetID() uuid.UUID { return n.ID }
func (n *InterfaceType) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *InterfaceType) GetPrefix() Space    { return n.Prefix }
func (n *InterfaceType) GetMarkers() Markers { return n.Markers }

func (n *KeyValue) GetID() uuid.UUID { return n.ID }
func (n *KeyValue) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *KeyValue) GetPrefix() Space    { return n.Prefix }
func (n *KeyValue) GetMarkers() Markers { return n.Markers }

func (n *Label) GetID() uuid.UUID { return n.ID }
func (n *Label) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *Label) GetPrefix() Space    { return n.Prefix }
func (n *Label) GetMarkers() Markers { return n.Markers }

func (n *Literal) GetID() uuid.UUID { return n.ID }
func (n *Literal) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *Literal) GetPrefix() Space    { return n.Prefix }
func (n *Literal) GetMarkers() Markers { return n.Markers }

func (n *MapType) GetID() uuid.UUID { return n.ID }
func (n *MapType) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *MapType) GetPrefix() Space    { return n.Prefix }
func (n *MapType) GetMarkers() Markers { return n.Markers }

func (n *MethodDeclaration) GetID() uuid.UUID { return n.ID }
func (n *MethodDeclaration) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *MethodDeclaration) GetPrefix() Space    { return n.Prefix }
func (n *MethodDeclaration) GetMarkers() Markers { return n.Markers }

func (n *MethodInvocation) GetID() uuid.UUID { return n.ID }
func (n *MethodInvocation) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *MethodInvocation) GetPrefix() Space    { return n.Prefix }
func (n *MethodInvocation) GetMarkers() Markers { return n.Markers }

func (n *MultiAssignment) GetID() uuid.UUID { return n.ID }
func (n *MultiAssignment) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *MultiAssignment) GetPrefix() Space    { return n.Prefix }
func (n *MultiAssignment) GetMarkers() Markers { return n.Markers }

func (n *ParameterizedType) GetID() uuid.UUID { return n.ID }
func (n *ParameterizedType) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *ParameterizedType) GetPrefix() Space    { return n.Prefix }
func (n *ParameterizedType) GetMarkers() Markers { return n.Markers }

func (n *Parentheses) GetID() uuid.UUID { return n.ID }
func (n *Parentheses) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *Parentheses) GetPrefix() Space    { return n.Prefix }
func (n *Parentheses) GetMarkers() Markers { return n.Markers }

func (n *PointerType) GetID() uuid.UUID { return n.ID }
func (n *PointerType) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *PointerType) GetPrefix() Space    { return n.Prefix }
func (n *PointerType) GetMarkers() Markers { return n.Markers }

func (n *Return) GetID() uuid.UUID { return n.ID }
func (n *Return) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *Return) GetPrefix() Space    { return n.Prefix }
func (n *Return) GetMarkers() Markers { return n.Markers }

func (n *Send) GetID() uuid.UUID { return n.ID }
func (n *Send) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *Send) GetPrefix() Space    { return n.Prefix }
func (n *Send) GetMarkers() Markers { return n.Markers }

func (n *Slice) GetID() uuid.UUID { return n.ID }
func (n *Slice) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *Slice) GetPrefix() Space    { return n.Prefix }
func (n *Slice) GetMarkers() Markers { return n.Markers }

func (n *StatementExpression) GetID() uuid.UUID { return n.ID }
func (n *StatementExpression) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *StatementExpression) GetPrefix() Space    { return n.Prefix }
func (n *StatementExpression) GetMarkers() Markers { return n.Markers }

func (n *StructType) GetID() uuid.UUID { return n.ID }
func (n *StructType) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *StructType) GetPrefix() Space    { return n.Prefix }
func (n *StructType) GetMarkers() Markers { return n.Markers }

func (n *Switch) GetID() uuid.UUID { return n.ID }
func (n *Switch) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *Switch) GetPrefix() Space    { return n.Prefix }
func (n *Switch) GetMarkers() Markers { return n.Markers }

func (n *TypeCast) GetID() uuid.UUID { return n.ID }
func (n *TypeCast) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *TypeCast) GetPrefix() Space    { return n.Prefix }
func (n *TypeCast) GetMarkers() Markers { return n.Markers }

func (n *TypeDecl) GetID() uuid.UUID { return n.ID }
func (n *TypeDecl) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *TypeDecl) GetPrefix() Space    { return n.Prefix }
func (n *TypeDecl) GetMarkers() Markers { return n.Markers }

func (n *TypeList) GetID() uuid.UUID { return n.ID }
func (n *TypeList) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *TypeList) GetPrefix() Space    { return n.Prefix }
func (n *TypeList) GetMarkers() Markers { return n.Markers }

func (n *Unary) GetID() uuid.UUID { return n.ID }
func (n *Unary) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *Unary) GetPrefix() Space    { return n.Prefix }
func (n *Unary) GetMarkers() Markers { return n.Markers }

func (n *VariableDeclarations) GetID() uuid.UUID { return n.ID }
func (n *VariableDeclarations) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *VariableDeclarations) GetPrefix() Space    { return n.Prefix }
func (n *VariableDeclarations) GetMarkers() Markers { return n.Markers }

func (n *VariableDeclarator) GetID() uuid.UUID { return n.ID }
func (n *VariableDeclarator) WithID(id uuid.UUID) J {
	if n.ID == id {
		return n
	}
	c := *n
	c.ID = id
	return &c
}
func (n *VariableDeclarator) GetPrefix() Space    { return n.Prefix }
func (n *VariableDeclarator) GetMarkers() Markers { return n.Markers }
