/*
 * Copyright 2026 the original author or authors.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Hand-written scaffold: KotlinScope mirrors JavaScope (generated from JavaVisitor `.class`)
// with `KotlinVisitor` substituted as the build target. KotlinVisitor inherits all
// JavaVisitor `visitX` methods, so the existing overrides remain correct on the
// KotlinVisitor anonymous subclass. K-specific visit methods (visitProperty,
// visitWhen, visitAnnotatedExpression, etc.) are NOT yet wired; recipes that need
// them currently fall back to the inherited JavaVisitor surface. Regenerate by
// re-running the sed transformation in build.gradle.kts (or a follow-up commit
// extends the codegen to handle self-referencing visitors).
package org.openrewrite.dsl.scopes

import org.openrewrite.Cursor
import org.openrewrite.ExecutionContext
import org.openrewrite.Tree
import org.openrewrite.TreeVisitor
import org.openrewrite.RecipeDsl

/**
 * Receiver scope for `kotlin { }` blocks inside `edit { }`,
 * `scan { }`, and `generate { }`. Exposes one `visitX(action: (Node) -> Node)`
 * function per public `visitX` declared on `org.openrewrite.kotlin.KotlinVisitor` and its
 * supertypes (up to but not including `TreeVisitor`).
 *
 * Generated by the rewrite-kotlin `generateLanguageScopes` Gradle task —
 * regenerate by running `:rewrite-kotlin:generateLanguageScopes` after
 * a visitor's `visitX` surface changes.
 */
@RecipeDsl
public class KotlinScope internal constructor() : LanguageScope() {

    @Suppress("UNCHECKED_CAST")
    public fun visitExpression(action: (org.openrewrite.java.tree.Expression) -> org.openrewrite.java.tree.Expression) {
        actions["visitExpression:(Lorg/openrewrite/java/tree/Expression;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitStatement(action: (org.openrewrite.java.tree.Statement) -> org.openrewrite.java.tree.Statement) {
        actions["visitStatement:(Lorg/openrewrite/java/tree/Statement;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitAnnotatedType(action: (org.openrewrite.java.tree.J.AnnotatedType) -> org.openrewrite.java.tree.J.AnnotatedType) {
        actions["visitAnnotatedType:(Lorg/openrewrite/java/tree/J\$AnnotatedType;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitAnnotation(action: (org.openrewrite.java.tree.J.Annotation) -> org.openrewrite.java.tree.J.Annotation) {
        actions["visitAnnotation:(Lorg/openrewrite/java/tree/J\$Annotation;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitArrayAccess(action: (org.openrewrite.java.tree.J.ArrayAccess) -> org.openrewrite.java.tree.J.ArrayAccess) {
        actions["visitArrayAccess:(Lorg/openrewrite/java/tree/J\$ArrayAccess;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitArrayDimension(action: (org.openrewrite.java.tree.J.ArrayDimension) -> org.openrewrite.java.tree.J.ArrayDimension) {
        actions["visitArrayDimension:(Lorg/openrewrite/java/tree/J\$ArrayDimension;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitArrayType(action: (org.openrewrite.java.tree.J.ArrayType) -> org.openrewrite.java.tree.J.ArrayType) {
        actions["visitArrayType:(Lorg/openrewrite/java/tree/J\$ArrayType;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitAssert(action: (org.openrewrite.java.tree.J.Assert) -> org.openrewrite.java.tree.J.Assert) {
        actions["visitAssert:(Lorg/openrewrite/java/tree/J\$Assert;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitAssignment(action: (org.openrewrite.java.tree.J.Assignment) -> org.openrewrite.java.tree.J.Assignment) {
        actions["visitAssignment:(Lorg/openrewrite/java/tree/J\$Assignment;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitAssignmentOperation(action: (org.openrewrite.java.tree.J.AssignmentOperation) -> org.openrewrite.java.tree.J.AssignmentOperation) {
        actions["visitAssignmentOperation:(Lorg/openrewrite/java/tree/J\$AssignmentOperation;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitBinary(action: (org.openrewrite.java.tree.J.Binary) -> org.openrewrite.java.tree.J.Binary) {
        actions["visitBinary:(Lorg/openrewrite/java/tree/J\$Binary;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitBlock(action: (org.openrewrite.java.tree.J.Block) -> org.openrewrite.java.tree.J.Block) {
        actions["visitBlock:(Lorg/openrewrite/java/tree/J\$Block;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitBreak(action: (org.openrewrite.java.tree.J.Break) -> org.openrewrite.java.tree.J.Break) {
        actions["visitBreak:(Lorg/openrewrite/java/tree/J\$Break;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitCase(action: (org.openrewrite.java.tree.J.Case) -> org.openrewrite.java.tree.J.Case) {
        actions["visitCase:(Lorg/openrewrite/java/tree/J\$Case;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitCatch(action: (org.openrewrite.java.tree.J.Try.Catch) -> org.openrewrite.java.tree.J.Try.Catch) {
        actions["visitCatch:(Lorg/openrewrite/java/tree/J\$Try\$Catch;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitClassDeclaration(action: (org.openrewrite.java.tree.J.ClassDeclaration) -> org.openrewrite.java.tree.J.ClassDeclaration) {
        actions["visitClassDeclaration:(Lorg/openrewrite/java/tree/J\$ClassDeclaration;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitCompilationUnit(action: (org.openrewrite.java.tree.J.CompilationUnit) -> org.openrewrite.java.tree.J.CompilationUnit) {
        actions["visitCompilationUnit:(Lorg/openrewrite/java/tree/J\$CompilationUnit;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitContinue(action: (org.openrewrite.java.tree.J.Continue) -> org.openrewrite.java.tree.J.Continue) {
        actions["visitContinue:(Lorg/openrewrite/java/tree/J\$Continue;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitDoWhileLoop(action: (org.openrewrite.java.tree.J.DoWhileLoop) -> org.openrewrite.java.tree.J.DoWhileLoop) {
        actions["visitDoWhileLoop:(Lorg/openrewrite/java/tree/J\$DoWhileLoop;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitEmpty(action: (org.openrewrite.java.tree.J.Empty) -> org.openrewrite.java.tree.J.Empty) {
        actions["visitEmpty:(Lorg/openrewrite/java/tree/J\$Empty;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitEnumValue(action: (org.openrewrite.java.tree.J.EnumValue) -> org.openrewrite.java.tree.J.EnumValue) {
        actions["visitEnumValue:(Lorg/openrewrite/java/tree/J\$EnumValue;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitEnumValueSet(action: (org.openrewrite.java.tree.J.EnumValueSet) -> org.openrewrite.java.tree.J.EnumValueSet) {
        actions["visitEnumValueSet:(Lorg/openrewrite/java/tree/J\$EnumValueSet;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitFieldAccess(action: (org.openrewrite.java.tree.J.FieldAccess) -> org.openrewrite.java.tree.J.FieldAccess) {
        actions["visitFieldAccess:(Lorg/openrewrite/java/tree/J\$FieldAccess;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitForEachLoop(action: (org.openrewrite.java.tree.J.ForEachLoop) -> org.openrewrite.java.tree.J.ForEachLoop) {
        actions["visitForEachLoop:(Lorg/openrewrite/java/tree/J\$ForEachLoop;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitForEachControl(action: (org.openrewrite.java.tree.J.ForEachLoop.Control) -> org.openrewrite.java.tree.J.ForEachLoop.Control) {
        actions["visitForEachControl:(Lorg/openrewrite/java/tree/J\$ForEachLoop\$Control;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitForLoop(action: (org.openrewrite.java.tree.J.ForLoop) -> org.openrewrite.java.tree.J.ForLoop) {
        actions["visitForLoop:(Lorg/openrewrite/java/tree/J\$ForLoop;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitForControl(action: (org.openrewrite.java.tree.J.ForLoop.Control) -> org.openrewrite.java.tree.J.ForLoop.Control) {
        actions["visitForControl:(Lorg/openrewrite/java/tree/J\$ForLoop\$Control;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitParenthesizedTypeTree(action: (org.openrewrite.java.tree.J.ParenthesizedTypeTree) -> org.openrewrite.java.tree.J.ParenthesizedTypeTree) {
        actions["visitParenthesizedTypeTree:(Lorg/openrewrite/java/tree/J\$ParenthesizedTypeTree;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitIdentifier(action: (org.openrewrite.java.tree.J.Identifier) -> org.openrewrite.java.tree.J.Identifier) {
        actions["visitIdentifier:(Lorg/openrewrite/java/tree/J\$Identifier;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitElse(action: (org.openrewrite.java.tree.J.If.Else) -> org.openrewrite.java.tree.J.If.Else) {
        actions["visitElse:(Lorg/openrewrite/java/tree/J\$If\$Else;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitIf(action: (org.openrewrite.java.tree.J.If) -> org.openrewrite.java.tree.J.If) {
        actions["visitIf:(Lorg/openrewrite/java/tree/J\$If;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitImport(action: (org.openrewrite.java.tree.J.Import) -> org.openrewrite.java.tree.J.Import) {
        actions["visitImport:(Lorg/openrewrite/java/tree/J\$Import;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitInstanceOf(action: (org.openrewrite.java.tree.J.InstanceOf) -> org.openrewrite.java.tree.J.InstanceOf) {
        actions["visitInstanceOf:(Lorg/openrewrite/java/tree/J\$InstanceOf;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitDeconstructionPattern(action: (org.openrewrite.java.tree.J.DeconstructionPattern) -> org.openrewrite.java.tree.J.DeconstructionPattern) {
        actions["visitDeconstructionPattern:(Lorg/openrewrite/java/tree/J\$DeconstructionPattern;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitIntersectionType(action: (org.openrewrite.java.tree.J.IntersectionType) -> org.openrewrite.java.tree.J.IntersectionType) {
        actions["visitIntersectionType:(Lorg/openrewrite/java/tree/J\$IntersectionType;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitLabel(action: (org.openrewrite.java.tree.J.Label) -> org.openrewrite.java.tree.J.Label) {
        actions["visitLabel:(Lorg/openrewrite/java/tree/J\$Label;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitLambda(action: (org.openrewrite.java.tree.J.Lambda) -> org.openrewrite.java.tree.J.Lambda) {
        actions["visitLambda:(Lorg/openrewrite/java/tree/J\$Lambda;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitLambdaParameters(action: (org.openrewrite.java.tree.J.Lambda.Parameters) -> org.openrewrite.java.tree.J.Lambda.Parameters) {
        actions["visitLambdaParameters:(Lorg/openrewrite/java/tree/J\$Lambda\$Parameters;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitLiteral(action: (org.openrewrite.java.tree.J.Literal) -> org.openrewrite.java.tree.J.Literal) {
        actions["visitLiteral:(Lorg/openrewrite/java/tree/J\$Literal;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitMemberReference(action: (org.openrewrite.java.tree.J.MemberReference) -> org.openrewrite.java.tree.J.MemberReference) {
        actions["visitMemberReference:(Lorg/openrewrite/java/tree/J\$MemberReference;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitMethodDeclaration(action: (org.openrewrite.java.tree.J.MethodDeclaration) -> org.openrewrite.java.tree.J.MethodDeclaration) {
        actions["visitMethodDeclaration:(Lorg/openrewrite/java/tree/J\$MethodDeclaration;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitMethodInvocation(action: (org.openrewrite.java.tree.J.MethodInvocation) -> org.openrewrite.java.tree.J.MethodInvocation) {
        actions["visitMethodInvocation:(Lorg/openrewrite/java/tree/J\$MethodInvocation;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitModifier(action: (org.openrewrite.java.tree.J.Modifier) -> org.openrewrite.java.tree.J.Modifier) {
        actions["visitModifier:(Lorg/openrewrite/java/tree/J\$Modifier;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitMultiCatch(action: (org.openrewrite.java.tree.J.MultiCatch) -> org.openrewrite.java.tree.J.MultiCatch) {
        actions["visitMultiCatch:(Lorg/openrewrite/java/tree/J\$MultiCatch;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitVariableDeclarations(action: (org.openrewrite.java.tree.J.VariableDeclarations) -> org.openrewrite.java.tree.J.VariableDeclarations) {
        actions["visitVariableDeclarations:(Lorg/openrewrite/java/tree/J\$VariableDeclarations;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitNewArray(action: (org.openrewrite.java.tree.J.NewArray) -> org.openrewrite.java.tree.J.NewArray) {
        actions["visitNewArray:(Lorg/openrewrite/java/tree/J\$NewArray;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitNewClass(action: (org.openrewrite.java.tree.J.NewClass) -> org.openrewrite.java.tree.J.NewClass) {
        actions["visitNewClass:(Lorg/openrewrite/java/tree/J\$NewClass;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitNullableType(action: (org.openrewrite.java.tree.J.NullableType) -> org.openrewrite.java.tree.J.NullableType) {
        actions["visitNullableType:(Lorg/openrewrite/java/tree/J\$NullableType;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitPackage(action: (org.openrewrite.java.tree.J.Package) -> org.openrewrite.java.tree.J.Package) {
        actions["visitPackage:(Lorg/openrewrite/java/tree/J\$Package;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitParameterizedType(action: (org.openrewrite.java.tree.J.ParameterizedType) -> org.openrewrite.java.tree.J.ParameterizedType) {
        actions["visitParameterizedType:(Lorg/openrewrite/java/tree/J\$ParameterizedType;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitPrimitive(action: (org.openrewrite.java.tree.J.Primitive) -> org.openrewrite.java.tree.J.Primitive) {
        actions["visitPrimitive:(Lorg/openrewrite/java/tree/J\$Primitive;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitReturn(action: (org.openrewrite.java.tree.J.Return) -> org.openrewrite.java.tree.J.Return) {
        actions["visitReturn:(Lorg/openrewrite/java/tree/J\$Return;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitSwitch(action: (org.openrewrite.java.tree.J.Switch) -> org.openrewrite.java.tree.J.Switch) {
        actions["visitSwitch:(Lorg/openrewrite/java/tree/J\$Switch;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitSwitchExpression(action: (org.openrewrite.java.tree.J.SwitchExpression) -> org.openrewrite.java.tree.J.SwitchExpression) {
        actions["visitSwitchExpression:(Lorg/openrewrite/java/tree/J\$SwitchExpression;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitSynchronized(action: (org.openrewrite.java.tree.J.Synchronized) -> org.openrewrite.java.tree.J.Synchronized) {
        actions["visitSynchronized:(Lorg/openrewrite/java/tree/J\$Synchronized;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitTernary(action: (org.openrewrite.java.tree.J.Ternary) -> org.openrewrite.java.tree.J.Ternary) {
        actions["visitTernary:(Lorg/openrewrite/java/tree/J\$Ternary;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitThrow(action: (org.openrewrite.java.tree.J.Throw) -> org.openrewrite.java.tree.J.Throw) {
        actions["visitThrow:(Lorg/openrewrite/java/tree/J\$Throw;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitTry(action: (org.openrewrite.java.tree.J.Try) -> org.openrewrite.java.tree.J.Try) {
        actions["visitTry:(Lorg/openrewrite/java/tree/J\$Try;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitTryResource(action: (org.openrewrite.java.tree.J.Try.Resource) -> org.openrewrite.java.tree.J.Try.Resource) {
        actions["visitTryResource:(Lorg/openrewrite/java/tree/J\$Try\$Resource;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitTypeCast(action: (org.openrewrite.java.tree.J.TypeCast) -> org.openrewrite.java.tree.J.TypeCast) {
        actions["visitTypeCast:(Lorg/openrewrite/java/tree/J\$TypeCast;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitTypeParameter(action: (org.openrewrite.java.tree.J.TypeParameter) -> org.openrewrite.java.tree.J.TypeParameter) {
        actions["visitTypeParameter:(Lorg/openrewrite/java/tree/J\$TypeParameter;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitTypeParameters(action: (org.openrewrite.java.tree.J.TypeParameters) -> org.openrewrite.java.tree.J.TypeParameters) {
        actions["visitTypeParameters:(Lorg/openrewrite/java/tree/J\$TypeParameters;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitUnary(action: (org.openrewrite.java.tree.J.Unary) -> org.openrewrite.java.tree.J.Unary) {
        actions["visitUnary:(Lorg/openrewrite/java/tree/J\$Unary;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitUnknown(action: (org.openrewrite.java.tree.J.Unknown) -> org.openrewrite.java.tree.J.Unknown) {
        actions["visitUnknown:(Lorg/openrewrite/java/tree/J\$Unknown;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitUnknownSource(action: (org.openrewrite.java.tree.J.Unknown.Source) -> org.openrewrite.java.tree.J.Unknown.Source) {
        actions["visitUnknownSource:(Lorg/openrewrite/java/tree/J\$Unknown\$Source;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitVariable(action: (org.openrewrite.java.tree.J.VariableDeclarations.NamedVariable) -> org.openrewrite.java.tree.J.VariableDeclarations.NamedVariable) {
        actions["visitVariable:(Lorg/openrewrite/java/tree/J\$VariableDeclarations\$NamedVariable;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitWhileLoop(action: (org.openrewrite.java.tree.J.WhileLoop) -> org.openrewrite.java.tree.J.WhileLoop) {
        actions["visitWhileLoop:(Lorg/openrewrite/java/tree/J\$WhileLoop;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitWildcard(action: (org.openrewrite.java.tree.J.Wildcard) -> org.openrewrite.java.tree.J.Wildcard) {
        actions["visitWildcard:(Lorg/openrewrite/java/tree/J\$Wildcard;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitYield(action: (org.openrewrite.java.tree.J.Yield) -> org.openrewrite.java.tree.J.Yield) {
        actions["visitYield:(Lorg/openrewrite/java/tree/J\$Yield;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    public fun visitErroneous(action: (org.openrewrite.java.tree.J.Erroneous) -> org.openrewrite.java.tree.J.Erroneous) {
        actions["visitErroneous:(Lorg/openrewrite/java/tree/J\$Erroneous;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] = action as ((Any) -> Any)
    }

    @Suppress("UNCHECKED_CAST")
    override fun build(): TreeVisitor<*, ExecutionContext> = object : org.openrewrite.kotlin.KotlinVisitor<ExecutionContext>() {
        override fun visitExpression(node: org.openrewrite.java.tree.Expression, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitExpression:(Lorg/openrewrite/java/tree/Expression;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.Expression else node
            return super.visitExpression(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitStatement(node: org.openrewrite.java.tree.Statement, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitStatement:(Lorg/openrewrite/java/tree/Statement;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.Statement else node
            return super.visitStatement(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitAnnotatedType(node: org.openrewrite.java.tree.J.AnnotatedType, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitAnnotatedType:(Lorg/openrewrite/java/tree/J\$AnnotatedType;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.AnnotatedType else node
            return super.visitAnnotatedType(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitAnnotation(node: org.openrewrite.java.tree.J.Annotation, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitAnnotation:(Lorg/openrewrite/java/tree/J\$Annotation;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Annotation else node
            return super.visitAnnotation(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitArrayAccess(node: org.openrewrite.java.tree.J.ArrayAccess, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitArrayAccess:(Lorg/openrewrite/java/tree/J\$ArrayAccess;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.ArrayAccess else node
            return super.visitArrayAccess(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitArrayDimension(node: org.openrewrite.java.tree.J.ArrayDimension, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitArrayDimension:(Lorg/openrewrite/java/tree/J\$ArrayDimension;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.ArrayDimension else node
            return super.visitArrayDimension(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitArrayType(node: org.openrewrite.java.tree.J.ArrayType, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitArrayType:(Lorg/openrewrite/java/tree/J\$ArrayType;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.ArrayType else node
            return super.visitArrayType(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitAssert(node: org.openrewrite.java.tree.J.Assert, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitAssert:(Lorg/openrewrite/java/tree/J\$Assert;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Assert else node
            return super.visitAssert(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitAssignment(node: org.openrewrite.java.tree.J.Assignment, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitAssignment:(Lorg/openrewrite/java/tree/J\$Assignment;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Assignment else node
            return super.visitAssignment(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitAssignmentOperation(node: org.openrewrite.java.tree.J.AssignmentOperation, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitAssignmentOperation:(Lorg/openrewrite/java/tree/J\$AssignmentOperation;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.AssignmentOperation else node
            return super.visitAssignmentOperation(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitBinary(node: org.openrewrite.java.tree.J.Binary, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitBinary:(Lorg/openrewrite/java/tree/J\$Binary;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Binary else node
            return super.visitBinary(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitBlock(node: org.openrewrite.java.tree.J.Block, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitBlock:(Lorg/openrewrite/java/tree/J\$Block;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Block else node
            return super.visitBlock(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitBreak(node: org.openrewrite.java.tree.J.Break, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitBreak:(Lorg/openrewrite/java/tree/J\$Break;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Break else node
            return super.visitBreak(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitCase(node: org.openrewrite.java.tree.J.Case, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitCase:(Lorg/openrewrite/java/tree/J\$Case;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Case else node
            return super.visitCase(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitCatch(node: org.openrewrite.java.tree.J.Try.Catch, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitCatch:(Lorg/openrewrite/java/tree/J\$Try\$Catch;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Try.Catch else node
            return super.visitCatch(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitClassDeclaration(node: org.openrewrite.java.tree.J.ClassDeclaration, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitClassDeclaration:(Lorg/openrewrite/java/tree/J\$ClassDeclaration;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.ClassDeclaration else node
            return super.visitClassDeclaration(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitCompilationUnit(node: org.openrewrite.java.tree.J.CompilationUnit, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitCompilationUnit:(Lorg/openrewrite/java/tree/J\$CompilationUnit;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.CompilationUnit else node
            return super.visitCompilationUnit(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitContinue(node: org.openrewrite.java.tree.J.Continue, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitContinue:(Lorg/openrewrite/java/tree/J\$Continue;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Continue else node
            return super.visitContinue(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitDoWhileLoop(node: org.openrewrite.java.tree.J.DoWhileLoop, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitDoWhileLoop:(Lorg/openrewrite/java/tree/J\$DoWhileLoop;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.DoWhileLoop else node
            return super.visitDoWhileLoop(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitEmpty(node: org.openrewrite.java.tree.J.Empty, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitEmpty:(Lorg/openrewrite/java/tree/J\$Empty;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Empty else node
            return super.visitEmpty(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitEnumValue(node: org.openrewrite.java.tree.J.EnumValue, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitEnumValue:(Lorg/openrewrite/java/tree/J\$EnumValue;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.EnumValue else node
            return super.visitEnumValue(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitEnumValueSet(node: org.openrewrite.java.tree.J.EnumValueSet, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitEnumValueSet:(Lorg/openrewrite/java/tree/J\$EnumValueSet;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.EnumValueSet else node
            return super.visitEnumValueSet(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitFieldAccess(node: org.openrewrite.java.tree.J.FieldAccess, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitFieldAccess:(Lorg/openrewrite/java/tree/J\$FieldAccess;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.FieldAccess else node
            return super.visitFieldAccess(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitForEachLoop(node: org.openrewrite.java.tree.J.ForEachLoop, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitForEachLoop:(Lorg/openrewrite/java/tree/J\$ForEachLoop;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.ForEachLoop else node
            return super.visitForEachLoop(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitForEachControl(node: org.openrewrite.java.tree.J.ForEachLoop.Control, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitForEachControl:(Lorg/openrewrite/java/tree/J\$ForEachLoop\$Control;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.ForEachLoop.Control else node
            return super.visitForEachControl(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitForLoop(node: org.openrewrite.java.tree.J.ForLoop, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitForLoop:(Lorg/openrewrite/java/tree/J\$ForLoop;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.ForLoop else node
            return super.visitForLoop(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitForControl(node: org.openrewrite.java.tree.J.ForLoop.Control, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitForControl:(Lorg/openrewrite/java/tree/J\$ForLoop\$Control;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.ForLoop.Control else node
            return super.visitForControl(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitParenthesizedTypeTree(node: org.openrewrite.java.tree.J.ParenthesizedTypeTree, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitParenthesizedTypeTree:(Lorg/openrewrite/java/tree/J\$ParenthesizedTypeTree;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.ParenthesizedTypeTree else node
            return super.visitParenthesizedTypeTree(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitIdentifier(node: org.openrewrite.java.tree.J.Identifier, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitIdentifier:(Lorg/openrewrite/java/tree/J\$Identifier;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Identifier else node
            return super.visitIdentifier(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitElse(node: org.openrewrite.java.tree.J.If.Else, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitElse:(Lorg/openrewrite/java/tree/J\$If\$Else;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.If.Else else node
            return super.visitElse(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitIf(node: org.openrewrite.java.tree.J.If, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitIf:(Lorg/openrewrite/java/tree/J\$If;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.If else node
            return super.visitIf(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitImport(node: org.openrewrite.java.tree.J.Import, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitImport:(Lorg/openrewrite/java/tree/J\$Import;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Import else node
            return super.visitImport(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitInstanceOf(node: org.openrewrite.java.tree.J.InstanceOf, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitInstanceOf:(Lorg/openrewrite/java/tree/J\$InstanceOf;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.InstanceOf else node
            return super.visitInstanceOf(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitDeconstructionPattern(node: org.openrewrite.java.tree.J.DeconstructionPattern, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitDeconstructionPattern:(Lorg/openrewrite/java/tree/J\$DeconstructionPattern;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.DeconstructionPattern else node
            return super.visitDeconstructionPattern(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitIntersectionType(node: org.openrewrite.java.tree.J.IntersectionType, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitIntersectionType:(Lorg/openrewrite/java/tree/J\$IntersectionType;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.IntersectionType else node
            return super.visitIntersectionType(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitLabel(node: org.openrewrite.java.tree.J.Label, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitLabel:(Lorg/openrewrite/java/tree/J\$Label;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Label else node
            return super.visitLabel(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitLambda(node: org.openrewrite.java.tree.J.Lambda, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitLambda:(Lorg/openrewrite/java/tree/J\$Lambda;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Lambda else node
            return super.visitLambda(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitLambdaParameters(node: org.openrewrite.java.tree.J.Lambda.Parameters, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitLambdaParameters:(Lorg/openrewrite/java/tree/J\$Lambda\$Parameters;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Lambda.Parameters else node
            return super.visitLambdaParameters(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitLiteral(node: org.openrewrite.java.tree.J.Literal, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitLiteral:(Lorg/openrewrite/java/tree/J\$Literal;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Literal else node
            return super.visitLiteral(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitMemberReference(node: org.openrewrite.java.tree.J.MemberReference, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitMemberReference:(Lorg/openrewrite/java/tree/J\$MemberReference;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.MemberReference else node
            return super.visitMemberReference(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitMethodDeclaration(node: org.openrewrite.java.tree.J.MethodDeclaration, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitMethodDeclaration:(Lorg/openrewrite/java/tree/J\$MethodDeclaration;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.MethodDeclaration else node
            return super.visitMethodDeclaration(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitMethodInvocation(node: org.openrewrite.java.tree.J.MethodInvocation, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitMethodInvocation:(Lorg/openrewrite/java/tree/J\$MethodInvocation;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.MethodInvocation else node
            return super.visitMethodInvocation(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitModifier(node: org.openrewrite.java.tree.J.Modifier, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitModifier:(Lorg/openrewrite/java/tree/J\$Modifier;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Modifier else node
            return super.visitModifier(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitMultiCatch(node: org.openrewrite.java.tree.J.MultiCatch, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitMultiCatch:(Lorg/openrewrite/java/tree/J\$MultiCatch;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.MultiCatch else node
            return super.visitMultiCatch(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitVariableDeclarations(node: org.openrewrite.java.tree.J.VariableDeclarations, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitVariableDeclarations:(Lorg/openrewrite/java/tree/J\$VariableDeclarations;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.VariableDeclarations else node
            return super.visitVariableDeclarations(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitNewArray(node: org.openrewrite.java.tree.J.NewArray, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitNewArray:(Lorg/openrewrite/java/tree/J\$NewArray;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.NewArray else node
            return super.visitNewArray(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitNewClass(node: org.openrewrite.java.tree.J.NewClass, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitNewClass:(Lorg/openrewrite/java/tree/J\$NewClass;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.NewClass else node
            return super.visitNewClass(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitNullableType(node: org.openrewrite.java.tree.J.NullableType, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitNullableType:(Lorg/openrewrite/java/tree/J\$NullableType;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.NullableType else node
            return super.visitNullableType(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitPackage(node: org.openrewrite.java.tree.J.Package, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitPackage:(Lorg/openrewrite/java/tree/J\$Package;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Package else node
            return super.visitPackage(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitParameterizedType(node: org.openrewrite.java.tree.J.ParameterizedType, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitParameterizedType:(Lorg/openrewrite/java/tree/J\$ParameterizedType;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.ParameterizedType else node
            return super.visitParameterizedType(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitPrimitive(node: org.openrewrite.java.tree.J.Primitive, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitPrimitive:(Lorg/openrewrite/java/tree/J\$Primitive;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Primitive else node
            return super.visitPrimitive(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitReturn(node: org.openrewrite.java.tree.J.Return, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitReturn:(Lorg/openrewrite/java/tree/J\$Return;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Return else node
            return super.visitReturn(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitSwitch(node: org.openrewrite.java.tree.J.Switch, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitSwitch:(Lorg/openrewrite/java/tree/J\$Switch;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Switch else node
            return super.visitSwitch(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitSwitchExpression(node: org.openrewrite.java.tree.J.SwitchExpression, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitSwitchExpression:(Lorg/openrewrite/java/tree/J\$SwitchExpression;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.SwitchExpression else node
            return super.visitSwitchExpression(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitSynchronized(node: org.openrewrite.java.tree.J.Synchronized, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitSynchronized:(Lorg/openrewrite/java/tree/J\$Synchronized;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Synchronized else node
            return super.visitSynchronized(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitTernary(node: org.openrewrite.java.tree.J.Ternary, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitTernary:(Lorg/openrewrite/java/tree/J\$Ternary;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Ternary else node
            return super.visitTernary(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitThrow(node: org.openrewrite.java.tree.J.Throw, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitThrow:(Lorg/openrewrite/java/tree/J\$Throw;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Throw else node
            return super.visitThrow(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitTry(node: org.openrewrite.java.tree.J.Try, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitTry:(Lorg/openrewrite/java/tree/J\$Try;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Try else node
            return super.visitTry(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitTryResource(node: org.openrewrite.java.tree.J.Try.Resource, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitTryResource:(Lorg/openrewrite/java/tree/J\$Try\$Resource;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Try.Resource else node
            return super.visitTryResource(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitTypeCast(node: org.openrewrite.java.tree.J.TypeCast, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitTypeCast:(Lorg/openrewrite/java/tree/J\$TypeCast;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.TypeCast else node
            return super.visitTypeCast(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitTypeParameter(node: org.openrewrite.java.tree.J.TypeParameter, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitTypeParameter:(Lorg/openrewrite/java/tree/J\$TypeParameter;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.TypeParameter else node
            return super.visitTypeParameter(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitTypeParameters(node: org.openrewrite.java.tree.J.TypeParameters, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitTypeParameters:(Lorg/openrewrite/java/tree/J\$TypeParameters;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.TypeParameters else node
            return super.visitTypeParameters(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitUnary(node: org.openrewrite.java.tree.J.Unary, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitUnary:(Lorg/openrewrite/java/tree/J\$Unary;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Unary else node
            return super.visitUnary(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitUnknown(node: org.openrewrite.java.tree.J.Unknown, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitUnknown:(Lorg/openrewrite/java/tree/J\$Unknown;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Unknown else node
            return super.visitUnknown(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitUnknownSource(node: org.openrewrite.java.tree.J.Unknown.Source, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitUnknownSource:(Lorg/openrewrite/java/tree/J\$Unknown\$Source;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Unknown.Source else node
            return super.visitUnknownSource(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitVariable(node: org.openrewrite.java.tree.J.VariableDeclarations.NamedVariable, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitVariable:(Lorg/openrewrite/java/tree/J\$VariableDeclarations\$NamedVariable;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.VariableDeclarations.NamedVariable else node
            return super.visitVariable(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitWhileLoop(node: org.openrewrite.java.tree.J.WhileLoop, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitWhileLoop:(Lorg/openrewrite/java/tree/J\$WhileLoop;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.WhileLoop else node
            return super.visitWhileLoop(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitWildcard(node: org.openrewrite.java.tree.J.Wildcard, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitWildcard:(Lorg/openrewrite/java/tree/J\$Wildcard;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Wildcard else node
            return super.visitWildcard(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitYield(node: org.openrewrite.java.tree.J.Yield, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitYield:(Lorg/openrewrite/java/tree/J\$Yield;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Yield else node
            return super.visitYield(transformed, ctx) as org.openrewrite.java.tree.J
        }

        override fun visitErroneous(node: org.openrewrite.java.tree.J.Erroneous, ctx: ExecutionContext): org.openrewrite.java.tree.J {
            val action = actions["visitErroneous:(Lorg/openrewrite/java/tree/J\$Erroneous;Ljava/lang/Object;)Lorg/openrewrite/java/tree/J;"] as? ((Any) -> Any)
            val transformed = if (action != null) action(node) as org.openrewrite.java.tree.J.Erroneous else node
            return super.visitErroneous(transformed, ctx) as org.openrewrite.java.tree.J
        }

    }
}
