/*
 * Copyright 2026 the original author or authors.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openrewrite.dsl.scopes

import org.openrewrite.ExecutionContext
import org.openrewrite.RecipeDsl
import org.openrewrite.TreeVisitor

// Shared runtime base for the per-language scope classes generated by the
// rewrite-kotlin `generateLanguageScopes` Gradle task.
//
// Each `<Lang>Scope` class:
//   - Inherits this base and is `@RecipeDsl`-marked.
//   - Auto-generates one `visitX(action: (Node) -> Node)` function per public
//     `visitX(Node, P)` declared on `<Lang>Visitor` (and its visitor ancestors,
//     up to but not including `TreeVisitor`).
//   - Each registered action is stored in [actions] keyed by the visitor
//     method's simple name.
//   - The generated `build()` returns an anonymous `<Lang>Visitor<ExecutionContext>`
//     whose overrides look up the registered action and dispatch.
//
// Last-registration-wins semantics: a `<Lang>Scope` block that calls the same
// `visitX` twice overwrites the first registration. Authors who genuinely need
// two visit passes use two separate language scopes (sibling `kotlin { }` calls
// in an `edit { }` block, composed via `composeSequential`).

@RecipeDsl
public abstract class LanguageScope internal constructor() {
    @PublishedApi
    internal val actions: MutableMap<String, Any> = mutableMapOf()

    /**
     * Build the language visitor for this scope. Generated subclasses
     * implement this by instantiating an anonymous `<Lang>Visitor` whose
     * overrides dispatch through [actions].
     */
    internal abstract fun build(): TreeVisitor<*, ExecutionContext>
}
