/*
 * Copyright 2025 the original author or authors.
 *
 * Licensed under the Moderne Source Available License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://docs.moderne.io/licensing/moderne-source-available-license
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package test

import (
	"bufio"
	"encoding/csv"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
	"time"
)

// JavaRpcClient communicates with a Java RPC server process
// (org.openrewrite.maven.rpc.JavaRewriteRpc) over stdin/stdout
// using Content-Length framed JSON-RPC 2.0.
type JavaRpcClient struct {
	process   *exec.Cmd
	stdin     io.WriteCloser
	stdout    *bufio.Reader
	requestID atomic.Int64
	mu        sync.Mutex // serializes writes to stdin

	// responses maps request ID → channel delivering the response
	responses sync.Map
}

type jsonRPCRequest struct {
	JSONRPC string `json:"jsonrpc"`
	ID      int64  `json:"id"`
	Method  string `json:"method"`
	Params  any    `json:"params,omitempty"`
}

type jsonRPCResponse struct {
	JSONRPC string          `json:"jsonrpc"`
	ID      int64           `json:"id"`
	Result  json.RawMessage `json:"result,omitempty"`
	Error   *rpcError       `json:"error,omitempty"`
}

type rpcError struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    string `json:"data,omitempty"`
}

// StartJavaRpcClient spawns a Java RPC server and returns a client.
// The classpath is read from test-classpath.txt (generated by Gradle).
// The marketplace CSV is written to a temp file.
func StartJavaRpcClient(t *testing.T, recipes []RecipeEntry) *JavaRpcClient {
	t.Helper()

	classpath := findTestClasspath(t)
	marketplaceCSV := writeMarketplaceCSV(t, recipes)

	javaCmd := findJavaCommand()
	cmd := exec.Command(javaCmd,
		"-cp", classpath,
		"org.openrewrite.maven.rpc.JavaRewriteRpc",
		"--marketplace="+marketplaceCSV,
	)

	stdin, err := cmd.StdinPipe()
	if err != nil {
		t.Fatalf("failed to get stdin pipe: %v", err)
	}
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		t.Fatalf("failed to get stdout pipe: %v", err)
	}
	cmd.Stderr = os.Stderr

	if err := cmd.Start(); err != nil {
		t.Fatalf("failed to start Java RPC server: %v", err)
	}

	client := &JavaRpcClient{
		process: cmd,
		stdin:   stdin,
		stdout:  bufio.NewReader(stdout),
	}

	// Start background reader
	go client.readResponses()

	return client
}

// Shutdown gracefully stops the Java RPC server.
func (c *JavaRpcClient) Shutdown() {
	if c.stdin != nil {
		c.stdin.Close()
	}
	if c.process != nil {
		done := make(chan error, 1)
		go func() { done <- c.process.Wait() }()
		select {
		case <-done:
		case <-time.After(5 * time.Second):
			c.process.Process.Kill()
			<-done
		}
	}
}

// SendRequest sends a JSON-RPC request and waits for the response.
func (c *JavaRpcClient) SendRequest(method string, params any) (json.RawMessage, error) {
	id := c.requestID.Add(1)

	req := jsonRPCRequest{
		JSONRPC: "2.0",
		ID:      id,
		Method:  method,
		Params:  params,
	}

	// Create response channel
	ch := make(chan *jsonRPCResponse, 1)
	c.responses.Store(id, ch)
	defer c.responses.Delete(id)

	// Send request
	if err := c.writeMessage(req); err != nil {
		return nil, fmt.Errorf("failed to send %s request: %w", method, err)
	}

	// Wait for response
	select {
	case resp := <-ch:
		if resp.Error != nil {
			return nil, fmt.Errorf("RPC error (%d): %s", resp.Error.Code, resp.Error.Message)
		}
		return resp.Result, nil
	case <-time.After(30 * time.Second):
		return nil, fmt.Errorf("timeout waiting for %s response", method)
	}
}

func (c *JavaRpcClient) writeMessage(msg any) error {
	body, err := json.Marshal(msg)
	if err != nil {
		return err
	}

	c.mu.Lock()
	defer c.mu.Unlock()

	header := fmt.Sprintf("Content-Length: %d\r\n\r\n", len(body))
	if _, err := io.WriteString(c.stdin, header); err != nil {
		return err
	}
	if _, err := c.stdin.Write(body); err != nil {
		return err
	}
	return nil
}

func (c *JavaRpcClient) readResponses() {
	for {
		resp, err := c.readMessage()
		if err != nil {
			return
		}
		if val, ok := c.responses.Load(resp.ID); ok {
			ch := val.(chan *jsonRPCResponse)
			ch <- resp
		}
	}
}

func (c *JavaRpcClient) readMessage() (*jsonRPCResponse, error) {
	// Read Content-Length header
	for {
		line, err := c.stdout.ReadString('\n')
		if err != nil {
			return nil, err
		}
		line = strings.TrimSpace(line)
		if line == "" {
			continue // blank separator line
		}
		if strings.HasPrefix(line, "Content-Length:") {
			lengthStr := strings.TrimSpace(strings.TrimPrefix(line, "Content-Length:"))
			contentLength, err := strconv.Atoi(lengthStr)
			if err != nil {
				return nil, fmt.Errorf("invalid content length: %s", lengthStr)
			}

			// Read blank separator
			if _, err := c.stdout.ReadString('\n'); err != nil {
				return nil, err
			}

			// Read body
			body := make([]byte, contentLength)
			if _, err := io.ReadFull(c.stdout, body); err != nil {
				return nil, err
			}

			var resp jsonRPCResponse
			if err := json.Unmarshal(body, &resp); err != nil {
				return nil, fmt.Errorf("invalid JSON response: %w", err)
			}
			return &resp, nil
		}
	}
}

// RecipeEntry describes a recipe for the marketplace CSV.
type RecipeEntry struct {
	Name        string
	PackageName string
	Version     string
}

// DefaultJavaRecipes returns the common Java recipes used for testing.
func DefaultJavaRecipes() []RecipeEntry {
	return []RecipeEntry{
		{Name: "org.openrewrite.java.ChangeType", PackageName: "org.openrewrite:rewrite-java", Version: "8.73.0"},
		{Name: "org.openrewrite.java.ChangeMethodName", PackageName: "org.openrewrite:rewrite-java", Version: "8.73.0"},
		{Name: "org.openrewrite.java.search.FindTypes", PackageName: "org.openrewrite:rewrite-java", Version: "8.73.0"},
		{Name: "org.openrewrite.java.search.FindMethods", PackageName: "org.openrewrite:rewrite-java", Version: "8.73.0"},
	}
}

func findTestClasspath(t *testing.T) string {
	t.Helper()

	// Check environment variable first
	if cp := os.Getenv("REWRITE_GO_CLASSPATH"); cp != "" {
		return cp
	}

	// Look for generated classpath file
	_, thisFile, _, _ := runtime.Caller(0)
	searchPaths := []string{
		filepath.Join(filepath.Dir(thisFile), "..", "..", "test-classpath.txt"),
		"test-classpath.txt",
		"rewrite/test-classpath.txt",
	}

	for _, p := range searchPaths {
		data, err := os.ReadFile(p)
		if err == nil {
			return strings.TrimSpace(string(data))
		}
	}

	t.Skip("Java RPC classpath not available. Run './gradlew :rewrite-go:generateTestClasspath' first, or set REWRITE_GO_CLASSPATH.")
	return ""
}

func findJavaCommand() string {
	if javaHome := os.Getenv("JAVA_HOME"); javaHome != "" {
		return filepath.Join(javaHome, "bin", "java")
	}
	return "java"
}

func writeMarketplaceCSV(t *testing.T, recipes []RecipeEntry) string {
	t.Helper()

	tmpFile, err := os.CreateTemp("", "marketplace-*.csv")
	if err != nil {
		t.Fatalf("failed to create marketplace CSV: %v", err)
	}
	t.Cleanup(func() { os.Remove(tmpFile.Name()) })

	w := csv.NewWriter(tmpFile)
	w.Write([]string{"name", "displayName", "description", "ecosystem", "packageName", "version"})
	for _, r := range recipes {
		w.Write([]string{r.Name, r.Name, "", "maven", r.PackageName, r.Version})
	}
	w.Flush()
	tmpFile.Close()

	return tmpFile.Name()
}
