{
 "title": "Rewrite Maven",
 "time": { "from": "2020-11-10T23:37:30.323Z", "to": "2020-11-10T23:38:42.349Z" },
 "panels": [
  {
   "title": "Cache sizes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "entries" }
   ],
   "targets": [
    {
     "expr": "rewrite_maven_workspace_cache_size",
     "legendFormat": "{{content}} {{layer}}"
    }
   ]
  },
  {
   "title": "New downloads by group",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (group_id) (rewrite_maven_download_seconds_count{outcome=\"success\"})",
     "legendFormat": "{{group_id}}"
    }
   ]
  },
  {
   "title": "Success/Cached/Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "operations" }
   ],
   "targets": [
    {
     "expr": "sum(rewrite_maven_download_seconds_count{outcome=\"success\"})",
     "legendFormat": "success"
    },
    {
     "expr": "sum(rewrite_maven_download_seconds_count{outcome=\"cached\"})",
     "legendFormat": "cached"
    },
    {
     "expr": "sum(rewrite_maven_download_seconds_count{outcome=\"error\"})",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Parse parent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rewrite_parse_parent_total", "legendFormat": "parents" }
   ]
  },
  {
   "title": "Download Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rewrite_maven_download_seconds_count{outcome=\"error\"}",
     "legendFormat": "{{group_id}}"
    }
   ]
  }
 ]
}