import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.openrewrite.codegen.dsl.GenerateLanguageScopesTask
import org.openrewrite.codegen.dsl.LanguageDescriptor

plugins {
    id("org.openrewrite.build.language-library")
    kotlin("jvm") version "2.2.21"
}

// When bumping this version, also update the kotlin-bom platform version
// in rewrite-gradle/build.gradle.kts and rewrite-maven/build.gradle.kts so
// the kotlin-stdlib alignment stays in lockstep across modules.
val kotlinVersion = "2.3.20"

recipeDependencies {
    parserClasspath("jakarta.persistence:jakarta.persistence-api:3.1.0")
}

dependencies {
    compileOnly(project(":rewrite-core"))
    compileOnly(project(":rewrite-test"))

    implementation(project(":rewrite-java"))

    // Recipe-DSL language scopes: each `<Lang>Scope.kt` is generated by the
    // `generateLanguageScopes` task and compiles against the language module's
    // visitor types. Authors who use `maven { … }` / `yaml { … }` / etc. add
    // `implementation("org.openrewrite:rewrite-<lang>")` themselves — these
    // are compileOnly so rewrite-kotlin's runtime classpath stays lean for
    // consumers that only need Kotlin parsing.
    //
    // `gradle { … }` is intentionally absent: rewrite-gradle depends on
    // rewrite-kotlin (see RecipeDsl.kt comment), so we'd create a project
    // cycle by listing it here. See plan §"Deliberately deferred".
    compileOnly(project(":rewrite-yaml"))
    compileOnly(project(":rewrite-xml"))
    compileOnly(project(":rewrite-maven"))
    compileOnly(project(":rewrite-json"))
    compileOnly(project(":rewrite-properties"))
    compileOnly(project(":rewrite-toml"))
    compileOnly(project(":rewrite-hcl"))
    compileOnly(project(":rewrite-python"))
    compileOnly(project(":rewrite-csharp"))
    compileOnly(project(":rewrite-scala"))
    compileOnly(project(":rewrite-javascript"))
    compileOnly(project(":rewrite-groovy"))

    // Align kotlin-stdlib-jdk7/-jdk8/-common with kotlin-stdlib (clikt 3.5.0
    // would otherwise drag the jdk7/jdk8/common artifacts back to 1.6.20).
    testImplementation(platform("org.jetbrains.kotlin:kotlin-bom:$kotlinVersion"))

    implementation(kotlin("compiler-embeddable", kotlinVersion))
    implementation(kotlin("reflect", kotlinVersion))
    implementation(kotlin("stdlib", kotlinVersion))

    testImplementation("org.junit-pioneer:junit-pioneer:latest.release")
    testImplementation(project(":rewrite-test"))
    testRuntimeOnly(project(":rewrite-java-21"))
    testRuntimeOnly("org.antlr:antlr4-runtime:4.13.2")
    testRuntimeOnly("com.fasterxml.jackson.module:jackson-module-kotlin")
    testRuntimeOnly("jakarta.persistence:jakarta.persistence-api:3.1.0")

    testImplementation("com.github.ajalt.clikt:clikt:3.5.0")
    testImplementation("com.squareup:javapoet:1.13.0")
    testImplementation("com.google.testing.compile:compile-testing:0.+")

    // For driving kotlinc with the rewrite-kotlin compiler plugin loaded in tests.
    testImplementation("dev.zacsweers.kctfork:core:0.12.1")
}

configurations.matching { it.name == "kotlinBouncyCastleConfiguration" }.configureEach {
    resolutionStrategy.eachDependency {
        if (requested.group == "org.bouncycastle") {
            useVersion("1.84")
            because("CVE-2026-3505, CVE-2026-5598, CVE-2026-5588, CVE-2026-0636")
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_1_8)
        // Required to override `FirPropertyChecker.check`, whose signature uses
        // context parameters as of Kotlin 2.2. Scoped to this module because the
        // recipe DSL compiler plugin in `org.openrewrite.kotlin.recipe.internal`
        // depends on it.
        freeCompilerArgs.add("-Xcontext-parameters")
    }
}

tasks.named<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>("compileTestKotlin") {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_21)
        freeCompilerArgs.add("-Xcontext-parameters")
    }
}

// === Recipe DSL language-scope codegen ===
//
// Each `<Lang>Scope.kt` is generated from the corresponding `<Lang>Visitor`'s
// public `visitX` methods (walking the class hierarchy up to but not including
// `TreeVisitor`). Inputs: the visitor `.class` files on the compile classpath
// plus rewrite-kotlin's own `compileJava` output (for `KotlinVisitor`). Output:
// `build/generated/source/recipeDsl/main/kotlin`.

val generatedScopesDir = layout.buildDirectory.dir("generated/source/recipeDsl/main/kotlin")

// `KotlinScope` is hand-written under `src/main/kotlin/org/openrewrite/dsl/scopes/`
// rather than codegen'd: `KotlinVisitor` lives in rewrite-kotlin's own Java
// sources, and `K.java` transitively depends on `internal/` classes that pull
// in `kotlin-compiler-embeddable` Psi types — too heavy for a parallel
// visitor-only JavaCompile to handle cleanly. The 13 cross-module languages
// (java/yaml/xml/maven/json/properties/toml/hcl/python/csharp/scala/javascript/groovy)
// are codegen'd from their `.class` files on the compile classpath.

val generateLanguageScopes by tasks.registering(GenerateLanguageScopesTask::class) {
    visitorClasspath.from(configurations.named("compileClasspath"))
    outputDir.set(generatedScopesDir)
    languages.set(listOf(
        // factoryName, scopeName, visitorFqn — KotlinScope deliberately omitted (hand-written).
        LanguageDescriptor("java", "JavaScope", "org.openrewrite.java.JavaVisitor"),
        LanguageDescriptor("yaml", "YamlScope", "org.openrewrite.yaml.YamlVisitor"),
        LanguageDescriptor("xml", "XmlScope", "org.openrewrite.xml.XmlVisitor"),
        LanguageDescriptor("maven", "MavenScope", "org.openrewrite.maven.MavenVisitor"),
        LanguageDescriptor("json", "JsonScope", "org.openrewrite.json.JsonVisitor"),
        LanguageDescriptor("properties", "PropertiesScope", "org.openrewrite.properties.PropertiesVisitor"),
        LanguageDescriptor("toml", "TomlScope", "org.openrewrite.toml.TomlVisitor"),
        LanguageDescriptor("hcl", "HclScope", "org.openrewrite.hcl.HclVisitor"),
        LanguageDescriptor("python", "PythonScope", "org.openrewrite.python.PythonVisitor"),
        LanguageDescriptor("csharp", "CSharpScope", "org.openrewrite.csharp.CSharpVisitor"),
        LanguageDescriptor("scala", "ScalaScope", "org.openrewrite.scala.ScalaVisitor"),
        LanguageDescriptor("javascript", "JavaScriptScope", "org.openrewrite.javascript.JavaScriptVisitor"),
        LanguageDescriptor("groovy", "GroovyScope", "org.openrewrite.groovy.GroovyVisitor"),
    ))
}

// Register the generator task PROVIDER on the source set (not the raw output
// directory). Gradle then infers the implicit dependency for every task that
// consumes the source set — `compileKotlin`, `kotlinSourcesJar`,
// `licenseMain`, and any other downstream task. Passing the path string
// (`generatedScopesDir`) instead would force us to wire each consumer
// manually, which Gradle 9's strict validation rejects on CI.
sourceSets.named("main") {
    java.srcDir(generateLanguageScopes)
}
