/*
 * Copyright 2026 the original author or authors.
 * <p>
 * Licensed under the Moderne Source Available License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://docs.moderne.io/licensing/moderne-source-available-license
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openrewrite.javascript;

import lombok.EqualsAndHashCode;
import lombok.Value;
import org.jspecify.annotations.Nullable;
import org.openrewrite.*;
import org.openrewrite.javascript.internal.LockFileRegeneration;
import org.openrewrite.javascript.internal.PackageJsonHelper;
import org.openrewrite.javascript.marker.NodeResolutionResult;
import org.openrewrite.javascript.marker.NodeResolutionResult.Dependency;
import org.openrewrite.json.tree.Json;
import org.openrewrite.marker.Markup;
import org.openrewrite.text.PlainText;
import org.openrewrite.yaml.tree.Yaml;

import java.nio.file.Path;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@EqualsAndHashCode(callSuper = false)
@Value
public class ChangeDependency extends ScanningRecipe<ChangeDependency.Accumulator> {

    @Option(displayName = "Old package name",
            description = "The current name of the npm package to rename.",
            example = "lodash")
    String oldPackageName;

    @Option(displayName = "New package name",
            description = "The new name to use for the package.",
            example = "lodash-es")
    String newPackageName;

    @Option(displayName = "New version",
            description = "Optional new version constraint to set on the renamed package.",
            example = "^5.0.0",
            required = false)
    @Nullable String newVersion;

    @Option(displayName = "Scope",
            description = "The dependency scope: `dependencies`, `devDependencies`, etc. " +
                    "When omitted, all scopes are searched.",
            valid = {"dependencies", "devDependencies", "peerDependencies",
                    "optionalDependencies", "bundledDependencies"},
            example = "dependencies",
            required = false)
    @Nullable String scope;

    @Override public String getDisplayName() { return "Change npm dependency"; }
    @Override public String getInstanceNameSuffix() { return String.format("`%s` -> `%s`", oldPackageName, newPackageName); }

    @Override public String getDescription() {
        return "Renames an npm dependency in `package.json` and optionally updates its version constraint. " +
                "After modifying the package.json, the lock file is regenerated by running the package manager. " +
                "Not safe to use as a precondition: invokes the package manager and publishes per-project " +
                "state shared with other dependency recipes.";
    }

    static class Accumulator {
        final Map<Path, ProjectState> projects = new HashMap<>();
        final Map<Path, Path> lockToPackage = new HashMap<>();
    }

    static class ProjectState {
        @Nullable SourceFile capturedPackageJson;
        @Nullable String capturedLockContent;
        @Nullable Map<String, String> configFiles;
        @Nullable SourceFile modifiedPackageJson;
        LockFileRegeneration.@Nullable Result regenResult;
    }

    @Override public Accumulator getInitialValue(ExecutionContext ctx) { return new Accumulator(); }

    @Override
    public TreeVisitor<?, ExecutionContext> getScanner(Accumulator acc) {
        return new TreeVisitor<Tree, ExecutionContext>() {
            @Override public Tree preVisit(Tree tree, ExecutionContext ctx) {
                stopAfterPreVisit();
                if (!(tree instanceof SourceFile)) return tree;
                SourceFile sf = (SourceFile) tree;
                Path p = sf.getSourcePath();
                String basename = p.getFileName().toString();

                if (PackageJsonHelper.isLockFile(basename)) {
                    if (sf instanceof Json.Document || sf instanceof Yaml.Documents || sf instanceof PlainText) {
                        Path packagePath = PackageJsonHelper.correspondingPackageJsonPath(p);
                        ProjectState ps = acc.projects.computeIfAbsent(packagePath, k -> new ProjectState());
                        ps.capturedLockContent = sf.printAll();
                        acc.lockToPackage.put(p, packagePath);
                    }
                    return tree;
                }
                if (sf instanceof Json.Document && "package.json".equals(basename)) {
                    NodeResolutionResult marker = sf.getMarkers().findFirst(NodeResolutionResult.class).orElse(null);
                    if (marker == null) return tree;
                    ProjectState ps = acc.projects.computeIfAbsent(p, k -> new ProjectState());
                    ps.capturedPackageJson = sf;
                    ps.configFiles = PackageJsonHelper.serializeConfigFiles(marker);
                }
                return tree;
            }
        };
    }

    private boolean matchesChange(SourceFile pkg) {
        NodeResolutionResult marker = pkg.getMarkers().findFirst(NodeResolutionResult.class).orElse(null);
        if (marker == null) return false;
        if (scope != null) {
            return containsIn(getScopeDeps(marker, scope));
        }
        return containsIn(marker.getDependencies()) || containsIn(marker.getDevDependencies())
                || containsIn(marker.getPeerDependencies()) || containsIn(marker.getOptionalDependencies())
                || containsIn(marker.getBundledDependencies());
    }

    private boolean containsIn(@Nullable List<Dependency> deps) {
        if (deps == null) return false;
        for (Dependency d : deps) if (oldPackageName.equals(d.getName())) return true;
        return false;
    }

    private @Nullable List<Dependency> getScopeDeps(NodeResolutionResult marker, String scopeName) {
        switch (scopeName) {
            case "dependencies": return marker.getDependencies();
            case "devDependencies": return marker.getDevDependencies();
            case "peerDependencies": return marker.getPeerDependencies();
            case "optionalDependencies": return marker.getOptionalDependencies();
            case "bundledDependencies": return marker.getBundledDependencies();
            default: return null;
        }
    }

    @Override
    public TreeVisitor<?, ExecutionContext> getVisitor(Accumulator acc) {
        return new TreeVisitor<Tree, ExecutionContext>() {
            @Override public Tree preVisit(Tree tree, ExecutionContext ctx) {
                stopAfterPreVisit();
                if (!(tree instanceof SourceFile)) return tree;
                SourceFile sf = (SourceFile) tree;
                Path p = sf.getSourcePath();

                ProjectState ps = acc.projects.get(p);
                if (ps != null && ps.capturedPackageJson != null) {
                    if (matchesChange(sf)) {
                        ensureComputed(ps, sf);
                    }
                    if (ps.modifiedPackageJson != null) {
                        SourceFile out = ps.modifiedPackageJson;
                        if (ps.regenResult != null && !ps.regenResult.isSuccess()) {
                            out = Markup.warn(out, new RuntimeException(
                                    "lock regeneration failed: " + ps.regenResult.getErrorMessage()));
                        }
                        PackageJsonHelper.putLiveTree(ctx, p, out);
                        return out;
                    }
                }

                Path packagePath = acc.lockToPackage.get(p);
                if (packagePath == null) return tree;
                ProjectState lockPs = acc.projects.get(packagePath);
                if (lockPs == null) return tree;
                if (lockPs.modifiedPackageJson == null) {
                    SourceFile pkg = PackageJsonHelper.getLiveTree(ctx, packagePath);
                    if (pkg == null) pkg = lockPs.capturedPackageJson;
                    if (pkg != null && matchesChange(pkg)) {
                        ensureComputed(lockPs, pkg);
                        if (lockPs.modifiedPackageJson != null) {
                            PackageJsonHelper.putLiveTree(ctx, packagePath, lockPs.modifiedPackageJson);
                        }
                    }
                }
                if (lockPs.regenResult != null && lockPs.regenResult.isSuccess()) {
                    return PackageJsonHelper.reparseLock(sf, lockPs.regenResult.getLockFileContent());
                }
                return tree;
            }

            private void ensureComputed(ProjectState ps, SourceFile pkg) {
                if (ps.modifiedPackageJson != null) return;
                PackageJsonHelper.EditAndRegenerateResult r = PackageJsonHelper.editAndRegenerate(
                        pkg,
                        doc -> PackageJsonHelper.changeDependency(doc, oldPackageName, newPackageName, newVersion, scope),
                        ps.capturedLockContent,
                        ps.configFiles);
                if (r.isChanged()) {
                    ps.modifiedPackageJson = r.getModifiedPackageJson();
                    ps.regenResult = r.getRegenResult();
                }
            }
        };
    }
}
