/*
 * Copyright 2026 the original author or authors.
 * <p>
 * Licensed under the Moderne Source Available License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://docs.moderne.io/licensing/moderne-source-available-license
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openrewrite.javascript;

import lombok.EqualsAndHashCode;
import lombok.Value;
import org.jspecify.annotations.Nullable;
import org.openrewrite.*;
import org.openrewrite.javascript.internal.LockFileRegeneration;
import org.openrewrite.javascript.internal.NodeDependencyScan;
import org.openrewrite.javascript.internal.PackageJsonHelper;
import org.openrewrite.javascript.marker.NodeResolutionResult;
import org.openrewrite.javascript.marker.NodeResolutionResult.Dependency;
import org.openrewrite.javascript.internal.MatchedDependency;
import org.openrewrite.javascript.table.NodeDependencyProtocolsSkipped;
import org.openrewrite.javascript.table.NodeLockRegenerationFailures;
import org.openrewrite.json.tree.Json;
import org.openrewrite.marker.Markup;
import org.openrewrite.text.PlainText;
import org.openrewrite.yaml.tree.Yaml;

import java.nio.file.Path;
import java.util.List;

@EqualsAndHashCode(callSuper = false)
@Value
public class ChangeDependency extends ScanningRecipe<NodeDependencyScan.Accumulator> {

    transient NodeLockRegenerationFailures lockRegenerationFailures = new NodeLockRegenerationFailures(this);
    transient NodeDependencyProtocolsSkipped protocolsSkipped = new NodeDependencyProtocolsSkipped(this);

    @Option(displayName = "Old package name",
            description = "The current name of the npm package to rename.",
            example = "lodash")
    String oldPackageName;

    @Option(displayName = "New package name",
            description = "The new name to use for the package.",
            example = "lodash-es")
    String newPackageName;

    @Option(displayName = "New version",
            description = "Optional new version constraint to set on the renamed package.",
            example = "^5.0.0",
            required = false)
    @Nullable String newVersion;

    @Option(displayName = "Scope",
            description = "The dependency scope: `dependencies`, `devDependencies`, etc. " +
                    "When omitted, all scopes are searched.",
            valid = {"dependencies", "devDependencies", "peerDependencies",
                    "optionalDependencies", "bundledDependencies"},
            example = "dependencies",
            required = false)
    @Nullable String scope;

    @Override public String getDisplayName() { return "Change npm dependency"; }
    @Override public String getInstanceNameSuffix() { return String.format("`%s` -> `%s`", oldPackageName, newPackageName); }

    @Override public String getDescription() {
        return "Renames an npm dependency in `package.json` and optionally updates its version constraint. " +
                "After modifying the package.json, the lock file is regenerated by running the package manager. " +
                "Not safe to use as a precondition: invokes the package manager and publishes per-project " +
                "state shared with other dependency recipes.";
    }

    @Override public NodeDependencyScan.Accumulator getInitialValue(ExecutionContext ctx) { return new NodeDependencyScan.Accumulator(); }

    @Override
    public TreeVisitor<?, ExecutionContext> getScanner(NodeDependencyScan.Accumulator acc) {
        return new TreeVisitor<Tree, ExecutionContext>() {
            @Override public Tree preVisit(Tree tree, ExecutionContext ctx) {
                stopAfterPreVisit();
                if (!(tree instanceof SourceFile)) return tree;
                SourceFile sf = (SourceFile) tree;
                Path p = sf.getSourcePath();
                String basename = p.getFileName().toString();

                if (PackageJsonHelper.isLockFile(basename)) {
                    if (sf instanceof Json.Document || sf instanceof Yaml.Documents || sf instanceof PlainText) {
                        Path packagePath = PackageJsonHelper.correspondingPackageJsonPath(p);
                        NodeDependencyScan.ProjectState ps = acc.projects.computeIfAbsent(packagePath, k -> new NodeDependencyScan.ProjectState());
                        ps.capturedLockContent = sf.printAll();
                        acc.lockToPackage.put(p, packagePath);
                    }
                    return tree;
                }
                if (sf instanceof Json.Document && "package.json".equals(basename)) {
                    NodeResolutionResult marker = sf.getMarkers().findFirst(NodeResolutionResult.class).orElse(null);
                    if (marker == null) return tree;
                    NodeDependencyScan.ProjectState ps = acc.projects.computeIfAbsent(p, k -> new NodeDependencyScan.ProjectState());
                    ps.capturedPackageJson = sf;
                }
                return tree;
            }
        };
    }

    private boolean matchesChange(SourceFile pkg) {
        NodeResolutionResult marker = pkg.getMarkers().findFirst(NodeResolutionResult.class).orElse(null);
        if (marker == null) return false;
        if (scope != null) {
            return containsIn(getScopeDeps(marker, scope));
        }
        return containsIn(marker.getDependencies()) || containsIn(marker.getDevDependencies())
                || containsIn(marker.getPeerDependencies()) || containsIn(marker.getOptionalDependencies())
                || containsIn(marker.getBundledDependencies());
    }

    private boolean containsIn(@Nullable List<Dependency> deps) {
        if (deps == null) return false;
        for (Dependency d : deps) if (oldPackageName.equals(d.getName())) return true;
        return false;
    }

    /**
     * Record the matched dependency when its value is a specifier protocol, so the run reports that the
     * declaration was left alone rather than renamed into a reference that no longer resolves.
     */
    private void collectProtocolSkip(SourceFile pkg, NodeDependencyScan.ProjectState ps) {
        ps.skippedProtocols.clear();
        NodeResolutionResult marker = pkg.getMarkers().findFirst(NodeResolutionResult.class).orElse(null);
        if (marker == null) {
            return;
        }
        for (String scopeName : new String[]{"dependencies", "devDependencies", "peerDependencies",
                "optionalDependencies", "bundledDependencies"}) {
            if (scope != null && !scope.equals(scopeName)) continue;
            List<Dependency> deps = getScopeDeps(marker, scopeName);
            if (deps == null) continue;
            for (Dependency d : deps) {
                if (!oldPackageName.equals(d.getName())) continue;
                String constraint = d.getVersionConstraint() == null ? "" : d.getVersionConstraint();
                if (PackageJsonHelper.dependencySpecifierProtocol(constraint) != null) {
                    ps.skippedProtocols.add(new MatchedDependency(d.getName(), scopeName, constraint));
                }
            }
        }
    }

    /** One row per matched dependency the rename could not safely touch, emitted once per project. */
    private void reportProtocolSkips(ExecutionContext ctx, NodeDependencyScan.ProjectState ps, Path packageJsonPath) {
        if (ps.protocolsReported || ps.skippedProtocols.isEmpty()) {
            return;
        }
        ps.protocolsReported = true;
        for (MatchedDependency skipped : ps.skippedProtocols) {
            protocolsSkipped.insertRow(ctx, new NodeDependencyProtocolsSkipped.Row(
                    packageJsonPath.toString(),
                    skipped.getPackageName(),
                    skipped.getDependencyScope(),
                    PackageJsonHelper.dependencySpecifierProtocol(skipped.getCurrentVersion()),
                    skipped.getCurrentVersion(),
                    newVersion == null ? "" : newVersion));
        }
    }

    private @Nullable List<Dependency> getScopeDeps(NodeResolutionResult marker, String scopeName) {
        switch (scopeName) {
            case "dependencies": return marker.getDependencies();
            case "devDependencies": return marker.getDevDependencies();
            case "peerDependencies": return marker.getPeerDependencies();
            case "optionalDependencies": return marker.getOptionalDependencies();
            case "bundledDependencies": return marker.getBundledDependencies();
            default: return null;
        }
    }

    /**
     * Mark the manifest with why the rename was refused. A warning rather than an error: the framework
     * attaches {@link Markup.Error} when a recipe throws, so an error here would be indistinguishable
     * from this recipe having crashed. Nothing is broken; a requested change was declined and the file
     * is left valid. Attached once, because a marker is a new tree instance every time and re-marking
     * each cycle would keep the recipe from ever stabilizing.
     */
    private SourceFile markProtocolSkips(SourceFile sf, NodeDependencyScan.ProjectState ps) {
        if (ps.skippedProtocols.isEmpty() || sf.getMarkers().findFirst(Markup.Warn.class).isPresent()) {
            return sf;
        }
        StringBuilder message = new StringBuilder();
        for (MatchedDependency skipped : ps.skippedProtocols) {
            if (message.length() > 0) {
                message.append(' ');
            }
            message.append("`").append(skipped.getPackageName()).append("` is declared as `")
                    .append(skipped.getCurrentVersion()).append("`, a ")
                    .append(PackageJsonHelper.dependencySpecifierProtocol(skipped.getCurrentVersion()))
                    .append(" reference whose constraint is held elsewhere and keyed on the current name.");
        }
        message.append(" Renaming it here would leave that reference dangling and the manifest would no")
                .append(" longer install, so `").append(oldPackageName).append("` was left unchanged.")
                .append(" Rename it in the file holding the constraint first.");
        return Markup.warn(sf, new IllegalStateException(message.toString()));
    }

    @Override
    public TreeVisitor<?, ExecutionContext> getVisitor(NodeDependencyScan.Accumulator acc) {
        NodeDependencyScan.linkWorkspaceMembers(acc);
        return new TreeVisitor<Tree, ExecutionContext>() {
            @Override public Tree preVisit(Tree tree, ExecutionContext ctx) {
                stopAfterPreVisit();
                if (!(tree instanceof SourceFile)) return tree;
                SourceFile sf = (SourceFile) tree;
                Path p = sf.getSourcePath();

                NodeDependencyScan.ProjectState ps = acc.projects.get(p);
                if (ps != null && ps.capturedPackageJson != null) {
                    if (matchesChange(sf)) {
                        collectProtocolSkip(sf, ps);
                        reportProtocolSkips(ctx, ps, p);
                        ensureComputed(ps, sf, ctx);
                    }
                    if (ps.modifiedPackageJson != null) {
                        SourceFile out = ps.modifiedPackageJson;
                        PackageJsonHelper.putLiveTree(ctx, p, out);
                        if (ps.regenResult != null && !ps.regenResult.isSuccess()) {
                            recordFailure(ctx, ps, p);
                            return Markup.warn(out, new RuntimeException(
                                    "lock regeneration failed: " + ps.regenResult.getErrorMessage()));
                        }
                        return markProtocolSkips(out, ps);
                    }
                    if (!ps.skippedProtocols.isEmpty()) {
                        return markProtocolSkips(sf, ps);
                    }
                }

                Path packagePath = acc.lockToPackage.get(p);
                if (packagePath == null) return tree;
                NodeDependencyScan.ProjectState rootPs = acc.projects.get(packagePath);
                if (rootPs == null) return tree;

                for (Path importer : NodeDependencyScan.lockImporters(acc, packagePath, rootPs)) {
                    NodeDependencyScan.ProjectState ips = acc.projects.get(importer);
                    if (ips == null) continue;
                    if (ips.modifiedPackageJson == null) {
                        SourceFile pkg = PackageJsonHelper.getLiveTree(ctx, importer);
                        if (pkg == null) pkg = ips.capturedPackageJson;
                        if (pkg != null && matchesChange(pkg)) {
                            ensureComputed(ips, pkg, ctx);
                            if (ips.modifiedPackageJson != null) {
                                PackageJsonHelper.putLiveTree(ctx, importer, ips.modifiedPackageJson);
                            }
                        }
                    }
                    if (ips.regenResult != null) {
                        if (ips.regenResult.isSuccess()) {
                            return PackageJsonHelper.reparseLock(sf, ips.regenResult.getLockFileContent());
                        }
                        recordFailure(ctx, ips, importer);
                        return Markup.warn(sf, new RuntimeException(
                                "lock regeneration failed: " + ips.regenResult.getErrorMessage()));
                    }
                }
                return tree;
            }

            private void ensureComputed(NodeDependencyScan.ProjectState ps, SourceFile pkg, ExecutionContext ctx) {
                if (ps.modifiedPackageJson != null) return;
                PackageJsonHelper.EditAndRegenerateResult r = PackageJsonHelper.editAndRegenerate(
                        pkg,
                        doc -> PackageJsonHelper.changeDependency(doc, oldPackageName, newPackageName, newVersion, scope),
                        ps.capturedLockContent,
                        ctx);
                if (r.isChanged()) {
                    ps.modifiedPackageJson = r.getModifiedPackageJson();
                    ps.regenResult = r.getRegenResult();
                }
            }
        };
    }

    private void recordFailure(ExecutionContext ctx, NodeDependencyScan.ProjectState ps, Path packageJsonPath) {
        if (ps.failureRecorded || ps.regenResult == null) {
            return;
        }
        ps.failureRecorded = true;
        LockFileRegeneration.insertFailureRow(ctx, lockRegenerationFailures, packageJsonPath, ps.regenResult, oldPackageName);
    }
}
